### ISSUE TITLE
a blank partial causes error and stalls compiling

### ISSUE THREAD

**Issue by amycheng** [assemble/assemble#111]
I got the following error:

`Warning: You must pass a string or Handlebars AST to Handlebars.compile. You passed  Use --force to continue.`

don't know if this is a bug or just how Handlebars works 

Add content to the partial solves the error.

I just like having blank partials as placeholders

**Comment by ChadRidings** [comment]
Can't thank you enough for sharing this information.  I was building out my framework... I knew I was going to use a footer partial so I added it but kept it blank while I waited for the design.  Grunt was halting at Assemble... tried everything under the sun for a good 2 hours.  Saw this post, added a blank div to the footer partial... and woola, I'm back up and running.  Again, thank you for sharing!
