### ISSUE TITLE
Is it possible to generate multiple files from one template?

### ISSUE THREAD

**Issue by tommack** [assemble/assemble#184]
If I have a data file like (this can be in any format that's convenient): 

```
[
  {name: "a", content: "content for a"},
  {name: "b", content: "content for b"}
]
```

And a template like: `<html> ... {{content}} ... </html>`

Where I would like to generate two files:

a.html: `<html> ... content for a ... </html>`
b.html: `<html> ... content for b ... </html>`

Is this possible to configure? I would not know the number of entries in the data file ahead of time.

**Comment by lindsaymacvean** [comment]
Hi jonschlinkert, how would I implement a grunt file to run with this?

**Comment by lindsaymacvean** [comment]
I figured it out here http://stackoverflow.com/questions/34934362/grunt-assemble-multiple-files-from-one-datafile

**Comment by jonschlinkert** [comment]
Great! sorry I didn't have a chance to respond, glad you got it sorted out.

**Comment by lindsaymacvean** [comment]
:) thanks for an awesome tool.

**Comment by calvinszeto** [comment]
Hi, hate to ask a vague question like this, but does this feature work in a gulpfile? I'm using assemble directly in a gulpfile like so:
<pre>
var assemble = require('assemble')();
...
gulp.task('assemble', ['clean'], function () {
    // Use Assemble to assemble Handlebars templates, layouts, etc.
    assemble.partials('./partials/**/*.hbs');
    assemble.layouts('./layouts/**/*.hbs');
    assemble.pages('./pages/**/*.hbs');

    loadHelpers();

    var data = require('./hbs_context.json');
    assemble.data(data);
    assemble.data({root: process.cwd()});

    return assemble.toStream('pages')
        .pipe(assemble.renderFile())
        .pipe(plugins.extname()) // Converts .hbs to .html
        .pipe(gulp.dest('.tmp/'));
});
</pre>

I have a layout and a context with an array of objects in it. I would like to create a number of pages, one for each object in the array, using the layout (basically, the same situation presented in the first post of this issue). From digging around, I couldn't find anything in the docs, and the code examples I found used Grunt and gists for data. Would appreciate any help. Thanks!!

**Comment by jonschlinkert** [comment]
@calvinszeto please open a new issue or preferably ask implementation questions on stackoverflow, and feel free to link them back to an issue here. thanks
