### ISSUE TITLE
Is it possible to define and pass data to an Assemble partial inline?

### ISSUE THREAD

**Issue by keeganstreet** [assemble/assemble#228]
In ERB, I can do it like this:

```
<%= partial("inputtext", :locals => {
    :id => "fistname",
    :label => "First name"
}) %>
```

I know I can pass data to an Assemble partial if it is already defined, e.g:

```
{{> inputtext predefinedData }} 
```

But can I define the data inline?

**Comment by onokumus** [comment]
assemble v0.1.6.2

`partials: btn-basic.hbs`
``` handlebars
<button class="{{modifier}}">
    {{text}}
</button>
```

`pages`
``` handlebars
{{> btn-basic modifier="btn btn-danger btn-lg" text="click me"}}
```

`result`

```html
<button class="btn btn-danger btn-lg">
  click me
</button>
```

**Comment by jonschlinkert** [comment]
@onokumus this is a good question for stackoverflow, fwiw it's more of a handlebars questions

**Comment by esr360** [comment]
@onokumus is it possible to set default options with this method? If so, how?

**Comment by onokumus** [comment]
@esr360 

``` handlebars
<button class="btn {{#if modifier}}{{modifier}}{{else}}btn-default{{/if}}">
    {{text}}
</button>
```

``` handlebars
{{> btn-basic text="button 1"}}
{{> btn-basic modifier="btn-danger btn-lg" text="button 2"}}
```

`result`

```html
<button class="btn btn-default">
  button 1
</button>

<button class="btn btn-danger btn-lg">
  button 2
</button>
```

**Comment by esr360** [comment]
@onokumus thank you so much, great solution!

**Comment by MickL** [comment]
Using this helper as described here: http://assemble.io/helpers/helpers-data.html i see:
`[object Object]` instead of the partial {{> input }}. 

Any idea?

**Comment by DigitalMiner** [comment]
I know this is a very old thread, but I am just starting out with Assemble and getting an issue with the parseJSON above. 

I've copied the code exactly (just renamed the partial) and all that renders is 
`[object Object]` 

Any ideas what is causing this? 

Cheers
