### ISSUE TITLE
Looping over a folder of partials

### ISSUE THREAD

**Issue by haustraliaer** [assemble/assemble#254]
One thing I am struggling with is how to load up a bunch of handlebars _files_ from a folder via a loop.

I'd like to do something like the following in a template, or a page (or even a partial):

```
files: 'path/to/files/*.hbs'
----

{{#each files}}
    <div class="container">
        {{ this }} 
    </div>
{{/each}}
```

With the output being:

```
    <div class="container">
        file 1 contents
    </div>

    <div class="container">
        file 2 contents
    </div>

    <div class="container">
        file 3 contents
    </div>

    <div class="container">
        etc..
    </div>
```

The important thing here is that I don't want to have to specify (or link to) each new partial as I create them, all I want to have to worry about is adding a new file with the right content to the right folder.

Here are a few things I tried without any luck just yet...

---

Where a template file has `{{> body}}` to pull a bunch of files from a folder and output them as individual `.html` files - perhaps there is a method to pull them in via assemble to a single file? I'm currently reading through the docs to figure this one out, but nothing jumps out at me.

---

I also found the `{{ md this }}` helper to _almost_ work. I modified it to not parse markdown, however it would only insert _all_ of the files into the single container. For example:

```
files: 'path/to/files/*.hbs'
----

{{#each files}}
    <div class="container">
        {{ md this }}
    </div>
{{/each}}
```

Would output this:

```
    <div class="container">
        file 1 contents
        file 2 contents
        file 3 contents
        etc...
    </div>
```

Which is not the _desired_ outcome. If I list the files in the YML front matter eg: `['file1.hbs', 'file2.hbs', 'file3.hbs']` it works perfectly, but defeats the objective of _not_ having to update that list.

---

I also tried using the include helper, but couldn't get that to work either (it only seemed be able to grab individual files).

---

Is this actually something I should be looking to do in the Gruntfile instead of with handlebars logic? Is it something I should use collections to handle? Or is it simply not possible yet (if not I'd definitely request it as a feature). Any help in the right direction would be much appreciated.

**Comment by mrmartineau** [comment]
@haustraliaer did you ever get a good working version of this? I'd like to use something like this on a styleguide too

**Comment by haustraliaer** [comment]
@mrmartineau gawd I haven't touched static websites for a long time now, sorry - been mostly working with react apps etc, so all my views are generated after load (unless pre-rendered on the server). I must have solved it above with the plugin code shown in the comment, because I closed the issue - so your best bet is starting there. Although I'm not sure how much assemble has changed since then ;P

**Comment by mrmartineau** [comment]
@haustraliaer ok, no worries. I've been using your code without much luck but I'll stick at it.

**Comment by mrmartineau** [comment]
FWIW, the official [aggregate](https://github.com/helpers/handlebars-helper-aggregate) helper perfectly does what I need.

**Comment by mdunbavan** [comment]
Hi, I have been trying to figure out how I can add a news collection where each item/post added into the news folder can then be used to create a list of posts in my main pages/news.hbs page. I have been racking my brain about this. If I run through my idea is it possible with this plugin above?

1. I create a collection in my gruntfile.js
```
        {
            name: 'newsMain',
            sortby: 'postedon',
            sortorder: 'ascending' 
          },
```

2. I create the assemble news options as below:

```
news: {
        options: {
          flatten: true,
          assets: '<%= config.dist %>/assets',
          layout: '<%= config.src %>/templates/layouts/default.hbs',
          data: '<%= config.src %>/data/*.{json,yml}',
          partials: '<%= config.src %>/templates/partials/*.hbs'
        },
        files: {
          '<%= config.dist %>/news/': ['<%= config.src %>/templates/news/*.hbs']
        }
      },
```

3. I then add a new post-one.hbs in /src/templates/news/ which gets assembled inside /dist/news/post-one.html
This process is repeated over and over

4. This bit is not working at all,I am trying to list out the posts in my /src/templates/pages/news.hbs
The below code gives me nothing at all.
```
{{#each posts}}
            {{#withSort posts "data.postedon"}}
                <div>
                    <h2><a href="/{{relativeLink}}">{{data.title}}</a></h2>
                    <p>By {{data.author}} on {{data.posted}}</p>
                    <p><a href="/{{relativeLink}}">more...</a></p>
                </div>
            {{/withSort}}
    {{/each}}
```

Nothing works and nothing gets outputted. I have attached a gist file below:
https://gist.github.com/mdunbavan/23d87058f31be0e05cca
Will the above plugin simplify what I want to do with my attempt above?
