### ISSUE TITLE
middleware: collections, filtering and sorting

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble#335]
@doowb, how about just keeping the collections object and necessary properties in assemble, and then put the logic for sorting etc. in plugins?

**Comment by andyra** [comment]
I'm having trouble sorting pages. I've added some YAML to my content to be able to pull out certain pages into a global nav menu, like so:
```
---
layout: default.hbs
title: Getting Started
navigation: main
sortOrder: 1
---
```
Another page might have `sortOrder` set to `2`, which I would expect to appear second. So far so good.

In my Handlebars template, I'm using the Assemble `withSort` helper to grab all the pages that have `navigation` set to `main` and sort them by the `sortOrder` metadata.

```
{{#withSort pages "data.sortOrder"}}
  {{#is data.navigation "main"}}
    <li>{{data.title}}</li>
  {{/is}}
{{/withSort}}
```

The list items are showing up, but they're not sorted at all (or if they are, it's alphabetically and not according to the `sortOrder` I specified). From what I've read in the Assemble docs, it _seems_ like this should work.

**Comment by jvwing** [comment]
Your code looks ok as shown.  But I would say that it sorts first and THEN grabs pages with `data.navigation` equal to  `main`, so you might get unexpected results if all of the sorted pages do not have `sortOrder` values.  

You might have better results using a [custom collection](http://assemble.io/docs/Collections.html) with the [`sortorder` option specified](http://assemble.io/docs/options-collections.html).  I have used that approach successfully.

For troubleshooting, I recommend isolating the code in it's own template while you debug it, to prevent interaction effects from other iterations. I've also found it helpful to build a table with the sort and filter criteria as separate columns, so I can visualize what's going on.

**Comment by andyra** [comment]
Ah, very good! The custom collections was a great suggestion, and I even found a [blog post by Andi Smith](http://www.andismith.com/blog/2014/02/creating-a-list-of-posts-in-assemble/) (also a commenter on #230) which explained how to implement custom collections and sorting.

Content:
```
---
layout: default.hbs
title: Getting Started
navMain: true
navOrder: 1
---
```
Template:
```
{{#withSort navMain 'data.navOrder'}}
  {{#each this.pages}}
    <li>
      <a href="{{prettyLink this.dest}}">{{data.title}}</a>
    </li>
  {{/each}}
{{/withSort}}
```

**Comment by jonschlinkert** [comment]
done, done and done! couldn't be easier to create custom collections than with the latest assemble (0.6.0 and up).

```js
var assemble = require('assemble');
var app = assemble();

// create a collection
app.create('docs');

// add a template to the collection
app.docs('foo', {content: 'this is content'});
```

To sort, group or paginate, just use a plugin or middleware. see:

- https://github.com/doowb/templates-indexer
- https://github.com/doowb/paginationator
