### ISSUE TITLE
Feature: ability to pass arguments to partials

### ISSUE THREAD

**Issue by d9su** [assemble/assemble#416]
Recently I have noticed a problem about reusing partials. So I have a block of html that will be reused multiple times, potentially on the same page, too. For example, a simple form that's attached to each actionable items on the page. If I have 10 actionable items, I have 10 of those forms.

The problem is, since those forms are identical, the same ID cannot appear twice on a page. The ideal case is when I generate those actionable items, I can invoke the form partial with the ID of the actionable item, so all the IDs in the form partial will be changed accordingly to not only make them unique, but also associated with the right elements.

As far as I know, the only argument I can pass to a partial is "this", which is the context of the page invoking the partial. It'd be nice if we can customize this argument.

**Comment by brunowego** [comment]
:+1:
