### ISSUE TITLE
bug: variables persist across pages

### ISSUE THREAD

**Issue by fitnr** [assemble/assemble#423]
The gist of this is that variables defined in the YFM of one page are persisting in the next page, which is giving unexpected results. This is happening when a child layout defines some variable in its YFM. Pages rendered later on with the parent layout are seeing those variables, which breaks defaults.

An outline of the problem:

`default.hbs` has some behavior with a variable:
```
...
{{#if foo_var}}
Something happens
{{/if}}
...
```

`layouts/special_layout.hbs` looks like this:
```
---
layout: default.hbs
foo_var: "special value"
---
```

If we have two content files, `a.html` and `b.html`, with a using the "special" layout and b using "default", b.html will see `foo_var: "special value"`. Expected behavior would be for b.html to see no value for foo_var.

[This gist demonstrated](https://gist.github.com/fitnr/8340708) to demonstrate (since gists can't have directories, I've indicated them with underscores in the filenames).

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of assemble
