### ISSUE TITLE
Add support for...

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble#43]
**IMPLEMENTED IN ASSEMBLE v0.6.0!** Any engine can be registered like:

``` js
assemble.engine('swig', require('engine-swig');
```

---

Templating engines under consideration. Comments/feedback encouraged.
- [x] [mustache](https://github.com/janl/mustache.js)
- [x] [handlebars](https://github.com/wycats/handlebars.js/) [(website)](http://handlebarsjs.com/)
- [ ] [underscore](https://github.com/documentcloud/underscore) [(website)](http://documentcloud.github.com/underscore/)
- [ ] [Nunjucks](http://nunjucks.jlongster.com/) . Seems to share a lot of similarities with liquid, from the docs "It is a direct port of the Python-powered jinja2 templating engine and aims to be feature-complete with jinja2."
- [ ] [Eco](https://github.com/sstephenson/eco)
- [ ] [dust](https://github.com/akdubya/dustjs) [(website)](http://akdubya.github.com/dustjs/)
- [ ] [ejs](https://github.com/visionmedia/ejs)
- [ ] [haml](https://github.com/visionmedia/haml.js) [(website)](http://haml-lang.com/)
- [ ] [haml-coffee](https://github.com/9elements/haml-coffee) [(website)](http://haml-lang.com/)
- [ ] [hogan](https://github.com/twitter/hogan.js) [(website)](http://twitter.github.com/hogan.js/)
- [ ] [jade](https://github.com/visionmedia/jade) [(website)](http://jade-lang.com/)
- [x] [swig](https://github.com/paularmstrong/swig) [(website)](http://paularmstrong.github.com/swig/)
- [ ] [liquid.js](https://github.com/darthapo/liquid.js) 

If you would like an engine added to the list, please make a comment on this issue so I can add it to the list for consideration.

**Comment by airtonix** [comment]
by the way, you should be using liquid.coffee instead of liquid.js.... actually you should just be creating an abstract TemplateEngineBaseClass that lets us describe how templates (and the template tags and filters) get rendered.

**Comment by jonschlinkert** [comment]
assemble v0.6.0 makes this extremely simple.

**Comment by airtonix** [comment]
@jonschlinkert in what way? configuration settings or by using render plugins?

If it's configuration settings, then you've just delayed half the problem for a short while.

But if assembles render process is done through plugins then good stuff.

Also links to any documentation or blueprints describing this new v6 render process please.

**Comment by jonschlinkert** [comment]
:+1:
