### ISSUE TITLE
Error while using {{#eachProperty}}: path must be a string

### ISSUE THREAD

**Issue by regiskuckaertz** [assemble/assemble#444]
I have a hash that I use to add custom attributes to elements:

```
"tagName": "button",
"attrs": {
  "data-mq": "only screen and (min-width: 45em)",
  "data-src": "highres.jpg"
}
```

But Assemble seems to choke on `{{ value }}`, i.e. in my template, the following does not work:

```
<{{tagName}}
  {{#eachProperty attrs}}
    {{key}}="{{value}}"
  {{/eachProperty}}
  >
```

It works when I remove `{{ value }}` though. So I thought that perhaps the string `value` was a reserved word? Indeed when I changed the helper to use another key name, it worked perfectly. In [helpers-collections.js, line 489](https://github.com/assemble/handlebars-helpers/blob/master/lib/helpers/helpers-collections.js#L489):

```
results.push(options.fn({
  key: key,
  val: value
}));
```

And in my template:

```
<{{tagName}}
  {{#eachProperty attrs}}
    {{key}}="{{val}}"
  {{/eachProperty}}
  >
```

Is it possible that some names are reserved? I had issues with `content` as well.

**Comment by dudewad** [comment]
Facepalm. This helped. Thanks.
