### ISSUE TITLE
Support lo-dash variables for yfm layout property

### ISSUE THREAD

**Issue by pwalczyszyn** [assemble/assemble#472]
In my child layouts I would like to dynamically specify parent layout based on variable passed from my gruntfile. Something as following:

```
---
layout: <%= parentLayout %>
---
```

When I use example above I get following error: `Warning: Layout file (src/layouts/<%= parentLayout %>) not found.`

**Comment by jonschlinkert** [comment]
closing based on age and since this was long ago fixed in grunt-assemble. this is also easy to do with the latest (0.6.0 assemble) using https://github.com/jonschlinkert/expand-front-matter
