### ISSUE TITLE
Clean up error handling (v0.5.0)

### ISSUE THREAD

**Issue by doowb** [assemble/assemble#500]
We're using node style methods in a lot of places throughout version 0.5.0 where functions are called like...
```js
assemble.someFunction(options, function (err, results) {
  if (err) {
    return assemble.log.error(err);
  }
  // do something with results
});
```
And the `someFunction` function might look like...
```js
assemble.someFunction = function (options, callback) {
  // do some work
  var results = {};
  // return results through callback
  callback(null, results);
};
```
Notice that if errors occur during `some work` they aren't caught properly inside the functions (like `someFunction`).

This issue is a reminder to fix this and handle errors better by making functions like `someFunction` look like this...
```js
assemble.someFunction = function (options, callback) {
  var results = {};
  try {
    // do some work
    results = {};
  } catch (err) {
    return callback(err);
  }
  callback(null, results);
};
```
If anyone finds a place like this, please just post a comment to this issue pointing it out and if you will send a pull request with a fix.

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of assemble
