### ISSUE TITLE
Is there a way to achieve a "nested" url structure or sub pages like "about/, about/team

### ISSUE THREAD

**Issue by drejohnson** [assemble/assemble#512]
This is a example folder structure that I'm trying to achieve.

templates/
├── pages
│   └── index.hbs (Home Page, example.com/)
└── about/
│   └──  index.hbs (About Page example.com/about)
││││└── team/ 
││││   └──  index.hbs (Team Page example.com/about/team)

**Comment by zukilover** [comment]
@drejohnson @jonschlinkert Hi, guys, I've just experienced the same issue, i.e not being able to generate such URL paths structure.

Is there any good news for this one?
