### ISSUE TITLE
Nest {{#extend}} within another {{#extend}}

### ISSUE THREAD

**Issue by spacedawwwg** [assemble/assemble#524]
I would like to be able to use layouts inside layouts (essentially to wrap partials in a container), such e.g:

I have my layout **layout-default.hbs** and another 'partial' layout **section.hbs**

```
{{#extend "layout-default"}}
	{{#content "featured"}}
		{{#extend "section"}}
			{{#content "section-title"}}Section Title 1{{/content}}
			{{#content "section-subtitle"}}Subtitle{{/content}}
			{{#content "section-body"}}
				{{> article articles.articleA}}
				{{> article articles.articleB}}
			{{/content}}
		{{/extend}}
		{{#extend "section"}}
			{{#content "section-title"}}Section Title 2{{/content}}
			{{#content "section-body"}}
				{{> article articles.articleC}}
				{{> article articles.articleD}}
			{{/content}}
		{{/extend}}
		{{#extend "section"}}
			{{#content "section-title"}}Section Title 3{{/content}}
			{{#content "section-body"}}
				{{> article articles.articleE}}
				{{> article articles.articleF}}
			{{/content}}
		{{/extend}}
	{{/content}}
	{{#content "main"}}
		<p>Main content</p>
	{{/content}}
{{/extend}}
```

This seems to work, except for the repeating the section. What happens it seems is that each {{#content}} are not independent of each {{#extend}} they are grouped and simply overwrite the values each time. Which means, in the example above, the {{#content "section-subtitle"}} is repeated for each subsequent {{#extend "section"}}

Does this make sense?

**Comment by jonschlinkert** [comment]
closing since this is really a challenge to be solved by the template engine or implementation details
