### ISSUE TITLE
Accessing custom variables in partial

### ISSUE THREAD

**Issue by shaunwallace** [assemble/assemble#526]
I found that for custom data to be passed to assemble templates I can do something like:

``` js
assemble: {
  options: {
    production: false 
  },
  ...
}
```

This works fine when accessing this variable inside of a page template like: 

``` handlebars
{{#if production}}
<script src="dist/assets/script.min.js"></script>
{{else}}
<script src="dist/assets/script.js"></script>
{{/if}}
```

but the issue that I am facing is that this variable cannot be accessed inside of a partial in the same way. What am I missing?

**Comment by DenisMir** [comment]
@sheedy Thanks for the information. Helped me out a lot. Using `@root` inside Assemble 0.4.x is a hit and miss. It is interesting that if you pass `@root` to one partial you don't have to pass it to other partials which is pretty weird.
