### ISSUE TITLE
Mixed html content within {{markdown}} tags

### ISSUE THREAD

**Issue by lmartins** [assemble/assemble#528]
Usually I have some html content mixed with markdown, specifically tables and other structures that would't be possible to achieve using markdown only.

A very simple example:
```
<figure class="Media Media--right w30">
    ![SMS Notifications]({{assets}}/images/Notifications-SMS.png)
    <figcaption>SMS Notifications Configuration</figcaption>
</figure>
```

This used to compile just fine as expected, but now is compiling into something like this:
```
<p>&lt;figure class=&quot;Media &quot;&gt;
    <img src="../../assets//images/Notifications.png" alt="Notifications">
    &lt;figcaption&gt;Notifications section&lt;/figcaption&gt;
&lt;/figure&gt;
</p>
```

Any way I can achieve the previous result or must I give on markdown entirely for this use case?

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of grunt-assemble and is not relevant to the current assemble
