### ISSUE TITLE
inArray compilation error if array empty

### ISSUE THREAD

**Issue by lmartins** [assemble/assemble#535]
Im using `inArray` helper to load JS files in some situations:

```
{{#inArray page.features "validation"}}
    <script src="//cdnjs.cloudflare.com/ajax/libs/parsley.js/2.0.0/parsley.min.js"></script>
  {{/inArray}}
```

This picks up the array declared in front matter:

```
features:
- common
- validation
```

The problem with this is that if one page doesn't have this array, or the array is empty, when compiling I get: 

```
Assembling ../EN/features/index.html ERROR
Warning: Array.prototype.indexOf called on null or undefined Used --force, continuing.
```

Any way to get around this?

**Comment by esr360** [comment]
I think this should be a default feature to be honest. Thoughts? The inArray feature isn't that useful if you have to declare the array in every page.

**Comment by jonschlinkert** [comment]
this is a really old bug report, and it's related to https://github.com/jonschlinkert/handlebars-helper-inarray, which has very little code. I think we can make changes pretty easily to that lib if it makes sense but we should open a new issue there to discuss if necessary

**Comment by esr360** [comment]
You're right my apologies, I thought inArray was a default Assemble feature.

**Comment by jonschlinkert** [comment]
no worries! I didn't mean for that to come of like I was giving you a hard time. I was just pointing it out guessing that you hadn't noticed - I've done the same...
