### ISSUE TITLE
Bug when json file name and key has the same name.

### ISSUE THREAD

**Issue by duanhuiwen** [assemble/assemble#536]
For example I have a file named lang.json which is like below

```json
{
 "lang": "en",
 "title": "index"
}
```

and when I use `{{ lang.title }}` in my handlebar partial, it will return empty instead of "index".

**Comment by Mike220889** [comment]
+1 for removal of this feature. It's _very_ confusing.

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of grunt-assemble and is not relevant to the current assemble
