### ISSUE TITLE
resolve-dep dependency causes missing `globule` module error

### ISSUE THREAD

**Issue by markosm** [assemble/assemble#539]
The `resolve-dep` dependency should probably be upgraded to the latest version in _package.json_. The current version referenced (`^0.3.4`) causes an `Error: Cannot find module 'globule'` when running _assemble_.

Please note that, as I myself just found out, the caret semver operator as used in `npm` enforces a major+minor constraint when the major version is `0`, instead of enforcing a constraint only on the major version as is performed for major versions `> 0`.

Steps to reproduce error:
- Delete the `assemble` directory from the `npm_modules` directory of a project using assemble.
- Run `npm install` again to freshly re-install `assemble` and its dependencies.
- Run the grunt `assemble` task.

Steps to resolve the error:
- Edit _assemble_'s `package.json` to reference version `^0.4.1` for dependency `resolve-dep`.

**Comment by tulik** [comment]
:+1:
