### ISSUE TITLE
Context of {{title}} in master template when using multiple data/json files

### ISSUE THREAD

**Issue by adrianjacob** [assemble/assemble#546]
I have scoured the docs looking to the answer for this but to no avail. Apologies for asking on here but having no joy anywhere else and not sure if it's a bug or just me being stupid. I cant be the only one in the world having this simple issue?

Link to stackoverflow:
http://bit.ly/1rs8cHc

Basically i am having context issues with {{title}} on the layout page when using mulyiple json files.

Any help would be much appreciated and hopefully others will find the answer and stop pulling their hair out too.

Thanks

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of grunt-assemble and is not relevant to the current assemble
