### ISSUE TITLE
Ordering blog posts, Assemble 0.4.x vs 0.5.x, etc.

### ISSUE THREAD

**Issue by nicholaswyoung** [assemble/assemble#550]
I've finally worked out how to configure Assemble, in it's most basic fashion, but one part eludes me: collections. The site I'm porting to Assemble currently has one section ([/notebook](http://nicholaswyoung.com/notebook)) where posts appear in a list, ordered with the most recently published first. (Currently, the link above is published with [Kirby CMS](http://getkirby.com), which I'm hoping to move away from. I share it here as an example of what I'm looking to achieve.)

I see that Assemble has a few basic constructs for this (e.g. Collections), but I don't know how to use 'em. The documentation isn't quite clear to me. How should I go about creating ordered blog lists with permalinks, pagination, etc.?

Are Collections the right methodology for this, or am I looking in the wrong place? Because I would rather not have to create file/directory structures that dictate ordering (as I'm currently doing in Kirby), and let the system decide which posts should be displayed first, based on the published date.

------

I've looked at the [assemble-blog](https://github.com/assemble/assemble-boilerplate-blog) package, but it's under heavy development (as I understand, anyway), and not suitable for reference. I'm also a bit confused about the new "middleware" packages, and what significance they carry, if any, in the world of Assemble 0.4.x.

------

Should I continue learning 0.4.x, with all it's ins-and-outs, or jump to the 0.5.x branch, and set myself up for the future? As a newcomer, I need a little guidance.

**Comment by jonschlinkert** [comment]
closing based on age
