### ISSUE TITLE
v0.6.0 what?!

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble#551]
That's right! we decided to go straight to v0.6.0. Why? Well, here are a few of the highlights.
## v0.6.0 features

In the upcoming release, here are just a few of the new features being introduced to Assemble:
- **CLI** v0.6.0 uses the same config-style and CLI patterns as gulp. just run `assemble` at the command line.
- **Streams** (gulp-style): Assemble v0.6.0 uses [vinyl](https://github.com/wearefractal/vinyl)
- **Plugins/Tasks** (gulp-style): Since Assemble v0.6.0 also uses [orchestrator](https://github.com/orchestrator/orchestrator), not only does Assemble v0.6.0 have support for gulp-style streaming plugins, but any gulp plugin can be run by Assemble v0.6.0.
- **Parsers** (kerouac-style): Parsers are like express engines and they're registered the same way as well. Being parsers, they're used for parsing instead of rendering. As an example, the pre-loaded (default) parser will extend the context with data from yaml front matter.  
- **Engines** express-style engine support! Engines support has changed so dramatically in this version that we're considering this a new feature. Assemble v0.6.0 allows any engine from **[Consolidate](https://github.com/visionmedia/consolidate.js)** or **[Transformers](https://github.com/ForbesLindesay/transformers)** to be registered using `assemble.engine()`, just like [express](http://expressjs.com/4x/api.html#app.engine). To author a custom engine, follow the instructions on the [consolidate](https://github.com/visionmedia/consolidate.js) docs or the [transformers](https://github.com/ForbesLindesay/transformers) docs, depending on what you need.
- **Routes/Middleware** (express/kerouac-style): Express-style routes, but for static pages! In a nutshell, routes allow you to run a stack of middlewares against any pages that match any number of given regex or string patterns. Endless possibilities here (need revving/cache busting anyone?).

This is truly just for starters. There are many "smaller" features, and some of them are more exciting to me than any of the above (like support for **partial layouts**! yep, meaning that partials are able to use layouts - even nested layouts!). Stay tuned for updates!
## What about support for previous versions?

We'll be moving the code for previous versions to branches or repos where it makes sense, and of course we'll continue to  answer questions and help out where we can, but we won't be actively supporting previous versions beyond crucial bug fixes. 
## Grunt/Gulp

> [This new version will be decoupled from grunt? It will have a gulp plugin?](https://github.com/assemble/assemble/issues/550)

Yes, Assemble v0.6.0 will be completely independent, but we will also offer both grunt and gulp plugins for anyone who prefers those tool chains. Once v0.6.0 is released, the main difference for Grunt users will be the need to begin installing `grunt-assemble` instead of just `assemble` - which is how it should have been all along.

The Assemble core team will continue using Grunt, Gulp and whatever other tool works best on each particular project. 
## Q/A

Please feel free to ask questions, give feedback and help out with this release. If you're interested in helping out with anything, as always please let us know! We will definitely need help and feedback from the community to make this happen! 

What else do you want to know about this release?

**Comment by dotmagic** [comment]
I'm still searching for a complete example using assemble v0.6.0, grunt-assemble and the swig engine. The closest I've found is #579 and the Information here.

The manual is still not ready?

**Comment by jonschlinkert** [comment]
@dotmagic this issue is related to the release of assemble v0.6.0. grunt-assemble is a different project, and adding an engine is a different issue. keeping the discussions focused in the right repos/issues is one way to help us focus on getting the docs done.

**Comment by dotmagic** [comment]
@jonschlinkert Well, its related to the changes in assemble v0.6.0. I'm sorry because I've got lost, its really hard to collect the information from various places together. According your comment questions regarding swig engine are also wrong placed in grunt-assemble. So where's the correct place to ask about it? For now I've switched to handlebars and just wait until its ready. The new version sounds really promising, please forgive us we're so impatient ;-)

**Comment by ryanve** [comment]
Is 0.6.0 gonna be merged into master and published to npm anytime soon? I'm trying to figure out how to use handlebars 2.0 or higher with assemble. Which is the best assemble branch to use for this?

**Comment by jonschlinkert** [comment]
> Is 0.6.0 gonna be merged into master and published to npm anytime soon?

want to write some documentation?

**Comment by ryanve** [comment]
@jonschlinkert I'm still sort of figuring it out. I'm glad to help if I can. I've got the [assemble/tree/handlebars-2.0.0](https://github.com/assemble/assemble/tree/handlebars-2.0.0) branch working with grunt-assemble.

**Comment by vwochnik** [comment]
I think I'm fairly familiar with Assemble v0.6.0. I'd certainly contribute a bit.
