### ISSUE TITLE
Improve the layout system

### ISSUE THREAD

**Issue by almeidap** [assemble/assemble#555]
It seems that I reached the limit of the current layout system of Assemble and I would love to see a more powerful and comprehensive solution to compose my pages.

For now, I am using a mix between the default layout system (\*.hbs files with YAML Front Matter, retrieved by the `layoutdir` options property) and the undocumented `#block`, `#extend` and `#content` layout "helpers" (*.hbs files retrieved by the `partials` options property):
https://github.com/assemble/handlebars-helpers/blob/master/lib/helpers/helpers-layouts.js

Looking around, It seems that this topic has been discussed for some time now:
#38, #201, #442, #480, #524, https://github.com/assemble/assemble-handlebars/issues/21, ...

...and it seems that there is some work on the way:
https://github.com/assemble/assemble/issues/524#issuecomment-48524811

In fact, IMHO, the `#block`, `#extend` and `#content` system should not be just basic helpers but the **first-class layout system** in Assemble. All my attempts to build my layout inheritance using the layout helpers have failed until now (untraceable exceptions, missing layouts, wrong context, unexpanded expressions, third-party helpers no more working inside `#content` body, etc.). And, to be honest, it's a real pain to understand whats going wrong behind the scene.

My suggestion would be to include YAML Front Matter layouts abilities into the current `#block`, `#extend` and `#content` approach, extended with another *tag*: `#layout`. Here is an on-the-fly example:

### base-layout.hbs
    {{#layout title="<%= package.title %>" uiLayout="base"}}
        <body class="{{uiLayout}}">
            {{#block "header"}}
                <h1>{{title}}</h1>
            {{/block}}
            {{#block "menu"}}{{/block}}
            {{> body}}
            {{#block "footer"}}{{/block}}
        </body>
    {{/layout}}

### default-layout.hbs
    {{#extend "base-layout" pageTitle="Default" uiLayout="default"}}
        {{#content "header" mode="prepend"}}
            <p class="lead">{{pageTitle}}</p>
        {{/content}}
        {{#content "menu"}}[Default menu]{{/content}}
        {{#content "footer"}}2014 (c) MyCompany{{/content }}
        <div id="content">
            {{> body}}
        </div>
    {{/layout}}

### index.hbs
    {{#extend "default-layout" pageTitle="Welcome"}}
        <p>Hello World! ;)</p>
    {{/layout}}

This would be awesome! I hope that this example is explicit enough to share my idea. Obviously, you should be able to nest `#extend` expressions, *tag* contents should be evaluated as expected and contexts should be adapted with the provided inline *tag* attributes.

**Comment by brunowego** [comment]
+1

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of assemble, and features like this are more appropriate for plugins or custom code
