### ISSUE TITLE
Extend page level data with external data files

### ISSUE THREAD

**Issue by kylerush** [assemble/assemble#560]
Hi guys,

We've been using Assemble heavily on Optimizley's new marketing website which will hopefully go live in the next couple of weeks. You can find the open source [repo here](https://github.com/optimizely/marketing-website).

One of the last issues we can't work out is a way to add data to the page level object from an external data file. 

For example, given the following directory structure:

```
|
+- website
|    +- about
|        +- index.hbs
|        +- contact.hbs
|        +- page.yml
```

The contents of `website/about/page.yml` are:

```
header: "About us"
```

We'd like to access the `website/about/page.yml` data in the `website/about/index.hbs` Handlebars template like so:

```
<h1>{{page.header}}</h1>
```

To output HTML like this:

```
<h1>About us</h1>
```

The data in `website/about/page.yml` (or JSON) would only be added to the `page` data object in the `.hbs` (or whatever template file) in the current directory. In the example above, `page.header` from `website/about/page.yml` would only be available to `website/about/index.hbs` and `website/about/contact.hbs`.

Because of requirements with our translation management system, we cannot store the copy in YAML frontmatter.

We're happy to fork assemble and do this work ourselves, but before we start, I'm wondering the following:

1. Is this a feature you'd be interested in merging into Assemble if we submit a PR?
2. Is there a way to do this natively in assemble without forking it?
3. If no on #2, do you have any advice/pointers before we start?

Thanks, guys. Assemble is really awesome. We love it and we're super excited to get into production with it.

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of assemble. this is currently possible using middleware, plugins or helpers
