### ISSUE TITLE
using plain html files as pages

### ISSUE THREAD

**Issue by rweng** [assemble/assemble#564]
So I've got the following Twitter widget in a page:

~~~
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
~~~

which is transformed by handlebars to

~~~
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?&#39;http&#39;:&#39;https&#39;;if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+&quot;://platform.twitter.com/widgets.js&quot;;fjs.parentNode.insertBefore(js,fjs);}}(document,&quot;script&quot;,&quot;twitter-wjs&quot;);</script>
~~~

So I don't know if this is a bug in handlebars, however, I figured since the page basically **is** this widget I just turn handlebars off and let the html be inserted into the layout directly. This is where I got stuck. I guess it's really simple but I just don't get it right now, so please clarify: How do I turn of handlebars for pages?

Thanks, Robin

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of grunt-assemble and is not relevant to the current assemble
