### ISSUE TITLE
lodash properties not rendered on sibling pages until page has been built

### ISSUE THREAD

**Issue by michaelfillier** [assemble/assemble#567]
I am using lodash in properties for a set of .hbs pages. These pages all have the same title structure, like this:

title: <%= year %> <%= city %> Winners
year: 2014
city: Toronto

There are about 13 different cities and a variety of years. Instead of hard coding the title each time, I wanted something reusable. It works fine except I have a sidebar on each of these pages that lists the other page titles in the collection. It is currently displaying like this:

(1st page)
2014 Toronto Winners
<%= year %> <%= city %> Winners
<%= year %> <%= city %> Winners
<%= year %> <%= city %> Winners
etc.

(2nd page)
2014 Toronto Winners
2014 Vancouver Winners
<%= year %> <%= city %> Winners
<%= year %> <%= city %> Winners
etc.

(etc)

So the first page title is only "rendered" when the actual page is processed. Yet, on the index for the section of the site,  the each loop renders the titles properly for ALL pages. Any ideas?

**Comment by jonschlinkert** [comment]
closing due to lack of follow up and since this refers to an outdated version of assemble
