### ISSUE TITLE
Problems with nested partials and contexts

### ISSUE THREAD

**Issue by sjparsons** [assemble/assemble#575]
I've run into a problem when having nested partials and passing in contexts to those partials. Below is a fairly detailed description, but I've also created a Github repository that includes a fully worked example of the problem: [sjparsons/assemble-partial-bug](https://github.com/sjparsons/assemble-partial-bug)

## Background

Imagine you have the Handlebars partials `tile-grid` and `tile` 
where `tile-grid` is defined as:

	<h2>{{ title }}</h2>

	<table>
		<tr>
			<td>
				{{> tile tile-1}}
			</td>
			<td>
				{{> tile tile-2}}
			</td>
		</tr>
	</table>

Here we can think of `tile-grid` as a 'parent' partial and `tile` is a 'child' 
partial. The `tile-1` and `tile-2` are references to the context to pass into
the partial. In our Assemble configuration we have set a data folder with the
files `tile-1.json` and `tile-2.json` that are loaded automatically when we
pass in the contexts `tile-1` and `tile-2` respectively. See 
[Assemble: Context](http://assemble.io/docs/Context.html) and Yehuda Katz's 
[answer on SO](http://stackoverflow.com/questions/11523331/passing-variables-through-handlebars-partial) for more information.

Let's say we have a page in Assemble with the following code.

	{{> tile-grid }}

This will correctly include the code from the parent partial `tile-grid` and
the two child partials `tile` with the correct contexts loaded.

## Problem

However, now, let's say we have a page in Assemble with the following code.
Where `tile-grid-1` refers to a context to pass to the parent partial. There is
a corresponding file in our data folder named `tile-grid-1.json`. 

	{{> tile-grid tile-grid-1}}

In this case, the child partials are rendered blank – essentially the context
specified in the parent partial are not passed through.

## Details

The [assemble-partial-bug](https://github.com/sjparsons/assemble-partial-bug) repository includes all the code needed to replicate this problem. 

* See the `src` folder for the partials, pages and data used.
* See the `build` folder for rendered HTML pages that demonstrate the problem.

**Comment by jonschlinkert** [comment]
closing since this was really a handlebars issue
