### ISSUE TITLE
Allow multiple layout directories

### ISSUE THREAD

**Issue by LaurentGoderre** [assemble/assemble#578]
I don't know if this is addressed in 6.0 but right now, data, helpers and partials can all specify multiple folder but layouts can't. We have structure of inheritance through project and have nested projects and it would be convenient to allow multiple directories where layouts can be placed.

**Comment by brunowego** [comment]
+1

**Comment by jonschlinkert** [comment]
Done. In v0.6.0, this is easy:

Glob pattern:

```js
assemble.layouts('foo/*.hbs');
```

Array of glob patterns:

```js
assemble.layouts(['foo/*.hbs', 'bar/*.hbs']);
```

Most methods are chainable, so you can also do:

```js
assemble
  .layouts('foo/*.hbs')
  .layouts('bar/*.hbs')
  .layouts('baz/*.hbs');
```

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of grunt-assemble and is easily possible with the current assemble
