### ISSUE TITLE
Looping around a YAML List : {{each}} vs {{eachProperty}} - page variables scope is lost

### ISSUE THREAD

**Issue by stephenwil** [assemble/assemble#582]
When looping around data using an {{each}} loop (and also a {{eachProperty}} loop), accessing page data - e.g. {{basename}} or even {{page.basename}} renders nothing.

Is this to do with scope, or is it an actual issue?

**Comment by lifeisfoo** [comment]
See handlebars documentation about paths http://handlebarsjs.com/#paths


>The ../ path segment references the parent template scope, not one level up in the context. This is because block helpers can invoke a block with any context, so the notion of "one level up" isn't particularly meaningful except as a reference to the parent template scope.

**Comment by jonschlinkert** [comment]
closing based on age and lack of follow up
