### ISSUE TITLE
assembly docs and code review

### ISSUE THREAD

**Issue by serebrov** [assemble/assemble#583]
This is not actually a single issue, but just a bunch of my thoughts after the first experience with assemble.
The text is too long, so I just put a Google Docs link to the document with review: https://docs.google.com/document/d/1HoMs0wvK33Oj4ZPLVijSjlAWMMbcGk4FezRxCY1Cn2E/edit?usp=sharing

Hope something useful for the core team can be found in the document.
Note: After writing the document I noticed there is new 0.6.0 version re-written from the ground up. So most of code review and suggested changes in the document can be irrelevant.

**Comment by jonschlinkert** [comment]
closing since the docs are maintained on a separate repo. also we love feedback but always prefer contributions.
