### ISSUE TITLE
How to define collection metadata/sort order?

### ISSUE THREAD

**Issue by MokoJumbie** [assemble/assemble#584]
I'm clear on how to store page metadata but for collections such as categories, whose data is derived from the page metadata.

e.g. I would like to sort my categories in a specific order. Currently, I'm defining a categoryMeta array of category metadata object.

```
[{
	"name" : "Category Name 1",
	"customProperty" : "someValue"
},{
	"name" : "Category Name 2",
	"customProperty" : "anotherValue"
}]
```

Then I perform comparisons with the actual categories when iterating through them.

Also, in this case I can use the array order to define the sort order for the categories. Like so:

```
{{#withSort categoryMeta "@index"}}
{{#each ../categories}}
{{#is category ../name}}
<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">{{category}}</a>
	<ul class="dropdown-menu" role="menu">
		{{#each pages}}
			<li>
				<a href="{{relative dest this.dest}}">{{ data.title }}</a>
			</li>
		{{/each}}
	</ul>
</li>
{{/is}}
{{/each}}
{{/withSort}}
```

Is there a better way to store metadata per category and to handle the sorting?

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of grunt-assemble and is not relevant to the current assemble.

also, please ask user questions on stackoverflow
