### ISSUE TITLE
Partials not using fullpath in v0.6.0

### ISSUE THREAD

**Issue by kmcgrath** [assemble/assemble#585]
I'd like to track this down further, but need some guidance on were the loading of the partials is actually happening.

I started using v0.6.0 because I have a similar setup described in issue #560 and I was drawn in by the line in the v0.6.0 docs that reads: `If a string or array of file paths or glob patterns is passed, pages will be read from the file system, parsed into an object, and stored on the cache using the full filepath of each page as its unique identifier.`

When trying this out I've discovered that as with 0.4.0 only the filename is stored in partials cache.  Even the [tests](https://github.com/assemble/assemble/blob/v0.6.0/test/assemble.partials.js#L110) don't include the full path, only the base filename.

If the intention is to use the *full filepath* as the key and someone could guide me to where the load is actually happening I'd like to try and get that to work.

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of assemble
