### ISSUE TITLE
Assemble or generator-assemble for an existing project?

### ISSUE THREAD

**Issue by neo-art** [assemble/assemble#589]
Hi,

I have an existing project built with yeoman-webapp (I also added bourbon/neat as a grid framework
+webplate ui kit) and I would like to use **assemble** as a static site generator.
Unfortunately I am not experienced with assemble at all so I was hopping you could share your
thoughts what would be the right way to do that:
**1**. to install *assemble alone in a separate directory* and after that to merge it with the
*yeoman-webapp* project;
or
**2**. to install *generator-assemble* directly in the yeoman-webapp root or some other folder
(i.e. *app/*)?

Thank you in advance :)

**Comment by jonschlinkert** [comment]
closing since this is more of a user question. please ask user questions on stackoverflow
