### ISSUE TITLE
Is it possible to supply a flat JSON structure for building pages

### ISSUE THREAD

**Issue by rob-lowe** [assemble/assemble#590]
Hi. First off thanks for all your hard work on Assemble!

I have been looking at coupling a CMS with Assemble but the CMS only supplies a flat JSON structure by default. Do all fields other than `filename` and `content` have to be nested under data (as in this sample below) or is it possible and have I simply been referencing them incorrectly?

    {
    "filename": "new-assemble-site",
    "data": {
        "title": "My new assemble site",
        "gists": ["5898072"]
    },
    "content": "Got a new website. It's built with Assemble"
    },

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of grunt-assemble. also this is more implementation related and is currently possible via custom plugins, middleware or helpers
