### ISSUE TITLE
Assemble v0.6.0 Example Repos

### ISSUE THREAD

**Issue by dtothefp** [assemble/assemble#591]
Hey @doowb @jonschlinkert this is David at Optimizely. I started playing around with your v0.6.0 for a personal project, with hopes of contributing and potentially porting v6 over to our marketing site.  I'm having a little bit of trouble reconciling common tasks in Grunt for v4 such as registering multiple layouts, pages, partials, etc with your v6 docs.  Do you have any example repos and task config using v6 that I could have a look through as I think this would be helpful in getting started?

**Comment by jonschlinkert** [comment]
@dtothefp closing since I think we've addressed this :) feel free to keep the discussion going
