### ISSUE TITLE
Handlebars Latest Version

### ISSUE THREAD

**Issue by DenisMir** [assemble/assemble#593]
After looking at the different Github milestones of the project it would be interesting to know some kind of roadmap. Will we see the 0.5 release or is it going directly to 0.6? I would be interested in something like the ```@root.<object>```that allows to access the root context directly from partials. (see #526)

**Comment by regiskuckaertz** [comment]
Hi guys! Is there any plan to upgrade Handlebars to v2 in the 0.4 branch? Would be much needed over here. So if you need any help in doing so, please tell me and I'll do my best to help you get there.

**Comment by doowb** [comment]
@regiskuckaertz do you know if there are any breaking changes with in Handlebars 2.0 that would cause older templates to break?

**Comment by doowb** [comment]
@rauberdaniel @DenisMir I created a [branch for Handlebars 2.0.0.](https://github.com/assemble/assemble/tree/handlebars-2.0.0). You can see the differences (mostly with empty lines and other html formatting). You can use this branch directly to use assemble 0.4.x with Handlebars 2.0.0.

```bash
npm install -D assemble/assemble#handlebars-2.0.0
```

**Comment by DenisMir** [comment]
@doowb Thank you very much. I will try it out and get back to you.

**Comment by regiskuckaertz** [comment]
Sorry I was off this week-end. We have been running multiple instances of the 0.4 branch with manually upgraded Handlebars for a while now without any problem. We didn't do any formal testing though.

**Comment by regiskuckaertz** [comment]
Alright so I may have found something finally and I can't wrap my head around it. Let's say I have:

- a bunch of pages: a.md, b.md and c.md
- one layout:

```
<!doctype>
<head>
{{> header }}
</head>
<body>
{{> body }}
</body>
</html>
```

- the `header` partial looks like:

```
<title>{{ title }}</title>
<link rel="stylesheet" href="{{ @root.assets }}css/styles.css">
```

In this case, only in the first assembled file will `@root.assets` be correctly interpreted to, say, `assets/`. For all subsequent files, it's going to be empty. **But** if for any reason there is a mention of `@root` in the layout, then it works like a charm.

There seems to be something happening with registered partials, although I can't see what or why. Anyway, I solved the problem by simply adding `<!-- {{ @root }} -->` in the layouts where the problem occured and will leave things as is until 0.6 is ready for prime time.

**Comment by jonschlinkert** [comment]
@regiskuckaertz would you mind creating a new issue that is focused on that topic?

> I'd be happy to assist you in making progress on 0.6)

thanks!

**Comment by regiskuckaertz** [comment]
Sure: https://github.com/assemble/assemble/issues/625

**Comment by DenisMir** [comment]
@doowb The 2.0.0 branch does work very well. It would be great if there would be the same for Handlebars 3.0.0 which includes some features like "dynamic partial names". Which Handlebars version does Assemble 0.6 include?

**Comment by jonschlinkert** [comment]
closing since this is more helper related and - if it's still an issue - should be moved to the `handlebars-helpers` issues
