### ISSUE TITLE
Jenkins: Cannot read property 'stage' of undefined assemble

### ISSUE THREAD

**Issue by shammar13** [assemble/assemble#594]
Hi guys
```js
Running "assemble:pages" (assemble) task
Warning: Cannot read property 'stage' of undefined Use --force to continue.
```
I'm getting this error when I run the assemble grunt task. However, this is slightly different from the other versions of this error that I've found. The task runs as expected on my local machine, but the error is thrown on my Jenkins build slave.

Both my dev machine (Windows 7) and the Jenkins slave (Windows Server 2012) have the same version of Node (v0.10.31)  and Grunt (v0.1.13) installed.

Any ideas how to resolve this?

**Comment by jonschlinkert** [comment]
closing based on age and since assemble v0.6.0 is in beta
