### ISSUE TITLE
Error when running `assemble.create('foo', 'foo')`

### ISSUE THREAD

**Issue by pburtchaell** [assemble/assemble#600]
Hey I just noticed that when you pass in a plural name for a template that is the same as the singular name, e.g., `assemble.create('foo', 'foo');`, the following error occurs: 

```    
return this[plural].apply(this, arguments);
                        ^
RangeError: Maximum call stack size exceeded
```
I doubt someone would do this very often (and, yes, I did this intentionally), but might be better to throw an error instead.

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of assemble
