### ISSUE TITLE
v0.6.0 defining pages to be rendered

### ISSUE THREAD

**Issue by Melindrea** [assemble/assemble#603]
Given the following Assemblefile.js, how do I get it to render the pages defined as `all`? And would there be any major differences if I wanted it to render a custom-defined 'posts' or 'tutorials' or whatever?

```
var assemble = require('assemble');

assemble.option({layout: 'master'});
assemble.pages('all', 'templates/*.hbs');
assemble.layouts('layouts/*.hbs');

assemble.task('default', function() {
  assemble.src('templates/*.hbs')
    .pipe(assemble.dest('_gh_pages'));
});
```

**Comment by DusanMilko** [comment]
When using example 3, multiple srcs with multiple destinations. Running each task alone creates the pages in the right location. But if I run both tasks at the same the time, the src of the first task persists into the 2nd task and generates extra pages. Is there a solution to this?

**Comment by doowb** [comment]
@DusanMilko opened an issue about this at #677 . It's using gulp instead of assemble directly (which is what example 3 here uses).
