### ISSUE TITLE
Collections with 2 tags or more {{#is tag "Test"}}

### ISSUE THREAD

**Issue by florianmascaro** [assemble/assemble#605]
Hi,

I’m looking for a way to use « collections » to display content with 2 tags or more (TAG1 or TAG2 - TAG1 and TAG2). In the documentation (http://assemble.io/docs/Collections.html) it’s explain how it’s working only with 1 tag. May be I don’t need to use  #is but something else ? I have tried for exemple to combine TAG + Category, but that’s not working at all :(

*Collection documentation for 1 tag :*

```html
\{{#each tags}}
  \{{#is tag "Test"}}
  <h1>\{{tag}}</h1>
  <ul>
    \{{#each pages}}
      <li>\{{data.title}}</li>
    \{{/each}}
  </ul>
  \{{/is}}
\{{/each}}
```

**Comment by jonschlinkert** [comment]
closing since this is more of an implementation challenge and is more appropriate for stackoverflow
