### ISSUE TITLE
v0.6.0: layouts applied to files that shouldn't have layouts

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble#607]
lol, note the CSS wrapped in a layout:

![image](https://cloud.githubusercontent.com/assets/383994/5427207/90983310-835c-11e4-9bea-ce9d5b850c05.png)

**Comment by Melindrea** [comment]
Has something been done with this? My styles task just stopped working properly. I have `{layout: null}` in the src call, but it still wraps the css with the default layout. (It was working yesterday)

**Comment by avr** [comment]
It looks like the options in `assemble.src` get overwritten in `lib/stack.js` in `exports.dest`.

If you add `{layout: null}` to `assemble.dest` it works (but I'm not sure that's the intended desire).

@jonschlinkert or @doowb - I think it has to do with the way options are merged.  If nothing is passed to `assemble.dest`, the `srcOpts` object are always merged with default options in `exports.dest` from `lib/stack.js`

**Comment by doowb** [comment]
@Melindrea I made [this change](https://github.com/assemble/assemble/commit/fe4cd2f07210012108624213d269c483f004ba7a) based on @avr description. I think that's where the issue is.

**Comment by jonschlinkert** [comment]
@doowb  is extend need there? https://github.com/assemble/assemble/compare/42a303f309e0...5a18eada2139#diff-6d186b954a58d5bb740f73d84fe39073R200. why not just `options = options || {}`

**Comment by doowb** [comment]
I just reverted it back to [this](https://github.com/assemble/assemble/commit/7353e2f1507b086c558b7358bd75cd0befe5ad4d#diff-6d186b954a58d5bb740f73d84fe39073L205) and I'm not sure why it was done that way before. I don't think `options` is mutated further down, so it should be safe to just do `options = options || {}`

**Comment by avr** [comment]
For what it's worth - this update works as expected on my end.

**Comment by Melindrea** [comment]
For me as well, thank you =)

**Comment by jonschlinkert** [comment]
Sounds like we can close this! thanks for the feedback
