### ISSUE TITLE
v0.6.0: Specifying different layouts

### ISSUE THREAD

**Issue by Melindrea** [assemble/assemble#608]
So, assume that I set my default layout to be `master` (`assemble.option({layout: 'master'});`), how would I (using `assemble.src`) set that a particular set of pages use a different layout?

I'd prefer not needing to detail it in the frontmatter of each page.

**Comment by acao** [comment]
sorry to hijack a closed ticket, maybe should open a new one -  but @waynedpj how are you bringing handelbars-layouts into play? I feel like I'm overlooking something obvious but I'd love to be able to do this.

**Comment by waynedpj** [comment]
@acao sorry for delayed response! i am in the middle of big project rewrite/refactor and have not yet started using handlebars-layouts w/ Assemble 0.6.x.  instead i am using handlebars-layouts with Handlebars directly, so unfortunately i have no Assemble specific example to share .. if that is what you are asking?

after a quick look it does not seem trivial as unfortunately [handlebars-layouts registers itself with the actual Handlebars instance directly](https://github.com/shannonmoeller/handlebars-layouts/blob/v1.0.0/index.js#L156), which right now in Assemble 0.6.x seems not be easily accessible. i have some ideas on how this would work, but as per the policy here at Assemble Land, to make sure i am understanding your question and to make things easier to find, would you mind opening up a new issue for this?  thanks.
