### ISSUE TITLE
v0.4.42: pages supplied via the pages array duplicated for each input file in assemble.task.files

### ISSUE THREAD

**Issue by andymantell** [assemble/assemble#611]
I've been experiencing a bug whereby my custom pages (specified via the pages option in my gruntfile) are being rendered out multiple times, once for each file supplied to assemble. I have been having a look and have tracked it down to the following area of assemble.js:

    /**
     * Pages
     * @param  {[type]}   assemble [description]
     * @param  {Function} next     [description]
     * @return {[type]}            [description]
     */
    var assemblePages = function(assemble, next) {
      grunt.verbose.writeln(('\n' + 'Building pages...').grey);
      var src = false;
      var assetsPath = assemble.options.originalAssets;

      async.waterfall([
        function(stepDone){
          async.forEach(assemble.task.files, function(filePair, done) {

*From https://github.com/assemble/assemble/blob/master/tasks/assemble.js#L188*

So, the above code starts looping through all the files on disk, then further down we have the following code *inside* this file loop:

    // Build options.pages
    function(buildDone){
      // if there is a pages property, build the pages contained therein.
      if(assemble.options.pages) {
        _.forOwn(assemble.options.pages, function(fileInfo, filename) {

          if(!filename || filename.length === 0) {
            grunt.warn('Pages need a filename.');
            buildDone();
            return false;
          }
          if(!buildPage(filename, fileInfo)) {
            buildDone();
            return false;
          }
        });
      }

*From https://github.com/assemble/assemble/blob/master/tasks/assemble.js#L336*

This nesting results in the assemble.options.pages being "multiplied" by every input file making the build extremely slow when there are many files.

**Comment by jonschlinkert** [comment]
closing since this is related to grunt-assemble. the discussion can be continued there if it's still an issue
