### ISSUE TITLE
Warning: Missing helper: 'is' on 0.4.42

### ISSUE THREAD

**Issue by matt-diehl** [assemble/assemble#613]
Since last week, when I do a new install of Assemble, I get the issue:

```
Warning: Missing helper: 'is' Use --force to continue.
```

However, if I copy the "node_modules/assemble" folder from another project that was installed several weeks/months earlier (but using the same version), it works without any issues.

**Comment by eloypineda** [comment]
I have a similar issue.

Just after creating a project with generator-assemble, I run `grunt server` and I get:

```
Running "assemble:pages" (assemble) task
Assembling dist/blog.html ERROR
Warning: Missing helper: 'relative' Use --force to continue.
```

node v0.10.35
npm v1.4.28
yo v1.3.3

**Comment by matt-diehl** [comment]
I installed with no problems. Try updating npm and yeoman and then reinstall.

```
npm update -g npm
npm update -g yo
```

**Comment by matt-diehl** [comment]
If you're on a Windows machine, looks like you may need to work a little harder to update npm:

https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

**Comment by eloypineda** [comment]
Thanks for your answer @matt-diehl.

I updated npm to v2.3.0 and yo to v1.4.5 and still the same issue.

Sorry I didn't metion before, but I am Mac OS X 10.10.1
node installed via nvm v0.23.2

**Comment by sethcarter** [comment]
On Dec 29, 2014 1:02 PM, "Matt" <notifications@github.com> wrote:
>
> I've narrowed it down to this being an issue on handlebars-helpers. At
least one odd thing I've encountered is that the package.json is missing
the "nap" dependency when assemble is installed via npm, but it is clearly
in the package.json on GitHub (for 0.5.8).
