### ISSUE TITLE
v0.6: Rendering markdown files with a Handlebars template

### ISSUE THREAD

**Issue by dennari** [assemble/assemble#614]
I'm trying to figure out the proper way to use Assemble v0.6 in the following scenario:
  1. I have a folder full of markdown files with yaml front matter
  2. I want to render them to html files through a handlebars template, so that I'm able to use the front matter in the template

This works, but I assume there's a nicer way (collections?):

```javascript
var assemble = require("assemble"); 
var md = require('helper-markdown');
var through2 = require("through2")
var Assemble = assemble.init();
var hbsEngine = Assemble.getEngine(".hbs");
var hbsTemplate = [
      "<p>{{slug}}</p>",
      "{{#markdown}}",
        "{{content}}",
      "{{/markdown}}"].join("\n");
  
Assemble.src(__dirname + "/posts/*.md")
      .pipe(through2.obj(function(file, enc, cb) {
        var stream = this;
       
       // file.data contains the yaml front matter as an object
        var locals = _.extend(file.data || {}, {
          content: file.contents.toString(),
          helpers: {markdown: md}
        })
        
        // render the template template with the given locals
        hbsEngine.render(hbsTemplate, locals, function(err, content) {
          file.contents = new Buffer(content);
          stream.push(file);
          cb();
        });
        
   
      }))
      .pipe(Assemble.dest(__dirname+"/posts/rendered"))   
```

**Comment by jonschlinkert** [comment]
try this:

```js
var assemble = require('assemble');
assemble.helper('markdown', require('helper-markdown'));

assemble.task('default', function() {
  assemble.src('posts/*.md')
    .pipe(assemble.dest('blog'));
});
```

**Comment by jonschlinkert** [comment]
By default Assemble parses front matter and passes the date to templates as context. The strategy we use for determining context is based on a lot of usage and feedback, but... it's also customizable via a context function if for some reason it doesn't work for you.

Also, the default engine (handlebars) will process either `.hbs` or `.md` files [by default]https://github.com/assemble/assemble/blob/v0.6.0/lib/assemble.js#L197) (`*` is shown as a default extension too, but that's only there temporarily for dev).

To define a another engine, say, [engine-lodash](https://github.com/jonschlinkert/engine-lodash) for processing lo-dash templates, you would do:

```js
assemble.engine('tmpl', require('engine-lodash'));
```
where `tmpl` is the file extension that should be associated with that engine. e.g. Assemble would use engine-lodash on `.tmpl` files, and the built-in engine for `.hbs` files. Or to override just define a new engine with `.hbs` or `.md`.

**Comment by dennari** [comment]
Thanks for the quick reply! How does the handlebars engine process markdown? Does it somehow use `helper-md`? 

Regarding your first response, how can I specify the template (`hbsTemplate` in my original post)?

**Comment by doowb** [comment]
@dennari 

Try this in the `assemblefile.js`

```js
var assemble = require("assemble");
var md = require('helper-markdown');

assemble.helper('markdown', md);
var hbsTemplate = [
      "<p>{{slug}}</p>",
      "{{#markdown}}",
        "{% body %}",
      "{{/markdown}}"].join("\n");

assemble.layout('default', hbsTemplate);
assemble.option('layout', 'default');

assemble.task('posts', function () {
  return assemble.src(__dirname + "/posts/*.md")
    .pipe(assemble.dest(__dirname+"/posts/rendered"))
});

assemble.task('default', ['posts']);
```

I think there's a bug in `helper-markdown` dealing with context (I'll submit a PR) but `slug` is working inside the `layout`.

**Comment by dennari** [comment]
@doowb 
Okay, the layout approach works well indeed! Can I restrict the layout to only apply to the pages specified by `assemble.src`?

**Comment by jonschlinkert** [comment]
yes, you should be able to do `assemble.dest('blog', {layout: 'default'})`

**Comment by jonschlinkert** [comment]
try that on `assemble.src()` if dest doesn't work. I can't remember at the moment if we changed it (it was discussed)

**Comment by jonschlinkert** [comment]
closing based on age
