### ISSUE TITLE
Streams 2

### ISSUE THREAD

**Issue by dennari** [assemble/assemble#615]
Since node streams are a big thing in Assemble v0.6.0, I'd like to raise discussion about the version of node streams that are going to be supported. Some background: http://r.va.gg/2014/06/why-i-dont-use-nodes-core-stream-module.html.

I see that Assemble v0.6.0 is currently relying on event-stream, that is decidedly Streams 1: https://github.com/dominictarr/event-stream/issues/21.

Maybe the through2 family of modules could be used instead of event-stream?

**Comment by doowb** [comment]
I'm opening to using something from `through2`. We are mostly using `event-stream` for the `.pipe` method which creates a single stream from an array of streams.

If you'd like to do a PR, I'll review it.

**Comment by dennari** [comment]
Submitted #618

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of assemble
