### ISSUE TITLE
Change default extension on a page by page basis?

### ISSUE THREAD

**Issue by cschweda** [assemble/assemble#616]
I'm starting to work with Assemble and love it.

One question: is it possible to declare a unique page extension in the page's YAML -- and then have Assemble assemble the page but change the page extension?

In other words, the page YAML might look like this:

```yaml
title: My ColdFusion page
extension: .cfm
```

And then have Assemble change the extension from the default .html to .cfm on that specific page?

I know I can use the 'ext' in options to define all pages as something other than HTML -- but I'm wondering if it's possible to do on a page-by-page basis.

Chris

**Comment by jonschlinkert** [comment]
sorry for taking so long on the reply. With Assemble v0.6.0 it would be easy and you have a couple of options, but earlier versions I'm not sure.

Here are your Assemble v0.6.0 options:

**plugin**

key points of this solution:

- front-matter is on the `file.data` object
- the plugin must be added to the pipeline of each task, so you can decide where you want to use it

```js
var through = require('through2');
var rewrite = require('rewrite-ext');

// extension plugin
module.exports = function extension(ext) {
  return through.obj(function(file, enc, cb) {
   // falls back to the `ext` defined in the task if not in front matter
    file.path = rewrite(file.path, file.data.extension || ext);
    this.push(file);
    return cb();
  });
};
```

Then in your assemblefile.js

```js
var assemble = require('assemble');
var extension = require('./extension');

assemble.task('default', function() {
  assemble.src('templates/*.hbs')
    .pipe(extension('.html'))
    .pipe(assemble.dest('./dist'));
});
```

**middleware**

_(note that this solution should work, but there is a bug currently preventing it, so don't use it until I update this with confirmation that it has been fixed)_

key points of this solution:

- as with plugins, front-matter is on the `file.data` object
- the middleware only needs to be defined once, allowing you to use it across all tasks/plugins.

```js
var assemble = require('assemble');
var rewrite = require('rewrite-ext');

// the regex pattern is used for filtering files
assemble.postRender(/\.html/, function (file, next) {
  file.path = rewrite(file.path, file.data.ext);
  next();
});

assemble.task('default', function() {
  assemble.src('templates/*.hbs')
    .pipe(assemble.dest('./dist'));
});
```

With rewrite-ext , there is no need to check if `extension` exists in either solution. if it doesn't, rewrite-ext will just use the default that's defined in the task, or if not defined in the task it will fall back to the [mapped extension for the file type](https://github.com/jonschlinkert/rewrite-ext#more-examples).

**Comment by jonschlinkert** [comment]
closing due to lack of response and it's not really an issue
