### ISSUE TITLE
What's happening with v0.6.0

### ISSUE THREAD

**Issue by dennari** [assemble/assemble#617]
Hi! I've been intensively following the progress of the next Assemble release and am really looking forward to understand it better. Could you share something about what's the current situation and also is there something I could help you with, without really understanding the codebase. 

I'm having problems understanding the relations between all the different packages that Assemble v0.6.0 consists of.

**Comment by dennari** [comment]
I can see from #559 that permalinks, collections and indexes are missing. Is there something that all these depend on that's not yet implemented?

P.s. Sorry if I seem irritating, I'd just really like to get started with the new version. Actually I have already started, but feel too unsure about everything to be productive.

**Comment by jonschlinkert** [comment]
> Sorry if I seem irritating, I'd just really like to get started with the new version.

not at all! we've been traveling and with the holidays, publicly things probably seemed to have slowed down, but we're still working hard on assemble.

> I'm having problems understanding the relations between all the different packages that Assemble v0.6.0 consists of.

Understandable. can you give me some specifics, and I'll try to answer? We'd love any help at all

**Comment by jonschlinkert** [comment]
> I can see from #559 that permalinks, collections and indexes are missing. Is there something that all these depend on that's not yet implemented?

forgot to answer this. not really, we just haven't gotten to them yet. the plugins exist, but we need to update them.

**Comment by jonschlinkert** [comment]
closing, but feel free to continue the conversation!
