### ISSUE TITLE
assemble.src overwrites templates with identical names

### ISSUE THREAD

**Issue by dennari** [assemble/assemble#619]
Given this:
```
pages_identical
├── en
│   └── index.hbs
├── fi
│   └── index.hbs
└── se
    └── index.hbs
```

`assemble.src("pages_identical/**/*.hbs")` only returns a stream with a single file while `gulp.src` returns a stream with all three. I'm pretty sure this is not intended. I wrote a test case which caches this and I can submit it as a PR.

**Comment by doowb** [comment]
This is intended by default. The default template loaders use the `renameKey` option which is a function that takes in the `filepath` and returns a `key`. This is the default:

```js
assemble.option('renameKey', function (fp) {
  return path.basename(fp, path.extname(fp));
});
```

However, you can override this to format it however you'd like. The key is just used as a key for storage so it doesn't affect the destination filepath. I tried with this simple one and it works for your case:

```js
assemble.option('renameKey', function (fp) {
  return path.join(path.dirname(fp), path.basename(fp, path.extname(fp)));
});
```

One bug I ran across when testing this out is that it only works right now when doing `assemble.src/assemble.dest` outside of a task. When inside a task there's a bug where the `renameKey` option isn't being passed probably, but I'm finishing up a fix for that so it will be pushed up later today.

**Comment by doowb** [comment]
I fixed and published the underlying libs and updated assemble. Try again with `renameKey` and see how it works for you.

**Comment by jonschlinkert** [comment]
> I'm pretty sure this is not intended.

I'll elaborate a little on what @doowb said in case it helps. we chose to do this because it allows assemble to cache files by name or filepath, and at build time this ensures that context will be passed to the correct file. 

However, also as @doowb mentioned, this is just the default. You should be able to change it to work however you need it. I wouldn't call your setup an edge case by any means... but every user needs to be able to rely on assemble's context handling. IMO we chose the lesser of two evils until a better solution emerges. We're definitely open to any ideas

**Comment by jonschlinkert** [comment]
hmm, this also seems like it might be a good use of middleware. I don't think we've done any testing around this though, so it might need to be tweaked to ensure that dest paths are passed correctly to `.dest()`

as I think about it, this might even be a good use case for a plugin. there are several ways to solve the problem depending on what needs to happen to those files.

**Comment by dennari** [comment]
Thanks for the explanations and the fix! Part of what made me think this cannot be intended, was that the results diverged from vinyl-fs .src and so far I hadn't noted other differences. But I can certainly relate to the reasons given and using `renameKey` would definitely work in my case.

I would assume that a common need for this, as is in my case, would be the need to compile different language versions. After I thought about it, I chose to have a separate assemble instance run for each language, since in my case there aren't really any interactions.

**Comment by jonschlinkert** [comment]
closing since this is resolved by renameKey
