### ISSUE TITLE
assemble.src with an array of globs and separate options

### ISSUE THREAD

**Issue by dennari** [assemble/assemble#620]
I'm running into a problem where I'd like to pass separate options to each glob in an array of globs. Or how else can I deal with the following situation:
```
.
├── layouts
│   ├── index.hbs
│   └── post.hbs
├── pages
│   └── index.hbs
└── posts
    └── post.md
```

```javascript
assemble.layouts('layouts/*.hbs');
assemble.src(['pages/*.hbs', 'posts/*.md'], {layout: '?'});
```

**Comment by jonschlinkert** [comment]
middleware is good for this use case I think. 

```js
assemble.use(/\.md$/, function(file, next) {
  // you might need to use `file.data.layout`
  file.layout = 'foo';
  next(null, file);
});
```

**Comment by jonschlinkert** [comment]
actually, just to be clear, you're saying you want to define _more than one layout_ per `.src()` definition. right? Another option is defining layouts in front matter, but that's not optimal if the project isn't small.

**Comment by dennari** [comment]
Yes exactly, more than layout per src definition.

So more generally, for option o having values v1 and v2, if I want file f1
to get value v1 and file f2 to have value v2, there's currently no way
achieve this in .src?

**Comment by doowb** [comment]
@dennari
> no way achieve this in .src?

Correct. @jonschlinkert's solution with middleware is what I would suggest. Middleware works like routed middleware in express. Instead of having verbs like `get/post/put`, we have verbs `onLoad`, `before`, `after`, and `all`.

`onLoad` runs just after a template/page is loaded.
`before` runs just before a template is rendered.
`after` runs just after a template is rendered.

I would suggest a middleware to run `onLoad` and then you can set the layout based on the extension or look at something else on the file object:

```js
assemble.onLoad(/\.md$/, function (file, next) {
  file.layout = 'post-layout';
  next();
});

assemble.onLoad(/\.hbs$/, function (file, next) {
  file.layout = 'page-layout';
  next();
});
```

**Comment by jonschlinkert** [comment]
@dennari, in a perfect world, how would this work in `.src()` if we were to implement something? I can't think of how that could work, but maybe you have some ideas?

**Comment by dennari** [comment]
Thanks for the answers. Middleware seems like a powerful idea and I could get my problem solved with them. 

That said, I feel like I *should* be able to solve this with `.src()`. Isn't having more than one layout a pretty common thing? And using front matter might be the answer in some cases, but most certainly not in all. Moreover, it seems nice to be able to specify the options per the file-groupings defined by the *globs*. This is lost if going the middleware route.

I suggest that `.src()` would accept an array of objects, similar in spirit to http://gruntjs.com/configuring-tasks#files-array-format. For example:
```javascript
[
  {src: ['a', 'b'], options: {layout: 'c'}},
  {src: 'd/*.e', options: {layout: 'f'}}
]
```

Then in the implementation, we could call `vinyl-fs.src()` for each entry in the array and combine the streams with [merge-stream](https://www.npmjs.com/package/merge-stream) (also https://github.com/gulpjs/gulp/blob/master/docs/recipes/using-multiple-sources-in-one-task.md).

**Comment by dennari** [comment]
This might also point to a solution: https://github.com/gulpjs/gulp/issues/840#issuecomment-70154989.

**Comment by jonschlinkert** [comment]
maybe, I'm not sure that's the best solution. I/we have other solutions that might be better for this. I'll try to get a little time to do something this weekend.

**Comment by doowb** [comment]
I put a code snippet together using `assemble-push` (not sure if) but it would involve more explaining. It would work similar to gulp-add-src mentioned in the other issue, but specific to assemble collections. I'll post it tomorrow and go over what it's doing. I also have a couple ideas based on the issue you posted.

**Comment by jonschlinkert** [comment]
@doowb just so we don't duplicate work (it doesn't sound like we are, but just in case), I started putting together some code to see if `assemble.src()` can do this by leveraging one of the config normalization libs I created. I might also put something together for `assemble.config()` just to weigh pros and cons of each approach.

**Comment by doowb** [comment]
My test has 2 template types with custom loaders but I thought it was too complicated.

I think that it's as simple as letting src be called twice and use the options specific to that src call.

**Comment by jonschlinkert** [comment]
that might be good. we could also take the array of src patterns, normalize them into some idiomatic format, then loop over each "config" and push the files into the stream according to the options for that config. 

the other thing we discussed in the past was using a different method for this, so we don't complicate src. e.g. `assemble.config()`. but I'm not of the mindset that more methods are more complicated. feedback is welcome

**Comment by jonschlinkert** [comment]
closing since this is more of a user-case specific challenge that can be resolved with the suggested solutions
