### ISSUE TITLE
Can't install moment.js as helper

### ISSUE THREAD

**Issue by cschweda** [assemble/assemble#622]
I'm just getting started with Assemble, and I can't seem to properly install and register moment.js.

In the project directory, I've done:
```js
npm i helper-moment --save-dev

```
The 'assemble' portion of my gruntfile looks like this:

```js
assemble: {
      options: {
        flatten: false,
        partials: '<%= build.src %>/_partials/*.hbs',
        layoutdir: '<%= build.src %>/_layouts',
        data: ['<%= build.src %>/_data/*.{json,yml}', 'package.json'],
        assets: '<%= build.out %>/',
        helpers: ['helper-moment','foo/*.js' ],

      },
      pages: {
        options: {
          layout: 'page.hbs'
        },
        expand: true,
        cwd: '<%= build.src %>/',
        src: ['**/*.hbs','!_*/**'],
        dest: '<%= build.out %>/'
      }
    },
```

I'm trying to test a date on my page with this:
```js

---
layout: default.hbs
title: <%= site.title %>
description: "Test."
example: <%= new  Date ("Sun Jun 30 2011 01:53:23 GMT+0300 (EEST)" ) %>
---
{{moment  example  format ="dddd, DD MMMM YYYY HH:mm:ss ZZ" }} 
```
But when I start the build, I get:
```js
Assembling out/index.html ERROR
Warning: Missing helper: 'moment' Use --force to continue.

Aborted due to warnings.
```

Obviously, I'm missing something. I have no idea what.

**Comment by cschweda** [comment]
Even an example of a working moment.js assemble setup would help.

Thanks.

**Comment by jonschlinkert** [comment]
is the helper in your dependencies? if not assemble can't load it.

**Comment by cschweda** [comment]
Yes -- it's my DevDependencies in my package.json file.

```js
  "name": "assemble-bootstrap",
  "version": "0.0.0",
  "dependencies": {},
  "devDependencies": {
    "assemble": "~0.4.4",
    "grunt": "~0.4.1",
    "grunt-autoprefixer": "~0.2.0",
    "grunt-bower-install": "~0.5.0",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-coffee": "~0.7.0",
    "grunt-contrib-concat": "~0.3.0",
    "grunt-contrib-connect": "~0.5.0",
    "grunt-contrib-copy": "~0.4.1",
    "grunt-contrib-cssmin": "~0.6.0",
    "grunt-contrib-htmlmin": "~0.1.3",
    "grunt-contrib-imagemin": "^0.9.2",
    "grunt-contrib-jshint": "~0.6.3",
    "grunt-contrib-uglify": "~0.2.0",
    "grunt-contrib-watch": "~0.5.2",
    "grunt-ftp-deploy": "^0.1.9",
    "grunt-gh-pages": "~0.8.0",
    "grunt-mocha": "~0.4.0",
    "grunt-modernizr": "~0.3.0",
    "grunt-rev": "~0.1.0",
    "grunt-rsync": "~0.2.1",
    "grunt-shell": "~0.5.0",
    "grunt-usemin": "~0.1.10",
    "helper-moment": "^0.1.0",
    "load-grunt-tasks": "~0.2.0",
    "time-grunt": "~0.1.1"
  },

```

Is this correct?

Does it need to be in dependencies? Instead of devDependecies?

**Comment by jonschlinkert** [comment]
wait, you're using this: https://github.com/helpers/helper-moment? It says on the readme that it's for Assemble v0.6.0 and up. Sorry

**Comment by cschweda** [comment]
Wait -- what?

I'm using what's on the documentation:

http://assemble.io/helpers/helpers-dates.html

What do I use? Totally confused. Please give me a pointer. Is there another one?

**Comment by jonschlinkert** [comment]
looks like the docs need to be updated. sorry about the confusion, but generally user-help is not what issues are for on github. we use places like stackoverflow for these kinds of questions so we can keep issues focused on bugs and feature requests.

**Comment by StevenBlack** [comment]
@cschweda welcome to Assemble.  Get used to it.

I see you're just getting started.  Best advice I can give you is, treat everything in allied repos as conceptual, and then be delighted when you find some that still work.  Assemble is a great framework but docs and many associated repos under the Assemble banner, not so much.

@jonschlinkert documentation issues are bugs, right?

**Comment by jonschlinkert** [comment]
Hey good to see you @StevenBlack! Wow, that's the sweetest thing you've ever said (no really!) thanks.

Actually we care very much about users - to the degree that we try very hard to stay focused on progress. But we get very few pull requests and very little help from the community so it's hard for @doowb and I to keep up with the amount of issues that come in. It would be awesome if folks like @StevenBlack helped out instead of giving us a hard time for not providing more free support. But hey, get used to it, right?

> best advice I can give you is, treat everything in allied repos as conceptual, and then be delighted when you find some that still work.

Don't be a dick. You in particular have a **much** higher ratios of problems than the average user. You don't want to do any research or look for answers yourself, which results in you assuming that it's our fault and not user error. That's probably very frustrating for you. But don't feel alone, you frustrate us too.

**Comment by StevenBlack** [comment]
Excuse me?

**Comment by jonschlinkert** [comment]
you complain a lot, always have. you don't pay anyone here, and you don't help out. you just jab and insult. don't comment any more if you don't want to help or say something nice. it's counter-productive and it certainly does't make us want to bend over backwards to address whatever issues your having.

**Comment by StevenBlack** [comment]
You are maybe having a bad day?  

I must have touched a nerve.

You accuse me of a lot of things there Mr Schlinkert.  

I'll tell you where I come from.  I come from a place long before you were born where the most important thing is, don't mislead people.

You'll eventually learn.

**Comment by cschweda** [comment]
I'm still confused (and a bit weirded out). 

Is there a version of moment.js that works for the master branch of Assemble? Or do I want to forget about moment.js? Are most of the docs incorrect?

I'm sensing tension -- that's okay -- but I'd just like to figure out if moment.js works as stated in the documentation -- or if the documentation is incorrect.

(I'm happy to update the docs -- but I can't do anything until I find out what's what. Not sure if this is a bug or a help request. Happy to post on stackoverflow -- just hoping to get a quick answer here.)

**Comment by jonschlinkert** [comment]
@cschweda sorry, really I am. I give direct, straightforward answers and I think that insults some people. But that's all it is. 

SO is a great place for user help, we answer questions there often. helper-moment is a helper and a different project, so it's better to post the issue there if there if it's a helper issue. but... it sounds like this is a docs issue, and I already created an issue on the docs repo and linked it above (before the other comments). 

Again, it's not that we don't want to help, it's that we try to keep info focused in each place, so in the future other users can find what they need.

**Comment by jonschlinkert** [comment]
> You accuse me of a lot of things there Mr Schlinkert.

I'm not accusing you of anything. I just read your comment. 

> Best advice I can give you is, treat everything in allied repos as conceptual, and then be delighted when you find some that still work.

I know it's easy to take written word out of context, but I'm pretty sure that's an insulting comment.

**Comment by doowb** [comment]
@cschweda The related issue is in the [helper-moment](https://github.com/helpers/helper-moment/issues/1#issuecomment-67385838) repo.

@StevenBlack I have to agree with @jonschlinkert's last statement. I took your "advice" as bashing on us for not treating assemble like it's some type of enterprise project.

**Comment by cschweda** [comment]
No worries -- thanks for the explanation, @jonschlinkert -- I appreciate it,

@doowb -- Thanks for the pointer to the helper-moment repo. That's exactly what I needed.

**Comment by StevenBlack** [comment]
@jonschlinkert and @dwoob I was once an Assemble newb.  I tried, on many occasions, to inform you of about Assemble-allied repos that just don't work despite being listed under the Assemble banner.

It's called repo rot.  Repo rot is possibly the biggest hurdle to new people learning Assemble.  There's evidently no way to discuss repo rot here without you guys taking offence.  I get it: it's your baby.  Exposing repo rot is good news if you look at it correctly.

I can tell you: I still use Assemble every day and I'm doing fantastic things with it, well in excess of what's easily imaginable.  We just work on different quality planes.

When you guys start taking obsolete repos down and attaching deprecation notices, rather that flipping birds as perfectly exemplified here, please let me know.

**Comment by jonschlinkert** [comment]
> Repo rot is possibly the biggest hurdle to new people learning Assemble

No. It's not. Again, it's you. You don't look at branches, you don't look at related projects and dependencies to see that we're "fixing the root" of the issues - not just the superficial stuff. 

> We just work on different quality planes.

Of this I have no doubt.

> When you guys start taking obsolete repos down and attaching deprecation notices rather that flipping birds as perfectly exemplified here, please let me know.

https://github.com/orgs/ghost-town/dashboard do research before you make comments.

Your number one biggest problem is that you use something incorrectly, and assume it's something we're doing wrong. That's it.

**Comment by StevenBlack** [comment]
@jonschlinkert how the hell would you know??

You know what Assemble newbs do?  I'll tell you what Assemble newbs do.  They clone repos and try them.  I did a metric crapton of Assemble repo cloning and initializing when I first started.  

You are completely (completely) delusional about the quality of many of the repos Assemble links to directly.

Which is why I recommend to @cschweda to initially treat all of Assemble's allied repos as conceptual.  Things go way better when you doff a skunkworks hat when trying many of these.   A year ago I reckon the probability that a directly linked Assemble repo worked as advertised was about 0.6 -- that's generous.  I suspect this probability is much lower now. 

Now please stop acting like a risible wanker.  You just don't like hearing that having x-hundred public repos to your name isn't necessarily a good thing.  Some repos are bum-steers and you just need to face that fact someday.

**Comment by jonschlinkert** [comment]
@StevenBlack please don't comment on any project that I maintain. I'll just delete your comments going forward.

**Comment by StevenBlack** [comment]
@jonschlinkert Please leave it.  You've said some personally objectionable things and I will require this in the future.

**Comment by StevenBlack** [comment]
Oops, too late.  Heh.

**Comment by cschweda** [comment]
The link to the correct version of moment was deleted.

Can you repost that? I didn't get a chance to copy it.

Thank you.

**Comment by doowb** [comment]
@cschweda https://github.com/helpers/helper-moment/issues/1
