### ISSUE TITLE
v0.6.0: how to refresh the cache when running under watch?

### ISSUE THREAD

**Issue by akileez** [assemble/assemble#623]
I have some json files defined via `assemble.data` and if I make a change to a value in one of the files while running under assemble.watch, the changes are not reflected in the generated output. 

Here is an abridged version of my assemblefile.js
```js
assemble.option('assets', 'assets');
assemble.option('modulesDir', 'modules/');
assemble.option('scriptsDir', 'assets/scripts/');
assemble.option('layoutDelims', ['{{=', '}}']);
assemble.layouts(['layouts/global/*.hbs', 'layouts/regions/body/*.hbs']);
assemble.partials('layouts/regions/{foot,head}/*.hbs');
assemble.data(['assemble/data/*.json', 'assemble/defaults/*.json']);

assemble.task('site2', function(cb){
  return assemble.src(paths.site2)
    .pipe(extname())
    .pipe(assemble.dest(paths.build));
    cb(err);

assemble.task('watch', function() {
    assemble.watch(['templates/**/*.hbs', 'modules/**/*.hbs', 'helpers/*.js', 'assemble/{defaults,data}/*.json'], ['site', 'site2', 'pretty']);
    assemble.watch(['assemble/config/*.cson'], ['cfgsite']);
  });
});
```

is there a way to refresh the cache while running under watch?

**Comment by doowb** [comment]
You can move the `assemble.data()` call inside the `site2` task then the data will be loaded again.

If you need to load it in more than one task, I would create another task dedicated to loading the data that the other ones depend on....


```js
assemble.option('assets', 'assets');
assemble.option('modulesDir', 'modules/');
assemble.option('scriptsDir', 'assets/scripts/');
assemble.option('layoutDelims', ['{{=', '}}']);

assemble.task('preload', function (cb) {
  assemble.layouts(['layouts/global/*.hbs', 'layouts/regions/body/*.hbs']);
  assemble.partials('layouts/regions/{foot,head}/*.hbs');
  assemble.data(['assemble/data/*.json', 'assemble/defaults/*.json']);
  cb();
});

assemble.task('site1', ['preload'], function(cb){
  return assemble.src(paths.site1)
    .pipe(extname())
    .pipe(assemble.dest(paths.build))
    .on('error', cb)
    .on('end', cb);
});

assemble.task('site2', ['preload'], function(cb){
  return assemble.src(paths.site2)
    .pipe(extname())
    .pipe(assemble.dest(paths.build))
    .on('error', cb)
    .on('end', cb);
});
assemble.task('watch', function() {
    assemble.watch(['templates/**/*.hbs', 'modules/**/*.hbs', 'helpers/*.js', 'assemble/{defaults,data}/*.json'], ['preload', 'site1', 'site2', 'pretty']);
    assemble.watch(['assemble/config/*.cson'], ['cfgsite']);
  });
});
```

**Comment by akileez** [comment]
thanks @doowb. unfortunately the solution you presented does not solve the problem. 

Maybe this was a design decision in which case no problem. If this is what you consider a bug then its there. 

Running the above setup with console.log for debugging,  `this.options`, `this.context`, `this.locals` and `assemble.cache` reflects the initial startup state. After changing the json file while under `watch`, the cache remains static. No change.

I have previously tried moving `assemble.data` into the task. I also tried using `assemble.get` but I believe that is used for `assemble.options`. Both methods tried as a statement above `return` and as an option in `assemble.src`. I also tried using `loader-cache` to no avail. Maybe middleware might work but I am unfamilar with the syntax at this point.

**Comment by jonschlinkert** [comment]
this wasn't really a design choice, more of a limitation of some of the tools we're using that we're trying to work around. 

@doowb seems like this would benefit from events. and/or a method to update (or trigger updating) the context - or maybe init will work here.

**Comment by doowb** [comment]
I figured out what's happening. In [plasma](https://github.com/jonschlinkert/plasma/blob/master/index.js#L208) `.json` files are read in with `require` which caches files if the filename matches. If you change your `.json` files to `.yaml` files (you shouldn't have to change the syntax), then it works.

@jonschlinkert looks like we might need to update plasma to read files and do `JSON.parse()` instead of using `require`

**Comment by doowb** [comment]
This is my test project: https://github.com/doowb/assemble-test-data-watching

**Comment by akileez** [comment]
changing file to `.yaml` did the trick. Thanks!!

**Comment by jonschlinkert** [comment]
> looks like we might need to update plasma to read files and do JSON.parse() instead of using require

good catch @doowb. not something I would have thought of beforehand.  `require` is something 20x faster thought, so what do you think about setting a flag or passing an event to plasma when watch is used?  so the first load uses require but then it uses JSON.parse afterwards?

**Comment by jonschlinkert** [comment]
fixed in plasma

**Comment by Sebastian-Fitzner** [comment]
Hi,

first of all - great work you are doing there. Yesterday I made my first steps into assemble v0.6 and gulp and have a problem with the caching of json files (like @akileez said). The ticket is declared as fixed, but my json files are cached. 

Here are my files, any hints are very welcome: 

**assemble.js**: 

``` js
var config = require('./config');
var gulp = require('gulp');
var assemble = require('assemble');
var extname = require('gulp-extname');
var gulpAssemble = require('gulp-assemble');

gulp.task('preloadData', function () {
	assemble.data([config.paths.src + '/data/**/*.{json,yaml}']);
});

gulp.task('preloadPartials', function () {
	assemble.layouts(config.paths.src + '/templates/layouts/*.hbs');
	assemble.partials([config.paths.src + '/templates/partials/**/*.hbs']);
});

assemble.option({
	layout: 'tpl-default',
	assets: './'
});

gulp.task('assemble', function () {
	gulp.src(config.paths.src + '/templates/pages/**/*.hbs')
		.pipe(gulpAssemble(assemble))
		.pipe(extname())
		.pipe(gulp.dest(config.paths.dev + '/'))
		.pipe(config.notify('Build HTML files'));
});
```

**watch task**

``` js
gulp.watch(config.paths.src + "/templates/pages/**/*.hbs", ['assemble']);
gulp.watch([
	config.paths.src + "/templates/layouts/**/*.hbs",
	config.paths.src + "/templates/partials/**/*.hbs"],
	['preloadPartials', 'assemble']
);
gulp.watch(config.paths.src + "/data/*.{json,yaml}", ['preloadData', 'assemble']);
```

**Comment by doowb** [comment]
@Sebastian-Fitzner I recommend using `assemble` directly since everything you're doing is supported by assemble. Then take a look at the example above with how dependencies are used in the tasks. You probably need to set it up so the `assemble` task depends on the `preloadData` task finishing. The way you have it now, they both could start at the same time and the `assemble` task is probably running with stale data since it hasn't finished loading in the `preloadData` task yet.

**Comment by akileez** [comment]
@doowb beat me to it

**Comment by doowb** [comment]
Lol... however I just looked through the dependencies and the latest might not be using the latest `plasma` yet. I'll try to get that updated today.

**Comment by Sebastian-Fitzner** [comment]
I should mention, that I already had the structure from above and that was not working with JSON, but the missing plasma update could be the problem ... With YAML everything is working fine.

**Comment by jonschlinkert** [comment]
If you look in the dependencies for plasma, and find the function that's loading data, if it's using `require()` to load JSON then it hasn't been updated yet. That was all @doowb's idea btw. He broke everything - It just looks like I did it in the commit history lol
