### ISSUE TITLE
Custom Variable in Partial with Unique Context

### ISSUE THREAD

**Issue by adriaanbalt** [assemble/assemble#624]
Here are the files:

*json-file-name.json*
```
{
"image-name":"hello.jpg"
}
```

*default.hbs*
```
{{> body }}
```

*index.hbs* (a page)
```
{{> partial json-file-name }}
```

*partial.hbs*
```
<img src="{{ filepath }}{{ image-name }}" />
```

*Grunt.js*
```
assemble: {
	dist: {
				options: {

					filepath: 'http://domain.com/sub-directory/',

					assets: '<%= directory.dist %>',
					partials: ['<%= directory.app %>/views/partials/**/*.hbs'],
					layout: ['<%= directory.app %>/views/layouts/default.hbs'],
					data: ['app/data/**/*.json'],
					pages: ['<%= directory.app %>/views/pages/**/*.hbs']
				},
				files: [{
					expand: true,
					src: ['**/*.hbs'],
					cwd: '<%= directory.app %>/views/pages/',
					dest: '<%= directory.dist %>'
				}]
			}
		}
}
```

But "filepath" which is set in the options of Assemble appears blank in the "partial.hbs".  Is this because I am in the context of "json-file-name.json" and therefore unable to access the option "filepath" in the partial.hbs?

**Comment by doowb** [comment]
You need to use `../` to get to the parent context... [Handlebars paths](http://handlebarsjs.com/#paths)

```handlebars
<img src="{{ ../filepath }}{{ image-name }}" />
```

**Comment by adriaanbalt** [comment]
I did that, but it doesn't work.

**Comment by jonschlinkert** [comment]
there are other things that could cause this, because of how handlebars manages context. if the partial is wrapped with a block helper somewhere, this would also change the context. could there be a block helper defined in a page, partial, layout etc. where the partial is being injected?

**Comment by adriaanbalt** [comment]
I'm not using any block helpers.  I'm finding that the *index.hbs* can reference ```{{ filepath }}``` but the partial cannot.  Even when I used ```{{ ../filepath }}```.  I think this is because when include the partial I pass it a reference to a JSON file and somehow the partial cannot find the parent context.  Maybe I should pose this to the Handlebars team instead since Assemble has been working great regardless of this context issue.

**Comment by Sebastian-Fitzner** [comment]
Because you are using `{{>}}` partial you cannot get the parent context in your partial file. 

You need to pass in a second context beside your json context. That can only work if you use https://www.npmjs.com/package/handlebars-helper-partial. Hope that helps ...

**Comment by jonschlinkert** [comment]
good catch @Sebastian-Fitzner, sounds like it might be the issue

**Comment by adriaanbalt** [comment]
This is perfect @Sebastian-Fitzner thank you.
