### ISSUE TITLE
Helping you make progress on v0.6

### ISSUE THREAD

**Issue by regiskuckaertz** [assemble/assemble#625]
Assemble is central to our workflow, it's only natural to help you back with anything that can make v0.6 a reality.

**Comment by jonschlinkert** [comment]
:+1: awesome. let me know what you need from us. maybe a screen share?

**Comment by regiskuckaertz** [comment]
sure! I can have a chat with you after work (i.e. from 6pm GMT+1 on). I suppose I'll first get acquainted with how v0.6 works compared to v0.4 (installing and reading the code I guess) and then either get working on the pending issues, debug untested areas, or even help you with the programming. Does that seem to make sense?

**Comment by jonschlinkert** [comment]
Wow, @regiskuckaertz I never got a notification after this! I wish I could make these notifications more prominent! I wish I had. Not sure if you're still interested, but we'd love to have more help of course!

**Comment by regiskuckaertz** [comment]
Hi @jonschlinkert! No worry, with my girlfriend we decided to take a week off just after I wrote this, so I wouldn't have been available anyway :)
Sure I'm interested, I can certainly manage to put a few hours every week on this. According to you, what's the best way to understand how 0.6 works compared to 0.4?

**Comment by jonschlinkert** [comment]
closing since we've since released 0.7.0. we're always looking for help though!
