### ISSUE TITLE
v0.6.0 sub-layouts not rendering (nesting)

### ISSUE THREAD

**Issue by akileez** [assemble/assemble#626]
If I create a template which calls a layout(sub1), and that layout calls another layout (default), sub1 layout does not get rendered. It seems to only act as a pass-through to the final layout.

[test repo here](https://github.com/akileez/Assemble6.1)

**Comment by akileez** [comment]
after further investigation, the problem only occurs when you change your delimiters, in my case `{{= }}`.
When I used the default, `{% %}` it works.

**Comment by doowb** [comment]
@akileez - @jonschlinkert and I were just working on this the other day, and should have a fix soon. That test repo should help us out too, thanks.

**Comment by akileez** [comment]
no problem. its not critical. I have many other areas to explore with assemble 0.6.0 in the meantime. it's pretty freaking fantastic!!!

**Comment by jonschlinkert** [comment]
thanks!

**Comment by jonschlinkert** [comment]
closing here, I opened a new issue on doowb/layouts

**Comment by doowb** [comment]
@akileez I just pulled down your repo and used the latest modulus and it works as expected now. Thanks for the example repo.

**Comment by akileez** [comment]
thank you for all your efforts.
