### ISSUE TITLE
Latest verison of gray-matter

### ISSUE THREAD

**Issue by davidsinclair** [assemble/assemble#627]
Hi,

I recently raised this issue with gray-matter:

https://github.com/jonschlinkert/gray-matter/issues/9

(values containing '---' confusing gray-matter).  This has been fixed (incredibly quickly - thanks!).  Assemble uses an older version of gray-matter (^0.4.2).  Would it be possible to move to the new version containing this fix? 

Thanks in advance,

David

**Comment by jonschlinkert** [comment]
Assemble v0.6.0 uses the latest gray-matter. we won't be making any major changes like this to pre 0.6. 

also, that version of gray-matter uses regex, and shouldn't have this particular issue. However, if you find that it does and can show a test case for it, I'll get Assemble updated.
