### ISSUE TITLE
update repository property in package.json to use https instead of git protocol

### ISSUE THREAD

**Issue by jfroffice** [assemble/assemble#628]
this causes an error if git protocol is not allowed
```
npm ERR! git clone git://github.com/assemble/assemble fatal: unable to connect to github.com:
```

**Comment by doowb** [comment]
Which repository are you installing?

I noticed that you commented on transformicons and they have it specified using the `git` protocol in [their package.json](https://github.com/grayghostvisuals/transformicons/blob/master/package.json#L31).

**Comment by jfroffice** [comment]
@doowb you are right.

I am going to check this. 
As it is a specific branch v0.6.0 it does not seem to fix this, event I change package.json on with
```
https://github.com/assemble/assemble#v0.6.0.
```

If you have any workaround that would be helpful.

**Comment by jonschlinkert** [comment]
is this still an issue?

**Comment by jfroffice** [comment]
As far as we are using branch v0.6 we should be using git://.

I do not know if there is a workaround before you release v0.6.

@grayghostvisuals any idea ?

**Comment by grayghostvisuals** [comment]
I thought this line was being used because it's not a full release as of yet? https://github.com/assemble/assemble#v0.6.0

**Comment by doowb** [comment]
I submitted a PR to transformicons. This isn't an assemble issue, it's just that you probably have a firewall that's blocking npm from installing using the `git://` protocol. This is common, so my PR just removes the protocol piece entirely. If this doesn't work, you may need to look at your network settings and search for help with accessing github from a corporate network (at least that's what I needed to do when I first started with github).
