### ISSUE TITLE
What's the lowdown on 0.6.0?

### ISSUE THREAD

**Issue by nicholaswyoung** [assemble/assemble#629]
I'm getting ready to start a new website, with a deadline of next week. I would love to use Assemble 0.6.0 for this, but I haven't heard much news. If one wants to start building a 0.6.0-based site, are their docs on getting started?

**Comment by jonschlinkert** [comment]
We're using it a lot, there are docs on all of the supporting libs for assemble 0.6.0, which is what the API is composed of. The only thing preventing release is documentation, and we just haven't had time to do it yet.

**Comment by nicholaswyoung** [comment]
@jonschlinkert Cool. Where do you propose I begin my learning journey? Once I've had time to kick the tires, I would love to start contributing documentation, so let me know how I should go about that as well.

**Comment by jonschlinkert** [comment]
awesome. I think [Template](https://github.com/jonschlinkert/template) is a great place to start. Assemble can do anything in that documentation. just replace `template.foo()` with `assemble.foo()`. 

If you want to read/write files with assemble and run tasks, assemble uses the same signature as gulp:

```js
assemble.task('default', function() {
  assemble.src('templates/*.hbs')
    .pipe(assemble.dest('dist'));
});
```
hope that helps

**Comment by nicholaswyoung** [comment]
@jonschlinkert Cool. Is 0.6.0 ready to power a blog? Because that's one of my main use cases. I need to list posts written in markdown and render them into a handlebars or swig template.

Also: is the gulp plugin ready to go? Because I'll be using Gulp for rendering Stylus, etc.

**Comment by jonschlinkert** [comment]
> Is 0.6.0 ready to power a blog?

hmm, I would expect pagination to be a part of any blog, and we haven't yet created the plugin to do that.  I've been wanting to do this but haven't had time. but it's something anyone could do if they wanted.

> is the gulp plugin ready to go?

The gulp plugin will be nice if you're just using assemble for "light work", like building some markdown docs. But if you need access to all the methods on the API, since Assemble can run any grunt plugin, IMHO, it makes more sense to use assemble directly.

**Comment by nicholaswyoung** [comment]
So what would the best workflow be for using Gulp to handle CSS preprocessing and Assemble for generating the templates?

I'm trying to build one command in either Gulp or Assemble that will build templates and handle CSS generation. Maybe that's not possible at this point.

**Comment by jonschlinkert** [comment]
### Templates

Generate HTML from templates:

```js
var assemble = require('assemble');

// assemble processes handlebars templates by default
assemble.task('default', function () {
  assemble.src('templates/*.hbs')
    .pipe(assemble.dest('dist'));
});
```

### Pre-process CSS

**Using a plugin**

Use plugins to pre-process CSS (Assemble can run any gulp plugin):

```js
var assemble = require('assemble');
var less = require('gulp-less');

assemble.task('css', function () {
  assemble.src('styles/*.less')
    .pipe(less());
    .pipe(assemble.dest('dist/assets/css'));
});

assemble('default', ['css']);
```

**Or, using an engine**

Instead of a plugin you can register an engine, such as [engine-less](https://github.com/jonschlinkert/engine-less). 

_(Engines are run automatically on any files that have a file extension matching the name that you used when registering the engine.)_

```js
var assemble = require('assemble');
assemble.engine('less', require('engine-less'));

assemble.task('css', function () {
  assemble.src('styles/*.less')
    .pipe(assemble.dest('dist/assets/css'));
});

assemble('default', ['css']);
```

**Comment by nicholaswyoung** [comment]
@jonschlinkert Oh, very cool. Pagination isn't a concern at the moment, and it's something I can easily build out when it becomes one.

Here's another oddball question: can Assemble run existing Gulp plugins? If it does (and has a ```#watch``` method, again, like Gulp), then I don't even have a need to include Gulp in the workflow.

**Comment by nicholaswyoung** [comment]
@jonschlinkert Given that I don't need pagination at the moment, is there at least a way to order markdown posts in 0.6.0?

**Comment by jonschlinkert** [comment]
> my main dilemma is understanding how to build out a template, then take markdown posts with front matter, and render the templates with that markdown content/front matter as variable data

For that, all you need to do is:

```js
var assemble = require('assemble');

assemble.task('default', function () {
  assemble.src('templates/*.md')
    .pipe(assemble.dest('dist'));
});
```

> is there at least a way to order markdown posts in 0.6.0?

This is something that would be done with a plugin. I've really wanted to create one I just haven't had time lately. I'll talk to @doowb  and see if we can come up with something fast. No promises though

**Comment by nicholaswyoung** [comment]
Hmmm, that's interesting. So it isn't possible to take variable data from front matter on a markdown file, and pass it to something like a Handlebars or Nunjucks template?

**Comment by doowb** [comment]
@nicholaswyoung do you have a project folder structure showing how you're expecting to use templates verses markdown content? We just don't have things built-in to automatically achieve your goal, but we have new features and a new way of working with middleware and helpers that will.

**Comment by jonschlinkert** [comment]
> We just don't have things built-in to automatically achieve your goal

To clarify, front-matter works by default.

> So it isn't possible to take variable data from front matter on a markdown file

Same as pre v0.6.0 assemble, you'll need to use helpers for markdown. That should work the same as before. Try [this helper](https://github.com/helpers/helper-md#assemble) and see if that works.

**Comment by jonschlinkert** [comment]
or this one if you need to wrap inline markdown: https://github.com/helpers/helper-markdown#assemble

**Comment by nicholaswyoung** [comment]
@jonschlinkert @doowb I don't have an example offhand, but let me make a repo and I'll post it here later on.
