### ISSUE TITLE
Update Handlebars 3.0.0 in Assemble 0.4.x 

### ISSUE THREAD

**Issue by spacedawwwg** [assemble/assemble#631]

**Comment by DenisMir** [comment]
That would be great!

**Comment by jonschlinkert** [comment]
@doowb you okay with updating handlebars for 0.4.x before we start moving v0.6.0 to master?

**Comment by dvera123** [comment]
Awesome!

**Comment by gunnx** [comment]
+1

**Comment by alizbazar** [comment]
+1

**Comment by Abhra1992** [comment]
+1

**Comment by jonschlinkert** [comment]
I thought we did this... hmm. sorry folks, I acknowledge that assemble 0.4.x doesn't get as much love as it should since we've been focused on trying to get 0.6 released. if anyone wants to help maintain grunt-assemble let us know

**Comment by doowb** [comment]
Yeah, [handlebars 3.0.1](https://github.com/assemble/assemble-handlebars/blob/master/package.json#L42) is used in [grunt-assemble](https://github.com/assemble/grunt-assemble). If you're using `assemble` with `grunt`, then you should switch to `grunt-assemble`.

**Comment by jonschlinkert** [comment]
let's go ahead and close this here so we can continue any related discussions on grunt-assemble
