### ISSUE TITLE
Assemble v6 Custom Schema Option for parser-front-matter

### ISSUE THREAD

**Issue by dtothefp** [assemble/assemble#632]
I put this issue in Template as well. We are implementing YAML tags into into our YAML files in relation to tagging and transforming for translation. In order to do this we need to be able to pass an option down the dependency tree of `parser-front-matter` to attach a SCHEMA to the `js-yaml` [parser]( https://github.com/nodeca/js-yaml/blob/master/examples/custom_types.js#L79). Wondering if you guys could offer support in `pasrser-front-matter`/template/assemble for this or if you could recommend an implementation?

**Comment by jonschlinkert** [comment]
No problem, I'll make the necessary changes so the schema can be passed down.

**Comment by jonschlinkert** [comment]
actually, to be sure, did you already try passing the schema on the options? e.g. 

```js
assemble.option('schema', foo)`
```

**Comment by dtothefp** [comment]
@jonschlinkert I didn't try that yet, but in template where I saw the `parser` used it didn't seem to take any options. I can try but I'm starting to think this is a little more complicated because first we must access the `Type` constructor of of `js-yaml`. For example: 

```js
  var Type = yaml.Type;
  var marked = require('optimizely-marked');

  var TrType = new Type('tag:yaml.org,2002:tr', {
    kind: 'scalar',
    construct: function (data) {
      var translation = null !== data ? data : '';
      translation.isTR = true;
      //connect i18n parser here
      console.log('TR running *********');
      return translation;
    }
  });

  var MdType = new Type('tag:yaml.org,2002:md', {
    kind: 'scalar',
    construct: function (data) {
      marked.setOptions({
        linkPath: assemble.get('data.linkPath'),
        smartypants: true
      });
      var content = marked(null !== data ? data : '');
      content.isTR = true;
      console.log('md running******');
      return content;
    }
  });

  var SPACE_SCHEMA = yaml.Schema.create([ TrType, MdType ]);
``

So I'm worried I would just have to pass assemble these definitions somehow, or gain access to the parser instance

**Comment by jonschlinkert** [comment]
k, either way it should be easy to solve. It probably makes the most sense to just register your own parser in middleware (can't remember if we have an option to turn off the default parser, but if we don't we'll add one).

For example, this is how you would register `parser-front-matter`:

```js
var parser = require('parser-front-matter');

assemble.onLoad(/\.md$/, function (file, next) {
  parser.parse(file, function (err) {
    if (err) return next(err);
    next();
  });
});
```

`parser-front-matter` users gray-matter (https://github.com/jonschlinkert/parser-front-matter/blob/master/index.js#L8). Give me a few minutes, I'll add an example for how to register one with gray-matter.

**Comment by dtothefp** [comment]
Cool yeh we tracked the dependency chain for parser-front-matter > gray-matter and were happy to find `js-yaml` there :bowtie: . We will be using the parser in multiple places so a nice option might be something similar to the rename key getter/setter but don't know if that would be more work:

```js
assemble.options('parser', customParser);
```

**Comment by jonschlinkert** [comment]
Really, Assemble doesn't have parsers per se, we're just registering one as a middleware to serve as a default for most users. but users should be able to turn it off with `assemble.disable('parser')`.

For your user case, I think registering your own middleware is a better solution. e.g.

```js
var YAML = require('js-yaml');
var marked = require('optimizely-marked');
var extend = require('extend-shallow');
var matter = require('gray-matter');
var Type = YAML.Type;

var TrType = new Type('tag:yaml.org,2002:tr', {
  kind: 'scalar',
  construct: function (data) {
    var translation = null !== data ? data : '';
    //connect i18n parser here
    return translation;
  }
});

var MdType = new Type('tag:yaml.org,2002:md', {
  kind: 'scalar',
  construct: function (data) {
    marked.setOptions({
      linkPath: assemble.get('data.linkPath'),
      smartypants: true
    });
    var content = marked(null !== data ? data : '');
    return content;
  }
});

var OPTIMIZELY_SCHEMA = YAML.Schema.create([TrType, MdType]);

function yaml(str, opts) {
  try {
    opts = extend({schema: OPTIMIZELY_SCHEMA}, opts);
    return YAML.safeLoad(str, opts);
  } catch (err) {
    throw new SyntaxError(err);
  }
}

assemble.onLoad(/\.md$/, function (file, next) {
  extend(file, matter(file.content || ''), {
    parser: yaml
  });
  next();
});
```

**Comment by jonschlinkert** [comment]
actually, with a small tweak you could easily make this a requirable module.

```js

module.exports = function parser(file, next) {
  extend(file, matter(file.content || ''), {parser: yaml});
  next();
};

assemble.onLoad(/\.md$/, require('optimizely-parser'));
```

**Comment by dtothefp** [comment]
I think this all looks good but the regex with the file extension may not be necessary for our use case. We are mostly concerned with tagging yaml front matter and because assemble is parsing that by default we want a way to register our yaml tags before parsing and then to intercept that tagged data for translation. We already have middleware setup for intercepting separate yaml files, parsing for translation and scoping locally for their associated hbs templates. There may be a better way and I'm most likely not fully understanding your solution. We are having a meeting tomorrow at 2pm EST with our localization dev, Kyle and Brian. Would be great if you wanted to hop on the call as well and contribute to what you think might be the best solution. I'm on my phone so can't send an invite now but Brian has all the details if you're interested.

**Comment by jonschlinkert** [comment]
> We are having a meeting tomorrow at 2pm EST

sounds good

**Comment by dtothefp** [comment]
Cool...send you details and in the morning. I'm in SF this week so on PST

**Comment by jonschlinkert** [comment]
:+1:

**Comment by jonschlinkert** [comment]
@dtothefp can this be closed?

**Comment by dtothefp** [comment]
@jonschlinkert sorry for the delay. I think we are not going to end up using YAML tags but they are a pretty awesome feature that some users might want to use in the future. Up to you if you want to close the issue though because it is no longer pressing for us

**Comment by jonschlinkert** [comment]
no worries, thanks, I'll go ahead and close
