### ISSUE TITLE
v0.6.0 Collections

### ISSUE THREAD

**Issue by Melindrea** [assemble/assemble#634]
In the version of my site where I started implementing Assemble, I added `inMenu: true` to files in the menu, and used the collection that created (of menu items) to build up a menu.

How would I do something similar with 0.6? I'd really prefer not needing to hand-code the menu (it's a fairly simple one, only a single level)

**Comment by jonschlinkert** [comment]
I'll mark this as (somewhat) related to https://github.com/assemble/assemble/issues/629, since both rely on collections of some kind. 

(just wanted to tag this, but I want to discuss with @doowb before answering. we've discussed some options...)

**Comment by stefanwalther** [comment]
@Melindrea, did you get collections to work in 0.6.0? It would be really great to see a short working example ... thx.

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of assemble
