### ISSUE TITLE
v0.6.0 Compile partial in Handlebars Helper

### ISSUE THREAD

**Issue by Melindrea** [assemble/assemble#635]
In a particular helper (featured image, to be exact), I'd like to return a compiled Handlebars partial. 

Prior version had
        template = Handlebars.compile(fs.readFileSync('src/bonnet/partials/image.hbs', 'utf8'));
        return new Handlebars.SafeString(template(data));
but Handlebars can't be found in this version of my helper. I can get the partial itself from `this.options.partials.image`, but how would I go about compiling it with a data object and return some kind of safe string?

**Comment by jonschlinkert** [comment]
> I can get the partial itself from this.options.partials.image

how are you registering your partials? let's start with that

**Comment by Melindrea** [comment]
Entire Assemble.js file:

```
'use strict';

// Connected to globbing patterns
function extend(a, b) {
    for (var key in b) {
        if (b.hasOwnProperty(key)) {
            a[key] = b[key];
        }
    }
    return a;
}

var assemble = require('assemble'),
extname = require('gulp-extname'),
config = require('./config.js'),
buildDir = config.pkg.config.dist,
system = config.site.assemble.system,
content = config.site.assemble.content,

// [fix] - Replace once the globbing pattern works
// helpers = system.helpers + '/{,*/}helper-**.js',
path = require('path'),
glob = require('glob'),
helperFiles = glob.sync(system.root + '/' + system.helpers + '/{,*/}helper-**.js'),
helpers = helperFiles.reduce(function (acc, fp) {
    return extend(acc, require(path.resolve(fp)));
}, {});

// Load system
assemble.layouts(system.root + '/' + system.layouts + '/**.hbs');
assemble.helpers(helpers);
assemble.partials(system.root + '/' + system.partials + '/**.hbs');

assemble.option(config.site.assemble.options);
assemble.option('site', config.site.site);
assemble.option('env', config.env);
assemble.option('media', config.media);

assemble.task('pages', function() {
    assemble.src(content.root + '/pages/**.md')
        .pipe(extname())
        .pipe(assemble.dest(buildDir));
});

assemble.task('assets', function() {
    assemble.src('assets/**', {layout: null})
        .pipe(assemble.dest(buildDir));
});

assemble.task('default', ['pages', 'assets']);
```

The helper (based on code we've discussed before)
```
'use strict';

module.exports.featuredImage = function (imageId) {
    var fs = require('fs'),
        template, data, images = this.options.media.images,
        dir = '/' + this.options.media.directories.image + '/large/',
        imageSource;

    if (imageId && imageId in images) {
        imageSource = dir + images[imageId].source;

        data = {
            source: imageSource,
            size: images[imageId].sizes.large,
            alt: images[imageId].alt,
            classes: 'img-polaroid featured-image'
        };

        // Below are the old-style way I used to load and compile the template
        // template = Handlebars.compile(fs.readFileSync('src/bonnet/partials/image.hbs', 'utf8'));
        // return new Handlebars.SafeString(template(data));
    }
};
```

**Comment by jonschlinkert** [comment]
okay, that helps a lot, thanks. First thing in the helper, add these:

```js
assemble.helper('featuredImage', function (imageId) {
  console.log(this.app)
  console.log(this.options)
  console.log(this.context)
  // other stuff ...
});
```
(make sure the helper is called, I'm forgetful about this lol)

- `this.app` is `assemble`, and on that object you will find a `views` object with all cached partials, pages or any other templates.  
- Templates are cached as objects
- To get a cached partial, just do `this.app.views.partials[foo]`, or to get a page do  `this.app.views.pages[foo]`. All template types also get decorated with their own `get` method. So can alternatively do `this.app.getPage(foo)` etc.
- A `.render()` method is actually bound to every template, so to render it you just need get the To render any template, you can use the template's render method, e.g. `this.app.views.pages[foo].render()` (which takes a callback), or you can use assemble's render method, (`this.app.render()`)

These tests have lots of examples: https://github.com/jonschlinkert/template/blob/master/test/template.render.js. Everything on the Template API works the same in assemble. 

I can probably post some example tomorrow if you still need help. let me know if this made sense

**Comment by Melindrea** [comment]
Yep, that works perfectly. 

```
template = this.app.getPartial('image');
return template.render(data);
```

The one thing I can't find in the docs is some way for it to be a 'safe string', since currently it will give me the HTML and then in the compile replace the tags.

**Comment by jonschlinkert** [comment]
I know how to do this if the following works, but try getting the engine from assemble by doing:

```js
var Handlebars = assemble.getEngine('hbs');
new Handlebars.SafeString('foo');
```
This should ensure that you're using the same instance at runtime.

**Comment by doowb** [comment]
@jonschlinkert I don't think that'll work because the engine that's returned is actually an instance of the wrapped engine from `engine-cache`.

I was thinking about this issue this morning and forgot to answer...

@Melindrea since you're writing the helper to be used specifically for Handlebars, it's okay to just require in handlebars (make sure to add it to your project's package.json) and use the SafeString method directly:

```js
var Handlebars = require('handlebars');
return new Handlebars.SafeString(template.render(data));
```

Handlebars recently updated how SafeString works and there's no requirement to make sure it's the same instance of handlebars.

**Comment by jonschlinkert** [comment]
> engine that's returned is actually an instance of the wrapped engine from engine-cache.

I was writing something to say almost exactly that. In my first sentence I meant "if the following doesn't work", for that reason. 

> Handlebars recently updated how SafeString works and there's no requirement to make sure it's the same instance of handlebars.

That's great, I didn't know that

**Comment by Melindrea** [comment]
Oddly enough, it's not working. I followed @doowb's suggestions, but it's still escaped. I used console.log, and it logged this:

```
{ string: '<img width="297" height="416" src="/media/images/large/jonI.jpg" class="img-polaroid featured-image" alt="Old-Fashioned image of Jon and I">\n' }
```

**Comment by Melindrea** [comment]
Interesting. When I wrote the HTML out as it should be, it worked perfectly. Going to need to dig into why it's not liking the rendered template. (different project, similar use case =)

**Comment by jonschlinkert** [comment]
Hmm, Handlebars made changes to how safestring works, there might be some info in their docs that could help. I haven't had a chance to refresh on it yet.

**Comment by akileez** [comment]
@Melindrea make sure you are using @doowb suggestion inside your helper file, that is `var Handlebars = require('handlebars');` at the top of the helper file then call safeString when returning your data. I had this same issue when I started reworking my helpers for v0.6.0. No problems since I did the above.

**Comment by Melindrea** [comment]
@jonschlinkert Yeah, I'll check it up. It works for my current use case (supplying a string to it), and that's got priority over rendering a partial. Might've been a bug that's gotten fixed, or something. I'll close this, since the specific query--how to render a partial within a helper--has been solved.

**Comment by Melindrea** [comment]
And now I've confirmed that some update fixed my issue. Here's a working example:

```
'use strict';
module.exports.characterProfile = function (key) {
    var Handlebars = require('handlebars'),
        characters = this.options.character,
        character = characters.characters[key],
        template = this.app.getPartial('character-profile');

    return new Handlebars.SafeString(template.render(character));
};
```

**Comment by jonschlinkert** [comment]
:+1: great!

**Comment by jonschlinkert** [comment]
@Melindrea I've been meaning to ask... you were a little apprehensive about switching to the v0.6.0 branch at first, I know we have some kinks to work about, but in general what are your thoughts about the API/usability?

@akileez would love to hear your thoughts too.

**Comment by Melindrea** [comment]
@jonschlinkert The main apprehensiveness I still have is the lack of docs, but I've generally solved that by experimenting, and once I've depleted my guesses ask on here. 

I really *really* like the new version. The helpers are cleaner and easier to create, and the speed is zoom-zoom-zoom.

**Comment by jonschlinkert** [comment]
great, thanks for the feedback! docs are getting chipped away at, I think it's starting to accelerate since I came up with a formula that's really working out. hmm maybe I should post that to see if I can get some help writing the docs...? :)

**Comment by Melindrea** [comment]
Where I can, I'll happily help.

**Comment by jonschlinkert** [comment]
:+1:

**Comment by akileez** [comment]
@jonschlinkert Sorry for the delay. I had about 60 browser tabs open and forgot about this... Anyways, no apprehension on my part. Just too much anticipation. what prevented me from getting started sooner was the lack of working comprehensive examples. when @doowb [layout test](https://github.com/doowb/assemble-layout-tests) appeared I decided then I would never use 0.4 branch again and just learn what I could to covert my grunt process over to assemble completely. I looked at everything I possibly could to flesh out the info needed. When stuck, I found workarounds. When those didn't work, I'd post a question as @Melindrea has done. Its funny because most of the questions she posted I had experienced is some shape or fashion. But that bulldog tendency of mine would just keep pushing forward.

Enough rambling ... the new version is awesome in every way. Yes, there are quirks but I am sure that over time they will get worked out. My present [assemblefile.js](https://github.com/akileez/assemblefile) is posted for any critique. Its still very rough around the edges and I haven't worked on it in a couple of weeks, but enjoy.

**Comment by jonschlinkert** [comment]
great feedback, thank you! 

speaking of examples, I pushed up a [collections example](https://github.com/assemble/assemble-tags-collection-example) yesterday. It would have taken me less time to actually publish a lib that does this, but I'd rather try to show how to do it so the community can start creating plugins for this stuff.

**Comment by akileez** [comment]
@jonschlinkert I glanced at it yesterday. excellent example by the way. gives great insight into plugins. I wanted to work with it this weekend when I had some time and try to reproduce the output in my own backwards kind of way. But those kinds of examples I learn the most from. Also, THANK YOU for giving the results. When I can connect inputs to outputs, understanding increases by orders of magnitude, at least for me.

**Comment by jonschlinkert** [comment]
> When I can connect inputs to outputs, understanding increases by orders of magnitude, at least for me.

I'm exactly the same way, glad to know it might help!

**Comment by jonschlinkert** [comment]
@akileez what part of the US are you in? near midwest by any chance?

**Comment by akileez** [comment]
East coast. Trenton, New Jersey

**Comment by jonschlinkert** [comment]
That's not too far. I think a beer is in order if there's ever an event nearby for both of us :)

**Comment by jonschlinkert** [comment]
and of course, @Melindrea is welcome as well, or any of our other github friends. I'll just make sure to buy the first round before everyone gets there
