### ISSUE TITLE
Assemble grunt task breaks when using readFileSync() in helper.

### ISSUE THREAD

**Issue by JDillon522** [assemble/assemble#637]
I asked this question on [SO](http://stackoverflow.com/questions/28632199/handlebars-assemble-io-handing-return-data-from-helper) but I think I'll get a faster response here.

I have a handlebars helper I want to parse fixture data and then iterate through that data with your standard handlebars `{{#each}}` helper. 

Heres my helper:

	Handlebars.registerHelper('parseFixture', function(path, options) {
		if (!path || typeof path !== 'string') { return false; }

		var fs = require('fs');
		var nodePath = require('path');

		path = nodePath.join(__dirname, '../fixtures/' + path);

		fs.readFile(path, function(err, data) {
			if (err) {
				console.error('ERROR: ', err);
				return err;
			}

			data = data.toString('utf8')
			data = JSON.parse(data);

			return data;
		})
	});

And In my template:

	<nav>

		<ul>
			{{#parseFixture 'header.json'}}
				{{nav}}
				{{#each nav-bar.nav-links}}
					<li><a href="javascript:">{{this.topLevel}}</a></li>
				{{/each}}
			{{/parseFixture}}
		</ul>

	</nav>

And the fixture data I'm using:

	{
		"nav": [
			{
				"topLevel": "Things to Do"
			}, {
				"topLevel": "Places to Stay"
			}, {
				"topLevel": "Where to Eat"
			},{
				"topLevel": "Events"
			}, {
				"topLevel": "Deals"
			}, {
				"topLevel": "Plan Your Trip"
			}
		]
	}

So, I'm retrieving the fixture data properly, and it parses fine. If I log it out right above the return statement everything is grand. But even trying to output `{{nav}}` in the template does nothing.

I think the problem is that I'm using `readFile()` and not `readFileSync()`. I changed it however and I get:

>Warning: Bad arguments

It doesnt give me anything more descriptive, but I can follow added `console.log()`s right up to the `readFileSync()`.

**Does `readFileSync()` screw up grunt server or assemble?**

**Comment by JDillon522** [comment]
Nevermind. This [SO answer solved it for me](http://stackoverflow.com/questions/23825753/node-js-fs-readfilesync-bad-arguments)

For posterity sake, heres what I did with my helper:

```
	Handlebars.registerHelper('parseFixture', function(path, options) {
		if (!path || typeof path !== 'string') { return false; }

		var fs = require('fs');
		var nodePath = require('path');
		var fixture;

		path = nodePath.join(__dirname, '../fixtures/' + path);

		try {
			var json = fs.readFileSync(path)

			json = json.toString('utf8')
			json = JSON.parse(json);
			fixture = json;

		} catch (err) {
			return console.error(err);
		}
		return fixture;
	});
```

Theres some unnecessary variables I'll clean up but whatever

**Comment by doowb** [comment]
I did that so many times when I first started working with async functions in node. Glad you figured it out.
