### ISSUE TITLE
Passing data from helper to partial instead of outputting result

### ISSUE THREAD

**Issue by JDillon522** [assemble/assemble#638]
I have a custom helper that reads and parses a JSON file. I need that data to be available to another partial, but instead the helper is just outputing the data as an `[object Object]` string directly into the DOM.

How can I pass that data to the context of the next partial?

Heres my helper:

```
	Handlebars.registerHelper('parseFixture', function(path, options) {
		if (!path || typeof path !== 'string') { return false; }

		var fs = require('fs');
		var nodePath = require('path');
		var fixture;

		path = nodePath.join(__dirname, '../fixtures/' + path);

		try {
			fixture = fs.readFileSync(path)
			fixture = fixture.toString('utf8')
			fixture = JSON.parse(fixture);
		} catch (err) {
			return console.error(err);
		}

		return fixture;
	});
```

**Comment by doowb** [comment]
How are you using the helper and partials?
There are a few ways you can do this with handlebars.

**Comment by JDillon522** [comment]
I've tried a number of different ways:

```handlebars
// in a module
{{#parseFixture 'file.json'}}
	{{> partial}}
{{/parseFixture}}

// And in the partial itself
{{#parseFixture 'file.json'}}
	{{#each data}}
         //
    {{/each}}
{{/parseFixture}}
```

Both uses just end up outputing the result of the fixture into the DOM as `[object Object]`

**Comment by doowb** [comment]
Since you're using the block helper format, update your helper to the following:

```js
    Handlebars.registerHelper('parseFixture', function(path, options) {
        if (!path || typeof path !== 'string') { return false; }

        var fs = require('fs');
        var nodePath = require('path');
        var fixture;

        path = nodePath.join(__dirname, '../fixtures/' + path);

        try {
            fixture = fs.readFileSync(path)
            fixture = fixture.toString('utf8')
            fixture = JSON.parse(fixture);
        } catch (err) {
            return console.error(err);
        }

        return options.fn(fixture);
    });
```


`options.fn` is basically a compiled template using the html inside the helper block. So by doing `options.fn(fixture)` you're rendering the internal template with the `fixture` data as your context.

**Comment by JDillon522** [comment]
Fantastic! That did it. I was not aware of how `options` could be used. I originally included it as a "maybe I'll need to change some options later" parameter.
