### ISSUE TITLE
Assemble('default' ... -> object is not a function

### ISSUE THREAD

**Issue by stefanwalther** [assemble/assemble#640]
Hi,
I am trying to get started with v0.6.0 and if I use

`assemble( 'default', ['html', 'css'] );`

as described, I just get "object is not a function" ...

Any ideas?

Regards
Stefan

**Comment by doowb** [comment]
`assemble` is not a function, it's an instance of `Assemble`. It looks like you're trying to add a `task`:

```js
assemble.task('default', ['html', 'css']);
```

**Comment by stefanwalther** [comment]
Thx, this was a quick one ;-) Yes, got it ...
