### ISSUE TITLE
#markdown handlebar tag stopped working after `npm update`

### ISSUE THREAD

**Issue by aleksey-bykov** [assemble/assemble#641]

**Comment by jonschlinkert** [comment]
what version of assemble are you using?

**Comment by aleksey-bykov** [comment]
i create a new project from scratch, by doing `npm init` and then install grunt and assemble, so the version is the latest and greatest available from npm `"version": "0.4.42"`

**Comment by jonschlinkert** [comment]
we're working off the v0.6.0 branch, so nothing I know of has changed on our end. not everyone follows semver though so it might be a dep. more info would help

**Comment by quoo** [comment]
How exactly is it not working? I am seeing some intermittent issues with it rendering escaped html rather than actually rendering the tags and we're trying to narrow down the issue.

**Comment by jonschlinkert** [comment]
could be marked.js, but it looks like it hasn't been updated in a while

**Comment by aleksey-bykov** [comment]
It recognizes the 'markdown' tags but doesn't produce anything quietly. So
whatever is in between those tags turns into an empty string. It can be
seen if you init a new node package install grunt and assemble and run npm
update.

**Comment by jonschlinkert** [comment]
What are you using the `init`?

**Comment by jonschlinkert** [comment]
closing since this refers to an old version of assemble or grunt-assemble and is no longer relevant
