### ISSUE TITLE
v0.6.0 Document correct layout assignment

### ISSUE THREAD

**Issue by agross** [assemble/assemble#643]
The documented options to assign layouts does not work:

> Layouts can be defined in template locals:
```js
// either of these work (one object or two)
assemble.page('toc.hbs', { content: 'Table of Contents...'}, { layout: 'default' });
assemble.partial('foo.hbs', { content: 'partial stuff', layout: 'block' });
```

**Comment by doowb** [comment]
[These tests verify](https://github.com/jonschlinkert/template/blob/master/test/layout.js) that those syntaxes should work when using the default loader (like with `pages` and `partials`).

Is this happening with the default types or when using one of your custom loaders from the other issue? The default loader handles normalizing those arguments to ensure the properties are in the correct place.

**Comment by agross** [comment]
You are right! Related to #642, I tried using gulp-rename to define the destination file name. This broke layout rendering. Obviously gulp-rename is not the way to go. Looking forward to get #642 answered :-)
