### ISSUE TITLE
v0.6.0 Fail if assigned layout cannot be found

### ISSUE THREAD

**Issue by agross** [assemble/assemble#644]
Assemble will succeed given either setup:

* no layouts in `assemble` and a template with an assigned layout, or
* a mistyped layout for a `page`

I understand that layout is just conventional metadata, but it makes debugging/verifying your build harder than necessary.

```js
assemble.layouts('layouts/*.hbs');
assemble.page('will-render-just.content.hbs', { content: 'no layout', data: { layout: 'does-not-exist' }});
```

**Comment by jonschlinkert** [comment]
@doowb and I talked about this very issue recently. It's not a design choice, it's bug.

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of assemble and has been resolved
