### ISSUE TITLE
v0.6.0 Item ID defaults, renameKey function

### ISSUE THREAD

**Issue by agross** [assemble/assemble#645]
Copied from https://github.com/assemble/assemble/issues/639#issuecomment-75457808:
> As my product JSONs may contain duplicate file names in several subdirectories, I need to define a custom renameKey function. (Related: #619) I'd argue this is a very strange design decision. As least it doesn't make your users fall into the Pit Of Success™. Even a simple
```js
assemble.page('one.hbs', { content: 'one' });
assemble.page('blah/one.hbs', { content: 'blah/one' });
```
> will result in just one page rendered.

>> Well, we need to match up data with templates correctly.

What do you mean by "match up data"? Are you talking about files without front matter metadata, e.g. external metadata?

>> So if you, as a user, want to have multiple templates with the same name, and you expect assemble to magically know which template you meant when you put data on the context, we have a few options:

>> * don't allow it. since object keys must be unique in javascript, and we cannot match up data correctly when two templates have the same name. This, of course, would mean that you can't do what you're doing.
>> * use full file paths for all object keys and camelize the key so that in templates you would use variables like templates_pages_marketing_splash.title. I'm not a big fan of this option.
>> * don't decide for the user and give them a renameKey option so they can have multiple templates with the same name.

Just to make sure we're on the same page. My input data looks like this:
```
source/data/2765/DE/83.json
source/data/5000/DE/83.json
```

As it stands from my perspective I need the `data/2765/DE` and `data/5000/DE` parts to be part of my ID, otherwise I would just get `source/data/5000/DE/83.json` rendered to the output directory.

>> We decided to go with 3, since our experience has been that only users who have advanced needs will even need to know that such an option exists.

I didn't bother to think this was an advanced scenario. Before assemble I was using a Ruby generator called nanoc which also has the concept of "item IDs" which by default map to path names without extension, e.g. `source/data/2765/DE/83`. I think this would be a sane default as I found the culprit only after 3 hours of debugging.

>> Although, I'm still a little confused on where you are with this, e.g. were you saying that you are now able to accomplish what you need with renameKey, or it's not working for you?

There are two spots where I need the modified ID:

* The loader returns `acc[removeExtension(path.normalize(file))] = template;` (object key == `source/data/2765/DE/83`)
* And I defined 
```js
// Map e.g. dist/2765/DE/83/index.html back to the product template's ID.
assemble.option('renameKey', function(fp) {
  var res = path.join(path.dirname(fp), removeExtension(path.basename(fp)));
  return path.relative(process.cwd(), res);
});
```

Here are some questions for you:
* How would a single `renameKey` option work with mixed content? Using default loaders, custom loaders and a few `assemble.page()` statements? IMHO the `renameKey` would need to handle all of them, unless you split them into separate `assemble.tasks`. Would that be the preferred option?
* Related to #642, right now I just tried `.pipe(rename({}))` to compute the desired output file name. If I change the rename logic I would also need to change `renameKey` to get the correct template ID back. With my limited knowledge about assemble (please bear with me) this seems unfortunate as I need to define the mapping in two places.

Again, please bear with me if my questions appear stupid. Right now I just find it very hard to grok your mental models of how a static site should be built. I like to learn and get other people's concepts. It's just the limited documentation and missing samples that's making it a bit harder for me to stumble into that pit of success I was talking about. Thank you very much for your ongoing support!

**Comment by jonschlinkert** [comment]
> Again, please bear with me if my questions appear stupid

not at all! I hope I never implied that. 

I'm still reading through your response, I'll get some answers up here to clarify in a few

**Comment by agross** [comment]
> I hope I never implied that.

You never did :)

**Comment by jonschlinkert** [comment]
did any of the suggestions about renaming files on the other issue help with this?

**Comment by agross** [comment]
Yes, your feedback definitely helped a lot! I now have a simple solution to the problem:

* Template IDs generated from JSON look like this: 'generated/product/2765/DE/1234.json'
* `template.data.path` is the same value

Hence, `renameKey` is very simple, e.g. no mapping done:

```js
// Map `template.path`s back to the product template ID.
// These are the same, no mapping necessary.
assemble.option('renameKey', function(file) {
  return file;
});
```

**Comment by jonschlinkert** [comment]
great!
