### ISSUE TITLE
related to #642

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble#646]
See https://github.com/assemble/assemble/issues/642#overview.

For some reason the middleware solution I described isn't working - maybe the path is being overwritten afterwards. I haven't had time to debug yet, I just wanted to get this posted as a reminder.

**Comment by agross** [comment]
Alright, thank you for looking into it. I was playing with middleware myself yesterday and I also found that despite my attempts to modify `file.data.dest` my changes were not picked up to determine the output path.

**Comment by jonschlinkert** [comment]
do you remember the methods you tried? e.g. `.onLoad()`, `.preRender()` etc. or was it every stage?

**Comment by agross** [comment]
IIRC, I tried `assemble.use(pattern, fn)` and `assemble.router.all(pattern, fn)`.

**Comment by doowb** [comment]
I know what the issue is... The `path` property "loses" it's reference between the vinyl object and the template object on the cache.

I have an easy fix but this might come up with other properties.

**Comment by agross** [comment]
:+1:

**Comment by jonschlinkert** [comment]
@doowb was this fixed with the changes in template?

**Comment by doowb** [comment]
Yes, it's been fixed.
