### ISSUE TITLE
v0.6.0 assemble pollutes my data object

### ISSUE THREAD

**Issue by agross** [assemble/assemble#647]
In my first handlebars template I want to output all key/value pairs for my custom `data` object. The loader saves the object as `template.data.product` and it looks roughly like this:

```js
{
  "path": "source\\data\\1958\\DE\\8309.json",
  "data": {
    "product": {
      "id": 8309,
      "groupId": 384,
      "imageId": 181,
      "number": "RO-1"
    },
    "layout": "product",
    "src": {
      // ...
    },
    "dest": {
      // ...
    }
  }
}
```

Handlebars:
```hbs
<html>
  <h1>{{product.desc1}}</h1>
  <table>
    <thead>
      <td>Key</td>
      <td>Value</td>
    </thead>
    {{#each product}}
      <tr>
        <td>{{@key}}</td>
        <td>{{this}}</td>
      </tr>
    {{/each}}
  </table>
</html>

```

Now when it's time to render the layout template with this object, `data.product` suddenly contains extra properties `data.product.defaultLayout`, `data.product.src`, `data.product.dest`, and `data.product.layoutDelims`:

```js
{
  "path": "source\\data\\1958\\DE\\8309.json",
  "data": {
    "product": {
      "id": 8309,
      "groupId": 384,
      "imageId": 181,
      "number": "RO-1",
      "defaultLayout": false,
      "src": {
        "dirname": "source\\layouts",
        "basename": "product.hbs",
        // ...
        "path": "source/layouts/product.hbs",
        "ext": ".hbs"
      },
      "dest": {
        "dirname": "source\\layouts",
        // ...
      },
      "layoutDelims": [
        "{%",
        "%}"
      ]
    },
    "layout": "product",
    "src": {
      // ...
    },
    "dest": {
      // ...
    }
  }
}
```

I  checked with the debugger, these extra properties were added somewhere later in the pipeline than [`template.render(locals, function(err, content)`](https://github.com/assemble/template-render/blob/master/index.js#L75) and before [`Template.prototype.compileTemplate`](https://github.com/jonschlinkert/template/blob/master/index.js#L1695).

**Comment by jonschlinkert** [comment]
this is a good point. I had initially thought of the `data` object as being a reserved object, since then we've made major changes and haven't revisited the concept of adding the `src` and `dest` properties to that object. we'll get that changed before release.

but `src` and `dest` are on the `product` object too? are you using a custom loader and/or using a custom function to extend the context?

**Comment by jonschlinkert** [comment]
can you paste some of your setup here so we can see how you're loading data, etc.? I just don't see how we would be deep extending and object that we didn't know existed.

**Comment by agross** [comment]
From what I understand from the source and docs, `data` the object that is used to pass data to the template. Should I use `locals` instead?

**Comment by agross** [comment]
Yes, I'm using a custom loader (still talking about JSONs :). It's become pretty complex thanks to the convoluted mess that is my source. The most relevant part to you is this (it's a streaming loader):

```js
          var id = path.normalize(path.join(paths.source.data, group.id.toString(), 'DE', product.id.toString()));
          gutil.log('Extracting', log.format(id));

          var data = {
            product: product
          };

          // For layout property.
          if (opts) {
            data = _.extend(data, opts);
          }

          var template = {
            path: destPath,
            data: data,
            content: 'dummy content to have the template pass validation',
          };

          var acc = {};
          acc[id] = template;
          that.emit('data', acc);
```

Here's what's emitted:
```js
{ 'source\data\2765\DE\67338':
   { path: 'source\data\1958\DE\16541.json',
     data: { product: [Object], layout: 'product', destPath: [Function] },
     content: 'dummy content to have the template pass validation' } }
```

And after emitting it looks like this:
```js
{ 'source\data\1958\DE\16541':
   { path: 'source\data\1958\DE\16541.json',
     data:
      { product: [Object],
        layout: 'product',
        destPath: [Function],
        src: [Object],
        dest: [Object] },
     content: 'dummy content to have the template pass validation',
     locals: {},
     options:
      { subtype: 'products',
        isRenderable: true,
        load: 'stream',
        method: 'onLoad',
        next: [Function: next],
        basePath: '',
        originalPath: 'source\data\1958\DE\16541.json',
        params: {},
        route: [Object],
        engine: '.json' },
     layout: undefined,
     render: [Function],
     ext: '.json' } }
```

**Comment by jonschlinkert** [comment]
what's on `opts`?

**Comment by jonschlinkert** [comment]
try doing 

```js
if (opts) {
  data = _.extend({}, data, opts);
}
```
to clone the objects instead

**Comment by agross** [comment]
`opts` is just the `{ layout: 'product' }` definition and a (temporary) `destPath` function hack to have the file destination calculated.

**Comment by agross** [comment]
Just did what you suggested, no change in the HTML. Given that I pass the data correctly to assemble and it's enriched much later in the process, I'll ask again :) - Should I use `locals` instead?

**Comment by jonschlinkert** [comment]
> I'll ask again :) - Should I use locals instead?

Yes, probably. 

> Given that I pass the data correctly to assemble 

Passing data is the easy part, you're also extending it :)

I'm going to look deeper into this. I have some ideas about what could cause it if it is something we're doing, my hunch might be an easy fix. 

In the meantime, is `product` a custom template type? Also, you might want to try doing a custom `mergeContext` function to change how the context is merged. 

```js
assemble.option('mergeContext', function(template, locals) {
  // 
});
```
- `template` is the individual template at render-time. `data`, `options`, `locals` and whatever else has been defined on the template itself
- `locals` is the object passed to the render method - which also happens by proxy via the render plugin, helpers, or anything else that might call `.render()`

I'll check back in a bit after I look into it

**Comment by doowb** [comment]
do you have any partials or other templates named named `product`? Since we merge the data together based on key that would add the other partials `src` and `dest` info to the data. This is also done in `mergeContext`.

**Comment by jonschlinkert** [comment]
exactly, that's actually what I meant when I asked "custom template type", I must have been thinking about two things that the same time lol.

**Comment by agross** [comment]
Yes, I have a layout called `product.hbs`.

**Comment by agross** [comment]
So I guess `locals` is the way to go? Are there any downsides to using `locals`?

**Comment by jonschlinkert** [comment]
Also, to clarify something, when you look at the `data` object at runtime, you're not just seeing the template's `data` object, you're looking at the `context`, which is built up in the `mergeContext` function using data from:
-  `assemble.cache.data` (think of this as "global" or project-wide data), 
- `template.data`, data defined on the template itself. Unless it's extended directly or you're using virtual templates, this is usually front-matter.
- `template.options`: which are used to pass options to template engines and similar libs.
- `template.locals`: this is an object defined on an template method.

**Comment by agross** [comment]
Just to confirm: `data` is the only thing visible to the Handlebars engine?

**Comment by jonschlinkert** [comment]
no. `data` isn't passed to Handlebars, `context` (your example) is passed to handlebars. Context is created from `data` and the other objects I listed above. an example might help, give me a sec

**Comment by agross** [comment]
OK, I think I get it. It looks like a custom `mergeContext` just passing `data` or `locals` is the way to go then.

**Comment by jonschlinkert** [comment]
Okay, thanks for working through this with us. In the meantime, in case this helps (you or anyone else stopping by), here is an overview of a couple of different data objects on assemble:

All data loaded with `assemble.data()` is stored on `assemble.cache.data`:

```js
// stored on `assemble.cache.data`
assemble.data({
  site: {title: 'My site'}
});
```

When templates are loaded, they are stored on `assemble.views` plus the name of the collection, e.g. a `page` would be stored on `assemble.views.pages`. If a template has a data object, here is what it might look like:

```js
// stored on `assemble.views.partials.button.data`
assemble.partial('button.hbs', '{{title}}', {data: {title: 'Click me'}});

// stored on `assemble.views.pages.home.data`
assemble.page('home.hbs', '{{title}}', {data: {title: 'Home page'}});

// stored on `assemble.views.layouts.default.data`
assemble.layout('default.hbs', '{{title}}\n{% body %}', {data: {title: 'Blog section'}});
```

`context` is created at render time by merging these together with other objects like `locals`, and then that `context` object is passed to the engine. That context object is what you showed in your first example. e.g. it's not surprising that it has additional properties on it besides what was defined on the template. If that's not what you need, the `mergeContext` method is the way around it.

**Comment by agross** [comment]
I think I have a better understanding of assemble now:

* Data items from different sources (locals, data, layouts) will be merged into a `context` passed to the template engine
* The mapping is done by name only
* Names (see `renameKey` discussion #645) are derived from file name with the directory portion stripped
* Given I had `data.products` with data important to me and a layout named `product` (from `source/layouts/product.hbs`) that itself might have front-matter or otherwise-defined properties, both where merged into the `context` and then passed to handlebars.

I settled with naming my important data item `data.item` now. No moar pollution!

Many thanks for the explanation!
