### ISSUE TITLE
is 'content' a reserved variable?

### ISSUE THREAD

**Issue by goodpixels** [assemble/assemble#649]
so this doesn't work:

```
---
title: Home
content: 'Some text.'
---
{{content}}
```

but this works:

```
---
title: Home
my_content: 'Some text.'
---
{{my_content}}
```

is this intended? and why does this happen?

**Comment by jonschlinkert** [comment]
can you give a little more info? 
- what version of assemble are you using? 
- do you have any custom helpers define? 
- any other helpers besides the built-in helpers? 
- any plugins?
thx

**Comment by goodpixels** [comment]
* I'm using the latest version - 0.4.42
* no helpers, plugins, etc, just basic out-of-the-box setup

here's my folder structure:

```
src/
	_content/
		pages/
			home.md
	_data/
		pages/
			home.json
	_inc/
		footer.hbs
		header.hbs
	_layouts/
		default.hbs
	pages/
		home.hbs
```

and here's my `Gruntfile.js`:

```
assemble: {
	options: {
		flatten: true,
		partials: [ 'src/_inc/**/*.hbs', 'src/_content/pages/*.md' ],
		layoutdir: 'src/_layouts',
		layout: 'default.hbs',				
	},
	pages: {
		options: {
			data: 'src/_data/pages/*.json',
		},
		files: {'public/': ['src/pages/*.hbs']}
	},
}
```

**Comment by jonschlinkert** [comment]
I looked into it, and I see a place where the [postprocess plugin](https://github.com/assemble/assemble/blob/master/lib/plugins/postprocess.js#L29) uses the `content` variable, but it doesn't seem like that should cause the issue. It might be one the helpers.

**Comment by akileez** [comment]
If I remember correctly, it was the layout helpers which used `content`. It conflicted with handlebars-helper-compose back in the day...

**Comment by jonschlinkert** [comment]
That's what I was just looking for to confirm, thanks!

**Comment by jonschlinkert** [comment]
closing since this is a grunt-assemble issue
