### ISSUE TITLE
customizing layout/helper/partial name generation

### ISSUE THREAD

**Issue by waynedpj** [assemble/assemble#654]
@jonschlinkert possibly related to #578: is there a way to customize the name under which the layouts/helpers/partials are named?  i have layouts/partials/helpers that are provided in a heirarchy e.g.

```
layouts/
            HTML/
                       doc.html
                       page.html
                       content.html
            SVG/
                       doc.svg
                       lyrics.svg
```
and so i need to reference layouts/helpers/partials via their relative paths:
```
layout: HTML/page
```
i believe it involves a custom load function (similar to that passed to `assemble.create`) but a) i would like to reuse the already present loading functionality that already converts globs, arrays, etc. to layouts/helpers/etc. and just tap in to the name generation, not replace the entire loader; b) replace the loader for the existing `layout` type.  are these things doable?  right now i am only able to create an entire new loader for a new template type via `create`.

thanks.

**Comment by jonschlinkert** [comment]
try passing a `renameKey` function on the options:

```js
assemble.option('renameKey', function(fp) {
  // do stuff to file path
});
```

This function determines how the object key of each template is named. there are more things we can try if this isn't enough

**Comment by waynedpj** [comment]
thanks, `renameKey` to the rescue :)

**Comment by jonschlinkert** [comment]
This worked for you then?

**Comment by waynedpj** [comment]
sorry if i did not make it clear, but yes `renameKey` worked to change the name under which a layout can be accessed .. just not at first, as i was mistakenly trying to pass each vinyl inside a task's `assemble.src('in/layouts/**/*.*)` stream to `assemble.layouts` which caused it to obviously not work for awhile.  my workflow right now gets everything into a Vinyl form so i can use the large Gulp/Vinyl ecosystem to pre/process/etc, then register.  thus, setting the layouts directly with a path/glob IMHO seems kinda un-gulp like .. for example, i need to preprocess layouts before registering them.  is that far fetched?

one quirk currently is that there is no way to pass the new base to cut the path off at (i.e. similar to how Vinyl's generate the `relative` property from their `base` and `path` properties), besides just sharing a variable in the assemble file.

one thing i did think of since i posted that it worked (and was planning on reposting if i could come up with a better use case) that it may be useful to have access to more than the path to decide on the key.  i realize this could be difficult since methods like `assemble.layouts` need to handle globs, paths and objects.  and i also realize that technically with the path at least the file can be loaded and read (e.g. if checking for a variable in front matter context), but assemble does this already and it seems weird to do all that in `renameKey`.  right now i cannot think of a very useful example besides checking for a name variable inside the front matter to use for the name, but it might be something to keep in mind?  or i am talking crazy.

**Comment by jonschlinkert** [comment]
> thus, setting the layouts directly with a path/glob IMHO seems kinda un-gulp like ..

Yeah, its not gulp-like. gulp wasn't made for that.  If you're trying to use gulp for a project where you need to use `assemble` methods, my recommendation is to use assemble directly. 

fwiw, @doowb and I have discussed getting rid of the gulp-assemble plugin, because of this trend.  it seems to be adding to the problem and confusion of what gulp is intended to do versus assemble.

**Comment by waynedpj** [comment]
i am no expert, so take my feedback w/ lots of salt, but the overlap of gulp and assemble has been confusing for me.  i am learning how much more assemble does, however i have been trying to use it in my gulp/stream setup instead of switching over to all assemble.  as you say, going with assemble may be easier but i am not sure how everything maps and if i want to switch so much mid stream (no pun intended!).

IMHO currently i see assemble as a multi faceted super gulp plugin/setup lib with lots of features, maybe too many to get my head around yet.  however, i have been trying to use the various parts of assemble ([layouts](https://github.com/doowb/layouts), [plasma](https://github.com/jonschlinkert/plasma), etc.) directly to keep things more manageable, kinda bringing assemble in piece by piece.

again, lots of salt!

**Comment by jonschlinkert** [comment]
this also should be taken with a grain of salt, but it's worth considering that if we ourselves thought this could or **should** all be done as gulp plugins, we would have done it. Assemble was initially a grunt plugin, and it seriously limited what Assemble can accomplish, so we've built everything from the ground up with a comprehensive API. 

In other words, IMHO what you're try to accomplish is great if you like a challenge and you just want to figure things out - but it's not idiomatic to gulp or assemble. When you have to write custom logic **for gulp** to do what assemble does natively, you're doing it wrong. 

Here are the core areas of the Assemble API, for a better perspective:

- **Template API**: methods for loading, caching and rendering, like `.loader()`, `.load()`, `.page()`, `.partial()`, `.layout()`, `.render()`, `.engine()`, `.helper()` etc.
- **Config API**: methods for setting options, `.option()`, `.enable()`, `.disable()`
- **Data API**: methods for loading, and caching data to be passed to templates, like `.data()`, `.transform()`
- **Middleware API**: methods related to routes and middleware, like `.use()`, `.preRender()` etc
- **Workflow (Task) API**:  methods for reading and writing to disk, and watching files: `.src()`, `.dest()`,  `.task()`, `.watch()`. Without doing math, I'm guessing this is less than 10% of the API

To try to get gulp to do the first four bullets seems like a lot of work. 

The important takeaway here is that @doowb and I spent about a year getting this all to work together. I'm not at all suggesting that you shouldn't try to do whatever works for your setup, but I'm very familiar with all of the challenges your having - and will have - trying to get these pieces to work together, and it's not easy

**Comment by waynedpj** [comment]
thanks @jonschlinkert for your explanation/advice which i take as the expert help that it is, no salt needed!  i apologize if i made it seem like i thought assemble was anything other than a major step forward.  that was **not** my intention at all!  i was just trying to explain from the basic level i am at where i was struggling and why (prob in not the most appropriate terms), as some possibly helpful feedback (which it obviously was not!).

i am discovering the many benefits of using assemble over gulp, as much as my current limited experience w/ gulp, assemble, etc. allows.  and i am not intentionally trying to redo assemble-like features in gulp with custom code.  in fact that is why i am trying to integrate with assemble: as you correctly pointed out i am slowly seeing the same problems that you have already solved.  and i trust in your experience with all this more than my experimentation!  unfortunately i can only handle bits at a time, whatever my limited understanding, skill and time allows.  very slowly and sometimes not-so-surely ;)  regardless, thanks again for your advice and *all* you and @doowb are doing!

**Comment by jonschlinkert** [comment]
> ...anything other than a major step forward.

I didn't read into that at all, no worries. All of this will make more sense when we get docs up!

**Comment by jonschlinkert** [comment]
@waynedpj I just re-read my comment and it comes across different than how I know I was thinking at the time. e.g. it sounds like I was defending assemble, I just wanted to make sure you know that's not the case. I was more concerned about you having an uphill battle although I (and @doowb) would be more than happy to help. 

In fact, (not that you're looking for this), but for fun we've discussed writing a blog post to show how to create a static site generator from scratch if assemble doesn't work for someone. at least that would give a head start. I love playing around with other great tools like metalsmith, it's what we all do right :) try new things and learn...

anyway, I just wanted to make sure that didn't come across the way it might sound...

**Comment by waynedpj** [comment]
> @waynedpj I just re-read my comment and it comes across different than how I know I was thinking at the time. e.g. it sounds like I was defending assemble, I just wanted to make sure you know that's not the case. I was more concerned about you having an uphill battle although I (and @doowb) would be more than happy to help.

thanks @jonschlinkert but no worries!  that was not what i took away from it at all.  you and @doowb have been a *huge* help+inspiration for my project, in addition to all the work you do w/ Assemble and the community around it.  and you are correct: i have banged my head against problems only to find a module by one of you 2 that solves it!  thus one of things i am slowly learning is that npmjs.org is your friend :wink:  anyway, thanks as always.

moreover, for me there is no need to defend Assemble: i learned JavaScript specifically to use it and try to make plugins for 0.4 :smile:  as i may have mentioned before, i got stuck and then went to gulp while waiting for 0.6 (since they were related).  now that i have moved farther along w/ gulp but 0.6 is arriving, it is hard (i.e. mainly due to my lack of ability and time) to switch everything back to Assemble 0.6 right away, but that is the goal.

> In fact, (not that you're looking for this), but for fun we've discussed writing a blog post to show how to create a static site generator from scratch if assemble doesn't work for someone. at least that would give a head start.

very cool, but not as if you 2 do not have enough to do :stuck_out_tongue_winking_eye: 

> I love playing around with other great tools like metalsmith, it's what we all do right :) try new things and learn...

well said :smiley:.  thanks again.

PS. apologies for all the smileys, i just discovered :colon: :+1: :wine_glass: :bread: :coffee: :smiley:

**Comment by jonschlinkert** [comment]
lol you can never have too many smileys! 

> i learned JavaScript specifically to use it and try to make plugins for 0.4

that's awesome! that may be the coolest compliment we've ever had for assemble! and I guess that makes two of us :)
