### ISSUE TITLE
middleware for layouts 

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble#655]
@doowb this is a continuation of https://github.com/assemble/assemble.io/issues/142#issuecomment-77877273

**Comment by doowb** [comment]
> maybe we can take a done function or something

I'm not sure what you mean by this... if we want to handle building the layouts inside a middleware, I think it would have to be added after the user defined `preRender` middleware in case `file.data.layout` is updated inside a `preRender` middleware.

`.handle` already has a `done` function, we're only using that to handle errors. We could move that in there, or we can expose/publish an `applyLayouts` middleware that users would need to register where ever they want it to be run. Then it could be something like:

```js
function updateLayout (file, next) {
  if (file.data.posts) {
    file.data.layout = 'post';
  }
  next();
}

assemble.preRender(/\hbs/, updateLayout, assemble.middleware.applyLayout);
```

**Comment by jonschlinkert** [comment]
what we're doing in handle is what I was thinking. but then we would need to expose logic that makes this more complicated. closing for now, we can revisit when it makes sense
