### ISSUE TITLE
Using Assemble v0.6.0 in Grunt

### ISSUE THREAD

**Issue by EmilioAiolfi** [assemble/assemble#656]
guys ,
how do I use assemble 0.6.0 in grunt ?

I run assemble in grunt dont work

```shell
$ grunt assemble
>> Local NPM module " assemble " not found . Is it installed ?
Warning : Task " assemble " not found . Use --force to continue.
```

help me, pls.
tks.

**Comment by jonschlinkert** [comment]
please create grunt related issues here https://github.com/assemble/grunt-assemble.
