### ISSUE TITLE
Partials in v0.6.0

### ISSUE THREAD

**Issue by stefanwalther** [assemble/assemble#657]
Hi,

great work, really is fun working with v0.6.0!!!
Though I cannot get partials to work:

**Default template (default.hbs)**

```html
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>site title</title>
</head>
<body>

<h1>{{title}}</h1>

<!-- This is working -->
<div>
	{{#markdown}}
		{% body %}
	{{/markdown}}
</div>

<!-- Whereas this is not working -->
<div>
	{%= partial('content')%}
</div>

</body>
</html>
```

**partials/content.hbs**
```html
<div>
	{{#markdown}}
		{% body %}
	{{/markdown}}
</div>
```

**assemblefile.js**
```javascript

'use strict';
var assemble = require( 'assemble' );
var less = require( 'gulp-less' );
var extname = require( 'gulp-extname' );
assemble.helper( 'markdown', require( 'helper-markdown' ) );

assemble.option( 'layout', 'default' );
assemble.option( 'assets', 'assets' );
assemble.layouts( 'source/layouts/**.hbs' );
assemble.partials( 'source/partials/**.hbs' );

assemble.task( 'site', function () {
	assemble.src( 'source/docs/**/**.md' )
		.pipe( extname() )
		.pipe( assemble.dest( 'dist' ) );
} );

assemble.task( 'default', ['site' /*, 'css', 'assets'*/ /*, 'watch'*/] );

```

Any ideas? Thx!

**Comment by doowb** [comment]
Since handlebars is the default engine for assemble, you should be using the handlebars helper syntax...

```has
{{partial "content"}}
```

**Comment by stefanwalther** [comment]
Thx, the partial is now included if doing as suggested, but ```{% body %}```is not resolved in this code (part of the partials file):

```html
<div>
	{{#markdown}}
		{% body }
	{{/markdown}}
</div>
```

**Comment by doowb** [comment]
Oh I missed that part. The layouts are applied before the handlebars templates are rendered so what you're doing won't work. 

If you want a layout that just does the markdown part you can make that and set is parent layout to `'default'`. Then any page you want to render with markdown will use the markdown layout.

**Comment by doowb** [comment]
I can post a better example when I get to my computer.

**Comment by doowb** [comment]
You have 2 options based on how you want to set it up in your build.

 1. Use regular layouts:

> `layouts/default.hbs`

```hbs
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
</head>
<body>

<h1>{{title}}</h1>
<div>
  {% body %}
</div>
</body>
</html>
```

> `layouts/content.hbs`

```hbs
---
layout: default
---
    {{#markdown}}
        {% body %}
    {{/markdown}}
```

> `docs/something.md`

```md
---
layout: content
---
# Header goes here
```

 2. Use partials with layouts

> `layouts/default.hbs`

```hbs
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
</head>
<body>

<h1>{{title}}</h1>
<div>
  {% body %}
</div>
</body>
</html>
```

> `partials/content.hbs`

```hbs
    {{#markdown}}
        {% body %}
    {{/markdown}}
```

> `partials/something.md`

```md
---
layout: content
---
# Header goes here
```

> `pages/docs.hbs`

```hbs
{{partial "something"}}
```

Looking at your setup above, the first way is probably better and you can change the "default" layout to `content` so all your markdown files will be wrapped with the `{{#markdown}}` helper.

**Comment by jonschlinkert** [comment]
The short answer is that `{% body %}` only works with layouts.

**Comment by jonschlinkert** [comment]
> great work, really is fun working with v0.6.0!!!

thanks for the feedback too! great to hear! We still have some kinks to work out, but these issues are critical in helping us, thanks!

**Comment by stefanwalther** [comment]
Thx all!

**Comment by jonschlinkert** [comment]
Anytime!
