### ISSUE TITLE
v0.6.0: Copying assets corrupts images

### ISSUE THREAD

**Issue by stefanwalther** [assemble/assemble#659]
Hi,

if I am copying images the images get corrupted (.png, .gif, etc. files.).
I think some replacing takes place, but I couldn't find it in the code, had something very similare in the past with grunt-replace tasks:

```javascript
assemble.task( 'assets', function () {
	assemble.src( 'source/assets/**', {layout: null} )
		//.pipe( debug() )
		.pipe( assemble.dest( 'dist/assets/' ) );
} );
```

**Comment by jonschlinkert** [comment]
I thought I had the same issue a week or two ago, this is confirmation. thanks for reporting. This should be a simple fix if I'm right about what it is. For development we were using a wildcard for the default engine, I think it's still there - which means the default engine is trying to render your images - obviously not what we want. we'll get it fixed

**Comment by stefanwalther** [comment]
Great, thx!

**Comment by jonschlinkert** [comment]
Hmm, in the meantime try doing `assemble.src( 'source/assets/**', {layout: null, read: false} )`, or `assemble.src( 'source/assets/**', {layout: null, render: false} )`. A month or so ago I tested this on a branch, but sadly I can't remember which property or if we implemented it in v0.6.0 yet.

**Comment by stefanwalther** [comment]
Unfortunately both not working

```layout: null, read: false``` - doesn't copy the content at all
```layoout: null, render: false``` - cannot see any changes, images are still corrupt

**Comment by jonschlinkert** [comment]
Worth a try, thanks for letting me know!

**Comment by akileez** [comment]
for copying images... this should work.
`assemble.copy` takes a `src` and `dest` as parameters.

```js
assemble.task('assets', function () {
  return assemble.copy('source/assets/**', 'dist/assets/');
});
```

**Comment by stefanwalther** [comment]
@akileez, thx, this works!

**Comment by jonschlinkert** [comment]
thanks @akileez!

**Comment by jonschlinkert** [comment]
closing since it sounds like this was solved

**Comment by Melindrea** [comment]
I can open a new issue if you'd prefer, but I have the same issue, except I can't use copy, as I want to run a gulp-plugin (image minification) on the assets.

**Comment by jonschlinkert** [comment]
No need, we're working on solving it. Once solved, you shouldn't need to use copy so you'll be able to minify too

**Comment by Melindrea** [comment]
I figured that, and that I'd let you know =)

**Comment by jonschlinkert** [comment]
... it's a pretty trivial fix, one of us just needs to get a chance to do it.

**Comment by jonschlinkert** [comment]
no worries :)

**Comment by jonschlinkert** [comment]
rather thank you for letting us know

**Comment by doowb** [comment]
I'll push up the fix in a few minutes. If it still doesn't work for @Melindrea then you can open a new issue.

**Comment by doowb** [comment]
I pushed up the one change that removes the default engine from default types so they won't be rendered. But this issue still happens because whenever a file is added through `template-init`, we try to parse the `contents`, so images are being corrupted.

A work around is using `minimal: true` in the options for `assemble.src`:

```js
assemble.task('images', function () {
  // read in images
  return assemble.src(['path/to/images/*.png'], { minimal: true })
    // add other plugins for processing images
    // ...
    // write out images
    .pipe(assemble.dest('dist/assets/img'));
});
```

We're working on some other ways of doing this so `minimal` isn't necessary.

**Comment by jonschlinkert** [comment]
this would be resolved by what I suggesting though, right? except we would need to do it in the init plugin and the render plugin, and we might need to tweak how it works in the init plugin. look at how it's implemented in verb https://github.com/assemble/verb/blob/master/lib/plugins/render.js#L23-L31

**Comment by jonschlinkert** [comment]
also, @doowb  you pushed to the wrong branch
