### ISSUE TITLE
v0.6.0: Error message when partial is not found

### ISSUE THREAD

**Issue by stefanwalther** [assemble/assemble#660]
This was a hard one, had a typo when calling a partial, this caused the following error which took me a while to find that actually the partial couldn't be found

```bash
D:\XXX\prototype\XXX\docgen\node_modules\assemble\node_modules\gulp-util\lib\PluginError.js:112
    return '    ' + prop + ': ' + self[prop];
                                ^
TypeError: Cannot convert object to primitive value
```

**Comment by jonschlinkert** [comment]
Yeah, that one is a pita. we're trying to get this resolved. we might need to get a quick fix implemented until we can do this correctly. If you do `console.log()` [above this line](https://github.com/assemble/template-render/blob/master/index.js#L90) and [this line](https://github.com/assemble/template-render/blob/master/index.js#L74) it will give you better info. This is not a solution, only a temporary holdover while we fix

**Comment by stefanwalther** [comment]
Thx @jonschlinkert

**Comment by stefanwalther** [comment]
Unfortunately the links above don't work anymore. Still getting this, which is unfortunately very annoying, can't really figure out to catch this and/or getting a better error message in case of something is missing, in my case helpers are missing:

```js
D:\Projects\Node.js\assemble\node_modules\gulp-util\lib\PluginError.js:102
    return '    ' + prop + ': ' + self[prop];
                                ^
TypeError: Cannot convert object to primitive value
```

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of assemble
