### ISSUE TITLE
[v0.6.0] assemble.engine('html', nunjucks) still tries to renders `*.html` with handlebars.

### ISSUE THREAD

**Issue by airtonix** [assemble/assemble#661]
```coffee

assemble = require 'assemble'
nunjucks = require 'template-nunjucks'

nunjucks.configure root: 'somepath'

assemble.init()
assemble.engine 'html', nunjucks
console.log assemble.engines
```

Results in

```
{ '.hbs': 
   { render: [Function],
     renderSync: [Function],
     compile: [Function],
     options: { layoutDelims: [Object], destExt: '.html' },
     helpers: {},
     name: 'render' },
  '.md': 
   { render: [Function],
     renderSync: [Function],
     compile: [Function],
     options: { layoutDelims: [Object], destExt: '.html' },
     helpers: {},
     name: 'render' },
  '.*': 
   { render: [Function],
     compile: [Function],
     options: {},
     helpers: {},
     name: 'noop',
     renderSync: [Function] } }

```

**Comment by jonschlinkert** [comment]
I think it's not `.html` specifically, my guess is that it's the wildcard, the same issue I mentioned on https://github.com/assemble/assemble/issues/659. we need to get this resolved. I'll look at it now

**Comment by doowb** [comment]
I know what this is. I thought I fixed it but it might have been in the context-manager branch on template... the engine is set in the defaults when creating the default types and then it's set on `template._engine` and is impossible to override with the default types.

**Comment by jonschlinkert** [comment]
I'm totally in favor of removing all defaults for engines and having the user explicitly define them. Even engine-assemble, I think we should move in that direction. any feedback welcome

**Comment by waynedpj** [comment]
:+1:

**Comment by airtonix** [comment]
Yeah, if people want default curated behaviour they can use your `Verb` tooling.

**Comment by jonschlinkert** [comment]
> Yeah, if people want default curated behaviour they can use your Verb tooling.

very true, but only if they want to render markdown documentation with Lo-Dash templates. your point is a good one though, this leaves more room for community-curated (opinionated) boilerplates

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of assemble
