### ISSUE TITLE
Create sitemap.html from files v0.6.0

### ISSUE THREAD

**Issue by Melindrea** [assemble/assemble#663]
Hi,

Do you have any suggestions on where to start looking for either a plugin, or *something* on how to create a sitemap from the source .md or built HTML-files?

I have a plugin, gulp-sitemap, that'll give me an XML sitemap, but I'd also want to create an HTML-file with the hierarchy (list), with the same templates as the rest of my files, but the content will be nested list with URLs to the pages.

So, given index.md, stories.md, stories/microfiction.md (all of which are compiled at the same time), I'd want a list as follows:

```html
<ul>
  <li><a href="/">Home (based on a variable in the md file</a></li>
  <li><a href="/stories">Stories</a>
    <ul>
      <li><a href="/stories/microfiction">Microfiction</a></li>
    </ul>
  </li>
</ul>
```

Thoughts on how to think to figure out what I need to do to get that as I build the pages?

**Comment by jonschlinkert** [comment]
https://github.com/assemble/assemble-middleware-sitemap starting point? I think the collections stuff @doowb and I just worked on will make this easier too

**Comment by jonschlinkert** [comment]
closing since this should be fairly easy to do with plugins/middleware with the latest assemble
