### ISSUE TITLE
The or Comparison does not work

### ISSUE THREAD

**Issue by grayghostvisuals** [assemble/assemble#665]
How can I make an or comparison? Here's my example [http://www.codeshare.io/gH8Lu](http://www.codeshare.io/gH8Lu)

Also see [https://github.com/assemble/gulp-assemble/issues/22#issuecomment-80562057](https://github.com/assemble/gulp-assemble/issues/22#issuecomment-80562057) for my initial question that i filed incorrectly.

**Comment by jonschlinkert** [comment]
@grayghostvisuals we're trying to help, but the way you're defining the `or` helper isn't going to work, so I have no idea what you're actually trying to achieve.

Can you just describe it? Per your other comment on the other issue, if you don't want to explain it to us, don't. we're always happy to help, but like you we have shit to do, but I want you to hit this out of the park, so let's just make everyone happy and see if we can figure this out.

Are you trying to conditionally render those script tags when "something" happens? From the helper, I really can't tell what that is.

**Comment by jonschlinkert** [comment]
...I'm re-reading too, just to make sure I didn't misunderstand/miss something

**Comment by jonschlinkert** [comment]
no, yeah I'll need more detail. If you can tell me what you need to accomplish as specifically as possible, I can't show you how to render just about anything.

**Comment by doowb** [comment]
I think I get it now... try:

```hbs
{{#any "index, expando-search" this.basename}}
<script src="js/lib/classie.js"></script>
<script class="demo-js">var tks_expando_form = document.querySelectorAll('.tks-expandoform');
for (var i = 0, len = tks_expando_form.length; i < len; i++) {
  new UISearch(tks_expando_form[i])
}</script>
{{/any}}
```

**Comment by grayghostvisuals** [comment]
@jonschlinkert 
Im trying to only load in the script block you see on index.html or expando-search.html. 

Also it's not that I don't want to explain it to you it's that I'm trying to discuss other aspects before going in a direction I don't think we need to go in such as a setup discussion. I'm not even gonna address the "we all have shit to do" comment because I think it was uncalled for.

**Comment by jonschlinkert** [comment]
that was part of the same sentence as...

> but I want you to hit this out of the park

and 

> we're always happy to help,

and 

> let's just make everyone happy and see if we can figure this out.

we're done

**Comment by grayghostvisuals** [comment]
Wow! @jonschlinkert we're done? nice one. anyways thanks @doowb

**Comment by jonschlinkert** [comment]
look, we were trying to help, @doowb and I were going back and forth on slack trying to figure this out for you. but your last comment just gave me a "wtf?" moment. I was giving you a "friendly" jab, like "hey bro, lighten up, let's get past this hump so you can win". True, we haven't had each other over for barbecues, but I'm disappointed that you would view that any other way after the number of times we've worked on stuff.

**Comment by grayghostvisuals** [comment]
@jonschlinkert I said it in the other issue to doowb

> "What I'm trying to do is not have certain script blocks load in single page case studies for the style guide. "

I was being polite and my examples were well explained. You also could have eliminated the line about having shit to do from your response. It has no effect if you say nice things post when all I read is that part. We all have other shit to do. I get it all the time as well, but I don't say that to other people in issues when they have a question or inquiry.

**Comment by grayghostvisuals** [comment]
Weird the response from @doowb isn't showing in this issue anymore where he posted the solution using ``{{any}}``.

**Comment by doowb** [comment]
I removed it because I didn't actually test it and didn't want to cause more confusion if it didn't work.

**Comment by jonschlinkert** [comment]
I'm not sure why @doowb removed his response, I think he did right after he posted it because it wasn't correct (I believe), probably not for any other reason. 

> You also could have eliminated the line about having shit to do from your response.

what does this mean? I also said "but like you..." and then I said we have shit to do, which we do, and now I'm spending time rehashing this with you instead. I said that response to your implying that you didn't have time to answer my questions.

**Comment by jonschlinkert** [comment]
this was how you responded to my first questions:

> Can you tell me exactly what it takes to make what I desire come to fruition? Maybe I can do some checks on my end first before going nuts with a setup discussion?

so you think that's not setting a negative tone? My bad if I'm causing you to go nuts with my questions to help. Honestly, if you come here for help and actually get it, then respond like I'm putting you out because you're too busy, I can't see how you're so surprised at my reaction.

**Comment by doowb** [comment]
> I'm not sure why @doowb removed his response

I realized that we have [`any` for collections](https://github.com/assemble/handlebars-helpers/blob/v0.6.0/lib/helpers/collections.js#L15) and [`any` for comparisons](https://github.com/assemble/handlebars-helpers/blob/v0.6.0/lib/helpers/comparisons.js#L43) in [handlebars-helpers#v0.6.0](https://github.com/assemble/handlebars-helpers/tree/v0.6.0) so one of them is overwriting the other one and I'm not sure which. There's probably a better solution for this anyway.
