### ISSUE TITLE
v0.6.0 Loading data (yaml and/or JSON)

### ISSUE THREAD

**Issue by Melindrea** [assemble/assemble#666]
This feels like it's probably obvious but I missed it somewhere.

In prior version you could set data to be loaded from a folder with `options: { data: 'glob/pattern' }`. How would I do that best in the new version (I tried `assemble.option('data', ['data/*.yaml']);` but that took it quite literally.)

**Comment by akileez** [comment]
for files: `assemble.data('data/*.yaml');` 

or as an array of files: `assemble.data(['data/*.yaml', 'config/**.{yam,json}]);` 

you can also load objects and other methods. I'll let @doowb or @jonschlinkert  fill in those details. I forget offhand.

**Comment by jonschlinkert** [comment]
thanks @akileez that's a great summary, you covered most of it. you can also pass an object directly:

```js
assemble.data({site: {title: 'Blog'}});
```
Also, as with Assemble v0.4.x, if you load a file that has the filename `data`, e.g.  `data.json` or `data.yml`, any data from that file is loaded directly onto the root of the context.

**Comment by jonschlinkert** [comment]
one more thing, you can also pass a function:

```js
assemble.data('package.json', function(fp) {
  return require(path.resolve(fp));
});
```

This is useful if you need to modify whatever is being loaded. 

**Example**

```js
assemble.data('*.json', function(fp) {
  return glob.sync(fp).reduce(function(acc, fp) {
    acc[fp] = require(path.resolve(fp));
    return acc;
  }, {});
});
```

**Comment by Melindrea** [comment]
Aha. Yeah, that should do the trick. That's one of the final pieces of the puzzle, so I might even launch the next version of this site, built in Assemble, tomorrow.

**Comment by jonschlinkert** [comment]
:+1:
