### ISSUE TITLE
v0.6.0 and Collections

### ISSUE THREAD

**Issue by stefanwalther** [assemble/assemble#667]
Hi,

I am so far quite happy with v0.6.0, managed to get a larger site up and running with templates, helpers, some other gulp-taks, all fine so far.

What I am really missing so far is collections, so the ability to add additional tags in front matter and use them in dynamic handlebars statements within layouts, like.

#each pages
  do something with the collection of pages, but do some more advanced stuff like using if statements, nested collections, etc.
/each

or 

#each tags
  build my tag list ...
/each

(sorry, working on my iPad and finding the correct characters is a challenge here)

I have somewhere read that 0.6.0 doesn't support collections yet. What do you recommend:

- Workaround 1: Creating some tasks where I write some .yml files, load them into assemble.data, would work fine but the drawback is that I have then disconnected the files from data, so would really like to have the data in front matter ...
- Workaround 2: I don't know, that's why I am asking
- Workaround 3: Be patient, go live now with assemble 0.4.0 and move later ... it was very powerful in v0.4.0 ...

What do you recommend?

Regards
Stefan

**Comment by jonschlinkert** [comment]
We're working on adding a plugin/helper for working with collections in 0.6.0, there are a number of issues open that ask the same or similar questions. this is something that the community could do too. I'll post an update when we get something done, in the meantime I'm going to close since there are other related issues

**Comment by stefanwalther** [comment]
OK, looking forward to test first results of your work!
