### ISSUE TITLE
Basic lodash engine example doesn't produce expected results

### ISSUE THREAD

**Issue by raine** [assemble/assemble#671]
Here's what I came up with:

```js
var assemble = require('assemble');

assemble.engine('tmpl', require('engine-lodash'));

assemble.data({ foo: 'bar' });

assemble.task('html', function() {
  assemble.src('templates/*.tmpl')
    .pipe(assemble.dest('dist/'));
});

assemble.task('default', ['html'])
```

In `templates/index.tmpl` I have:

```html
<%= foo %>
```

Shouldn't this setup give me `dist/index.html` with content `bar` or am I not getting something?

Instead, this is the result:

```sh
$ assemble
[01:03:33] Using assemblefile ./assemblefile.js
[01:03:34] Starting 'html'...
[01:03:34] Finished 'html' after 15 ms
[01:03:34] Starting 'default'...
[01:03:34] Finished 'default' after 12 μs
$ cat dist/index.tmpl
<%= foo %>
```

As a side note, it would be great if there were basic clonable examples that use the API described in README. All I could find was boilerplate repos with complex gruntfiles.

**Comment by doowb** [comment]
First issue is that it's not renaming `.tmpl` to `.html` because we don't handle that automatically for you anymore. Use `gulp-extname`:

```js
var extname = require('gulp-extname');

assemble.task('html', function() {
  assemble.src('templates/*.tmpl')
    .pipe(extname())
    .pipe(assemble.dest('dist/'));
});
```

The second issue is that it's not rendering the template with lodash, so this is probably a bug. How did you install `assemble` and what version is in the `package.json`?

Also, we're in the process of updating documentation and the boilerplates are for the old grunt version of assemble.

**Comment by raine** [comment]
Thanks for the quick response. I was totally expecting to get an html file out. After all, assemble is marketed as static site generator.

I installed assemble with `npm install -g assemble@beta` and got version `^0.6.0-beta.4` in package.json.

As someone who's new to this project, the API looks basically like that of gulp so I haven't really grokked the point of Assemble, why not simply have a bunch of gulp plugins.

**Comment by jonschlinkert** [comment]
> After all, assemble is marketed as static site generator.

Assemble also allows you to render anything, not just HTML. 

> As someone who's new to this project, the API looks basically like that of gulp so I haven't really grokked the point of Assemble

Is this a question or a statement?

**Comment by jonschlinkert** [comment]
crap I can't find my answer to this before. @doowb do you know where that was? I should add it to the readme

**Comment by waynedpj** [comment]
> crap I can't find my answer to this before. @doowb do you know where that was?

@jonschlinkert maybe you are looking for [this](https://github.com/assemble/assemble/issues/654#issuecomment-78629915)?

**Comment by jonschlinkert** [comment]
thanks! that's it!
