### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble#672]
creating this as a follow up to [this comment](https://github.com/assemble/assemble/issues/639#issuecomment-75362567) made by @agross

> Generally, I don't like that assemble does not log errors or fail when I declare `assemble.option('layout', 'does-not-exist')`.

We need to implement better error handling than what would be expected with gulp plugins. Users want to generate a project and should be comfortable in assuming that assemble will tell them when something went wrong.

**Comment by dtothefp** [comment]
@jonschlinkert maybe this is another issue, but Assemble also does not fail on yaml errors. I just had an error in my YFM and just resulted in lack of data for the page with no break of build or logging errors to the console

**Comment by jonschlinkert** [comment]
closing based on age

**Comment by Matt-Butler** [comment]
Can we please reopen this issue?

**Comment by Matt-Butler** [comment]
If a file fails to load, is there an option to throw an error?

**Comment by jonschlinkert** [comment]
Using what method? `.src`, `.data`?
