### ISSUE TITLE
Override assemble.data on a per task basis?

### ISSUE THREAD

**Issue by avr** [assemble/assemble#674]
I am trying to build out files with two tasks - one for local and one for dist.  Maybe I should be doing this through a plugin or helper - feel free to let me know.

I have the following two tasks

```
assemble.data(['src/data/*.yaml']);

// Build Local Files
assemble.task('local', function() {

    assemble.data({site: {url: 'http://dev.local' }});

    console.log(assemble.cache.data);

    assemble.src('src/pages/**/*.hbs')
        .pipe(extname())
        .pipe(assemble.dest('local/'));
});

// Build Remote Files
assemble.task('dist', function() {

    assemble.data({site: {url: 'https://remote.url.com' }});

    console.log(assemble.cache.data);

    assemble.src('src/pages/**/*.hbs')
        .pipe(extname())
        .pipe(assemble.dest('dist/'));
});

```

I can see that the data object is getting updated correctly when I log the data object.  However, the files are built with the default (from `src/data/data.yaml`).  Am I missing something or misunderstanding?

**Comment by doowb** [comment]
what does your `src/data/data.yml` file look like?

**Comment by avr** [comment]
```
site:
  name: Site Title
  url: "https://remote.url.com"
main_class: no-section-nav
layout: default-layout
```

I also tried moving both `assemble.src` into one task - still the same.

**Comment by doowb** [comment]
Try making `dist` depend on `local` finishing first:

```js
assemble.data(['src/data/*.yaml']);

// Build Local Files
assemble.task('local', function() {

    assemble.data({site: {url: 'http://dev.local' }});

    console.log(assemble.cache.data);

    return assemble.src('src/pages/**/*.hbs')
        .pipe(extname())
        .pipe(assemble.dest('local/'));
});

// Build Remote Files
assemble.task('dist', ['local'], function() {

    assemble.data({site: {url: 'https://remote.url.com' }});

    console.log(assemble.cache.data);

    return assemble.src('src/pages/**/*.hbs')
        .pipe(extname())
        .pipe(assemble.dest('dist/'));
});
```

**Comment by doowb** [comment]
If you're calling both tasks at the same time like `assemble.task('default', ['local', 'dist']);` and you don't make one depend on the other, then they run in parallel so the `assemble.data` is being called and updating data before the files in `local` have a chance to use it when rendering.

**Comment by avr** [comment]
The dependency thing is perfect - thanks for your help.

At first, it didn't work until I noticed that I was missing the `return`.  Do you have a quick explanation for that or a suggestion where I could dig a little more to understand?

**Comment by doowb** [comment]
with a `task` you can either return a `stream` or pass in a `callback` function and call it. This tells `assemble` to wait until the `stream` is finished or until the `callback` is called when the `task` is in a dependency list:

```js
// task returns a stream from `assemble.dest`
assemble.task('stream-task-a', function () {
  return assemble.src('**/*.hbs')
    .pipe(assemble.dest('_gh_pages'));
});

// task has a `callback` function so call when finished
assemble.task('callback-task-a', function (callback) {
  assemble.data(['data/**/*.json']);
  callback();
});

// task depends on `stream-task-a` finishing
assemble.task('stream-task-b', ['stream-task-a'], function () {
  console.log('stream-task-a has finished');
});

// task depends on `callback-task-a` finishing
assemble.task('callback-task-b', ['callback-task-a'], function () {
  console.log('callback-task-a finished');
});

// add all tasks to default
assemble.task('default', ['stream-task-a', 'stream-task-b', 'callback-task-a', 'callback-task-b']);
```

**Comment by avr** [comment]
Thanks - that's helpful.  I noticed you used the callback example in this demo:

https://github.com/doowb/assemble-test-data-watching/blob/master/assemblefile.js

I __think__ I understand how this is working now.  Is there any advantage to one or the other?  Or - are there certain instances where you'd want the returned stream and how would you access it?  Feel free to point me somewhere else or say "this isn't a support forum - ask that on SO".  :)

**Comment by doowb** [comment]
If you're working with a `stream` like from `assemble.src` or `assemble.dest`, just use `return`. If you're not working with a `stream` then use a `callback`.

You don't actually get access to the `stream` or `callback` results, it's just a way to tell `assemble`, "this task is finished".

**Comment by avr** [comment]
Ah - makes sense and makes sense why your `preload` task from the other repo just used the callback.  Very helpful.

Thanks again for taking the time to clarify!

**Comment by jonschlinkert** [comment]
:+1: good info for the docs! 


> Feel free to point me somewhere else or say "this isn't a support forum - ask that on SO". :)

we usually only suggest that if you want to get some points on SO :) but you're always welcome to ask questions here
