### ISSUE TITLE
Problem with partial in 6.0

### ISSUE THREAD

**Issue by arnriu** [assemble/assemble#675]
Hello,

First things first, I'm kinda new to assemble, sorry if my question is stupid / documented.
And my english is not perfect, i'll try my best ;)

So, I'm using assemble 0.6.0-beta.5 , with gulp-assemble 0.3.2.
The idea is: I have a simple layout, including a partial. And a page using the layout.
The mystery is: the layout and the page work, but not the partial in the layout.
I tried a lot of things, but i'm stuck. And it worked before in Alpha.

my gulp task:
```
var gulp = require('gulp'),
      assemble = require('assemble'),
      gulpAssemble = require('gulp-assemble');

gulp.task('assemble', function() {
    assemble.layouts('templates/layouts/*.html');
    assemble.partials('templates/partials/**/*.html');
    assemble.option('assets', '../../assets');

    gulp.src('./templates/pages/**/*.html')
        .pipe(gulpAssemble(assemble))
        .pipe(gulp.dest('./dist/views'));
});
```

My default layout:
```
<!doctype html>
<html lang="fr">
{{> head }}    (i tried {{ partial "head" }} too)

<body>		
	{% body  %}
</body>
</html>
```

My head partial:
```
<head>
	<meta charset="utf-8" />
	<title>{{title}}</title>

	<link rel="stylesheet" href="{{assets}}/styles/styles.min.css" />
	<script src="{{assets}}/scripts/scripts.min.js"></script>
</head>
```

My page:
```
---
layout: default
---

<h1>Page de test.</h1>
```

What I get:
```
<!doctype html>
<html lang="fr">
{{>head}}

<body>
			
	<h1>Page de test.</h1>

</body>
</html>
```

Thanks for your help !

**Comment by jonschlinkert** [comment]
hmmm, try using `{{> head.html}}`. if that works, we can show you how to get rid of the extension

**Comment by arnriu** [comment]
I did this, and i get the same result:

```
<!doctype html>
<html lang="fr">
{{> head.html}}

<body>
			
	<h1>Page de test.</h1>

</body>
</html>
```

**Comment by jonschlinkert** [comment]
have you tried using assemble directly? technically this issue should be on the gulp-assemble repo

**Comment by arnriu** [comment]
Yeah it was my thought, but i was not sure. I'm trying to use assemble directly right now, will let you know if it works. Correct me if I'm wrong, with assemble 6, I can do everything I'm doing in my gulpfile.js within an assemblefile.js right? I mean, my sass, js, whatever, ... tasks.

**Comment by jonschlinkert** [comment]
no worries, we can try to get this resolved here

> I mean, my sass, js, whatever, ... tasks.

correct, everything should. if you have any issues with it let us know and we'll try to get it fixed.

**Comment by arnriu** [comment]
Thank you :)

I tried this assemblefile.js (other files untouched, with: {{> head.html }} ):
```
var assemble = require('assemble');

assemble.task('html', function() {
    assemble.layouts('templates/layouts/*.html');
    assemble.partials('templates/partials/**/*.html');
    assemble.option({'assets': '../../assets'});

    assemble.src('./templates/pages/**/*.html')
        .pipe(assemble.dest('./dist/views'));
});
```

Running `assemble html`, i get the same result

**Comment by jonschlinkert** [comment]
can you try this and see if it works:

```js
var assemble = require('assemble');

assemble.layouts('templates/layouts/*.html');
assemble.partials('templates/partials/**/*.html');
assemble.option({'assets': '../../assets'});

assemble.task('html', function() {
    console.log(assemble.views);
    assemble.src('./templates/pages/**/*.html')
        .pipe(assemble.dest('./dist/views'));
});
```

Also, if that doesn't work add the output from `console.log(assemble.views)` here so we can take a look. thanks!

**Comment by jonschlinkert** [comment]
btw, what I just didn't shouldn't make any difference, I just want to see if there is something specific going on.

**Comment by arnriu** [comment]
Yeah no difference. If you want me tu run debug or log anything, please feel free to ask.

**Comment by arnriu** [comment]
Oh well, yes, your console log, sorry:

```
{ pages: {},
  layouts: 
   { default: 
      { content: '<!doctype html>\n<html lang="fr">\n{{> head.html }}\n\n<body>\n\t\t\t\n\t{% body  %}\n\n</body>\n</html>',
        path: '/Users/arnaud/Sites/pandaa/test/templates/layouts/default.html',
        ext: '.html',
        locals: {},
        options: [Object],
        layout: undefined,
        render: [Function],
        data: [Object] } },
  partials: 
   { head: 
      { content: '<head>\n\t<meta charset="utf-8" />\n\t<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />\n\t<meta name="apple-mobile-web-app-capable" content="yes" />\n\t\n\t<link rel="icon" type="image/png" href="{{assets}}/images/favicon.png" />\n\n\t<title>{{title}}</title>\n\t<meta name="description" content="{{desc}}" />\n\n\t<link rel="stylesheet" href="{{assets}}/stylesheets/styles.min.css" />\n\t\n\t<script src="{{assets}}/javascripts/scripts.min.js"></script>\n\t<script>var assets = "{{assets}}";</script>\n</head>',
        path: '/Users/arnaud/Sites/pandaa/test/templates/partials/common/head.html',
        ext: '.html',
        locals: {},
        options: [Object],
        layout: undefined,
        render: [Function],
        data: [Object] } } }
```

**Comment by jonschlinkert** [comment]
we'll keep trying lol.. try adding `assemble.enable('debugEngine')` above `assemble.layouts()` see if that outputs anything

**Comment by arnriu** [comment]
Nope, nothing new with `assemble.enable('debugEngine')`

**Comment by jonschlinkert** [comment]
ok, try this too and paste in the log:

```js
assemble.task('html', function () {
  assemble.src('./templates/pages/**/*.html')
    .on('data', function () {
      console.log(assemble.views);
    })
    .pipe(assemble.dest('./dist/views'))
});
```

**Comment by arnriu** [comment]
You get this sir:

```
{ pages: {},
  layouts: 
   { default: 
      { content: '<!doctype html>\n<html lang="fr">\n{{> head.html }}\n\n<body>\n\t\t\t\n\t{% body  %}\n\n</body>\n</html>',
        path: '/Users/arnaud/Sites/pandaa/test/templates/layouts/default.html',
        ext: '.html',
        locals: {},
        options: [Object],
        layout: undefined,
        render: [Function],
        data: [Object] } },
  partials: 
   { head: 
      { content: '<head>\n\t<meta charset="utf-8" />\n\t<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />\n\t<meta name="apple-mobile-web-app-capable" content="yes" />\n\t\n\t<link rel="icon" type="image/png" href="{{assets}}/images/favicon.png" />\n\n\t<title>{{title}}</title>\n\t<meta name="description" content="{{desc}}" />\n\n\t<link rel="stylesheet" href="{{assets}}/stylesheets/styles.min.css" />\n\t\n\t<script src="{{assets}}/javascripts/scripts.min.js"></script>\n\t<script>var assets = "{{assets}}";</script>\n</head>',
        path: '/Users/arnaud/Sites/pandaa/test/templates/partials/common/head.html',
        ext: '.html',
        locals: {},
        options: [Object],
        layout: undefined,
        render: [Function],
        data: [Object] } },
  __task__htmls: 
   { index: 
      { orig: '---\nlayout: default\n---\n\n<h1>Page d\'index.</h1>',
        data: [Object],
        content: '\n\n<h1>Page d\'index.</h1>',
        relative: 'index.html',
        base: '/Users/arnaud/Sites/pandaa/test/templates/views/',
        cwd: '/Users/arnaud/Sites/pandaa/test',
        stat: [Object],
        path: '/Users/arnaud/Sites/pandaa/test/templates/views/index.html',
        options: [Object],
        locals: [Object],
        ext: '.html',
        layout: undefined,
        render: [Function] } } }
```

**Comment by jonschlinkert** [comment]
okay, so we know that all of the templates are there. and we know that they are using the basename as the key.

this is the template type that is created by the task:

```js
__task__htmls: 
   { index: 
      { orig: '---\nlayout: default\n---\n\n<h1>Page d\'index.</h1>',
        data: [Object],
        content: '\n\n<h1>Page d\'index.</h1>',
        relative: 'index.html',
        base: '/Users/arnaud/Sites/pandaa/test/templates/views/',
        cwd: '/Users/arnaud/Sites/pandaa/test',
        stat: [Object],
        path: '/Users/arnaud/Sites/pandaa/test/templates/views/index.html',
        options: [Object],
        locals: [Object],
        ext: '.html',
        layout: undefined,
        render: [Function] }
```

oh, try changing the file extensions to `.hbs`.

**Comment by arnriu** [comment]
I changed extension of the 3 files from `.html` to `.hbs`
Nothing happens, no log, nothing.

My assemble file:
```
var assemble = require('assemble');

assemble.layouts('templates/layouts/*.hbs');
assemble.partials('templates/partials/**/*.hbs');
assemble.option({'assets': '../../assets'});

assemble.task('html', function () {
  assemble.src('./templates/views/**/*.hbs')
    .on('data', function () {
      console.log(assemble.views);
    })
    .pipe(assemble.dest('./dist/views'))
});
```

**Comment by jonschlinkert** [comment]
okay, obviously (as you pointed out) the partial tag isn't even being evaluated. I just wanted to narrow down other possible causes before we marked this a bug. Give me a minute, I'll do some testing on my end

**Comment by doowb** [comment]
@arnriu this might be a stupid question, but did you also change the file extension on the actual files to `.hbs`?

**Comment by arnriu** [comment]
Hello @doowb , Of course I did:
>I changed extension of the 3 files from .html to .hbs
To sum it up, i have now 3 .hbs files (the layout, the partial, the page), and the assemble file above.

**Comment by jonschlinkert** [comment]
strange that the partial is still in the rendered result as if it was escaped. that would only happen if it wasn't even passed to the engine

**Comment by arnriu** [comment]
Yeah, i thought it was because of some character causing strange escape in the head.html (now head.hbs btw), so I changed its content with `toto` (french equivalent of `foo`), and it didn't change anything.

**Comment by doowb** [comment]
Can you put up a repository so we can see the full code? You're setup looks correct from the snippets but there might be something we're missing.

**Comment by arnriu** [comment]
Here you go: https://github.com/arnriu/assemble-test

**Comment by arnriu** [comment]
(I reverted to `.html`, trying something, but I swear i did test `.hbs` ;) )

**Comment by doowb** [comment]
I renamed the files to `.hbs` and updated the glob patterns to `.hbs`.
I updated `{{> head.html}}` to `{{> head}}` in `templates/layouts/default.hbs`
I added `gulp-extname` to rename the files from `.hbs` to `.html` when they're written out.

Assemble used to fallback to handlebars when the extension didn't match the default extension (`.hbs`), so that's why `.html` probably worked for you before. But since there are issues with that when using files like images (`.png, .gif, .jpeg`) we decided to remove the fallback engine and only use `.hbs` as the default.

Let me know if you have any issues with the PR I made.

**Comment by arnriu** [comment]
Ok, so i missed 2 things: the fallback to handlebars removed for non `.hbs` extensions, and adding `gulp-extname` when renaming to `.hbs`.
Now it works perfectly.
You guys are awesome, thank you for your time and your work. Cheers from France.

**Comment by jonschlinkert** [comment]
any time!
