### ISSUE TITLE
[New Plugin] Collection indexing plugin with pagination

### ISSUE THREAD

**Issue by vwochnik** [assemble/assemble#676]
Hello all

in my quest to create a blog I have developed a plugin that is quite similar to assemble-index but more flexible.

The plugin can be found here:
https://github.com/vwochnik/assemble-plugin-index

I'd be happy to land on the assemble.io's plugin page.

peace
Vincent

**Comment by jonschlinkert** [comment]
that's great! we just talked about updating the current plugin to be used with assemble v0.6.0, any interest in helping with that? 

either way we'd be happy to add it to the site. thanks!

**Comment by jonschlinkert** [comment]
closing, I opened a new issue on assemble.io
