### ISSUE TITLE
Multiple src tasks at same time create duplicate pages

### ISSUE THREAD

**Issue by DusanMilko** [assemble/assemble#677]
When using something like:

```js
gulp.task('docs', function() {
  assemble.src('src/views/docs/\*\*/\*.hbs')
    .pipe(rename(function (path) {
      path.extname = ".html"
    }))
    .pipe(assemble.dest('build/docs/'));
});   
gulp.task('pages', function() {
  assemble.src('src/views/pages/\*\*/\*.hbs')
    .pipe(rename(function (path) {
      path.extname = ".html"
    }))
    .pipe(assemble.dest('build/'));
});
```

multiple srcs with multiple destinations. Running each task alone creates the pages in the right location. But if I run both tasks at the same the time, the src of the first task persists into the 2nd task and generates extra pages. Is there a solution to this?

expected result
---
build
---- (pages).html
-----docs
-----------(docs.html)

current result
---
build
----(pages).html
----(docs).html
-----docs
-----------(docs).html

It seems that the src doesn't clear when it goes into the 2nd tasks and output both into the 2nd tasks destination.

I run both doing something like:

```js
gulp.task('build', function() {
  gulp.run('docs');
  gulp.run('pages');
});
```

**Comment by akileez** [comment]
@DusanMilko  
solution is here: https://github.com/assemble/assemble/issues/674

**Comment by doowb** [comment]
@DusanMilko try using assemble directly instead of putting the `.src` and `.dest` in a gulp task. Assemble has a `session` that gets created for the `task` to ensure the source files aren't put on the same collection. When using a gulp task, that session isn't created so all the source files are stored in the same collection and all get pushed into the stream in the second task.

**Comment by akileez** [comment]
sorry about that.. I missed the `gulp` part. I assume everyone just uses assemble. doh!

**Comment by DusanMilko** [comment]
@doowb Thank you. Your solution worked
now doing

>assemble.task('docs', function() {
  assemble.src('src/views/docs/**/*.hbs')
    .pipe(rename(function (path) {
      path.extname = ".html"
    }))
    .pipe(assemble.dest('build/docs/'));
});   
assemble.task('pages', function() {
  assemble.src('src/views/pages/**/*.hbs')
    .pipe(rename(function (path) {
      path.extname = ".html"
    }))
    .pipe(assemble.dest('build/'));
});
gulp.task('assemble', function() {
  assemble.run('docs');
  assemble.run('pages');
});
