### ISSUE TITLE
Marked highlight example is incorrect

### ISSUE THREAD

**Issue by starwed** [assemble/assemble#678]
The page [here](http://assemble.io/docs/options-marked.html) has a couple of typos in the example under the highlight option.   (Not the example at the top, but the specific example using highlight.js under the highlight option.)

- It gives the signature of the function for highlight as  ` function  (lang, code) ` when it *should* be `function (code, lang)`.  (The correct signature is given at the top of the page.)
- It calls hljs.autoHighlight with the signature `autoHighlight(code, lang)` when it should be `autoHighlight(code, [lang])`.  (Or possible a call to `hljs.highlight(lang, code)` instead.)
- Also, I think the json  probably be `options: marked: highlight` rather than just `options:highlight`.

**Comment by jonschlinkert** [comment]
what version of assemble are yo using?

**Comment by starwed** [comment]
This is a bug in the docs that I link to, not assemble itself. I don't know your doc process, so I don't know if it was built against a particular version.

The marked version I checked against was 0.3.3.

**Comment by jonschlinkert** [comment]
So I'm guessing you're using a 0.4.x version of assemble?

**Comment by starwed** [comment]
Yeah, looking at it it's 0.4.3.

**Comment by jonschlinkert** [comment]
closing since this refers to the grunt-assemble plugin which was moved to https://github.com/assemble/grunt-assemble
