### ISSUE TITLE
Rendering markdown within a code block

### ISSUE THREAD

**Issue by marcelosomers** [assemble/assemble#680]
Not sure if this is a duplicate of #528, but I'm seeing some strange behavior when parsing content within a Markdown code block. Right now if I put any markdown tags within a code block, they're rendered as markdown. For example: `.foo__bar` gets rid of the underscores and starts a bold block until another set of double underscores.

The fix for now is to escape anything that would be interpreted as Markdown (i.e., `.foo\__bar`), but I'd hope the Markdown parser wouldn't render markdown inside a code block.

This may be an issue with the Markdown library and not with Assemble itself.

**Comment by doowb** [comment]
Which version of assemble are you using? Do you have an example of your templates we can take a look at?

**Comment by marcelosomers** [comment]
Our package.json is using the latest version (still in development).

Here's the `template.hbs`:
```
{{#markdown}}
{{> body }}
{{/markdown}}
```

And then I have an `index.hbs` loading within that body:
```
---
title: Foo
---
{{#each pages}}
  {{#contains this.dest "foo"}}
  {{#isnt ../../page.dest this.dest}}
  <div class="markdown__body">
    {{#markdown}}
      {{{page}}}
    {{/markdown}}
  </div>
  {{/isnt}}
  {{/contains}}
{{/each}}
```

Then the markdown file itself just has HTML, for example:
```
### Code Example
```html
<div class="page-group__row">
...
</div>
\``` (ignore the leading \ - just trying to keep my code block)
```

The two underscores cause everything to render in bold.

**Comment by jonschlinkert** [comment]
To clarify, are you using the grunt plugin or Assemble v0.6.0?

if 0.6.0, you need to use `{% body %}` for layouts. also, different markdown parsers are used in each version so a specific version would be helpful

**Comment by jonschlinkert** [comment]
closing due to lack of follow up
