### ISSUE TITLE
[v0.6.0] Handling of data in assemble

### ISSUE THREAD

**Issue by vwochnik** [assemble/assemble#681]
I have a couple questions regarding the data management of `assemble` v0.6.0.

1. Priority of data: In my tests, front matter overrides data issued by `.data()`. This might be a problem. I have a file `data/tags.yml` with all tags available in the form of `key: {name:..., caption:...}` and a list of tag keys in front matter `tags: [key, key]`. However, I can no longer access data from `tags.yml`. How can this efficiently be resolved?
   For inctance, I could imagine `assemble.data(glob, namespace)` or similar approaches but I cannot find any trace of the actual function called within `assemble` or `template`.

2. Working with data in the plugin pipeline: How do I insert data into `assemble`? Is the inserted data session-agnostic? How do I access the data again?

**Comment by jonschlinkert** [comment]
You can change how data is merged by passing a custom function on the `.mergeContext()` option:

```js
assemble.option('mergeContext', function() {
   // do stuff
});
```

See the [source code for mergeContext](https://github.com/jonschlinkert/template/blob/master/index.js#L2073) in template. It will be a better example than anything I can recreate

**Comment by vwochnik** [comment]
Thank you! But I've ran into a different problem that keeps me from progressing any further.

```js
// assemblefile.js
assemble.data('src/data/*.{json,yaml}');
```

```js
/// meta.yaml
title: "Test 123"
author: "Vincent"
```

```js
// template
{{json .}}
```

However, all I receive in my rendered page is `{"meta": ["object Object"]}`. I have tried changing the format to `json` but then I get an exception thrown at build time. I can `assemble.data({"meta":{/*...*/})` just fine.

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of assemble and has been resolved
