### ISSUE TITLE
v0.6.0 Layout Helpers

### ISSUE THREAD

**Issue by avr** [assemble/assemble#682]
Since the new version of `handlebars-helpers` doesn't include layout helpers (#extend, #content, #block), based on #652 I've added https://github.com/shannonmoeller/handlebars-layouts.

What is the intended way to register the layout helpers from `handlebars-layouts`?  My current setup is:

1. Include another copy of Handlebars in my package.json
2. Include handlebars-layouts in package.json
3. Initialize handlebars-layouts with the additional copy of handlebars
4. Attach just the helpers to assemble.helpers

```
var handlebars = require('handlebars');
var layouts = require('handlebars-layouts')(handlebars);

assemble.helpers(layouts.helpers);

```

It seems like I should be able to get `engine-assemble` version of Handlebars somehow.  Is that possible?  Or - maybe this really isn't a big deal...and this is good?

**Comment by vwochnik** [comment]
I did it this way:

```
assemble.helper('json', function(obj) {
  return util.inspect(obj);
});
```

Although, there might be a better way of assigning multiple helpers with `assemble`, you might have better luck looking into the source.

**Comment by doowb** [comment]
@avr if you're using `Handlebars 3+` then you should be able to do what you mentioned, but you don't need to register the helpers with assemble since they're already registered with Handlebars.

You can also ensure that you're using the same version of handlebars by doing:

```js
var handlebars = require('assemble/node_modules/engine-assemble/node_modules/handlebars');
```

but that's messy and if you do add Handlebars to your own package.json that one might be used instead of the one in `engine-assemble`.

If I get time I'll see about doing a PR to the other repo to expose the helpers then they can just be added like: 

```js
assemble.helpers(layoutHelpers);
```

**Comment by avr** [comment]
Thanks @doowb.

In working with this a bit more, I realized that I definitely do need to register the layout helpers with Assemble.  When I run my templates through `assemble.src` - if they don't have the extra layout helpers, things break (because Assemble doesn't know about the layout helpers).

I've also now run into an issue where the `handlebars-layouts` instance of Handlebars doesn't have all of my Assemble partials available.  So - I either need to re-register all of my partials with my new instance of Handlebars or (hopefully) just use the Assemble (maybe `engine-assemble`'s instance) of Handlebars.

Does that make sense?

**Comment by doowb** [comment]
I forgot that we exposed the Handlebars instance on the engine so you can get to it like this:

```js
var assemble = require('assemble');
var engine = assemble.engine('.hbs'); // gets the engine registered for handlebars templates
var handlebars = engine.handlebars; // this might be Handlebars
```

Now you can use that to register the `handlebars-layouts` helpers using the same instance.

Any partials that you load using `assemble.partials(...);` will be passed to the instance of Handlebars. I think you also need to register your layouts as partials to get `handlebars-layouts` to work.

**Comment by avr** [comment]
So I'm still running into issues.

If I use `var engine = assemble.engine('.hbs');` I get the error:

```
../my_site/node_modules/assemble/node_modules/template/node_modules/engine-cache/index.js:81
  engine.compile = engine.compile || fn.compile;
```

Looking through Template, I see there is a `getEngine` method that loads the engines from cache.  However, when using `assemble.getEngine('.hbs')`, I'm getting `undefined` for: both `engine.handlebars;` and `engine.Handlebars;`

Looking through `engine-assemble` and subsequently `engine-handlebars`, I can see that you are exposing Handlebars on `engine`.  However, it's not coming through in `assemble.getEngine('.hbs');`

In fact - just to test, I use:

```
var assemble = require('assemble');
var engine = assemble.getEngine('.hbs');
var handlebars = engine.Handlebars; // results in undefined
console.log(engine.compile.toString());
```

And my output reflects the compile method from `engine-cache` instead of what I'd expect from `engine-assemble`.

So - digging into `engine-cache` it looks like the expected `engine.Handlebars` gets dropped in `Engines.prototype.setEngine` lines 61-70.

Does that make sense?

**Comment by jonschlinkert** [comment]
> it looks like the expected `engine.Handlebars` gets dropped 

Hmm, @doowb or I can take a look and see what's happening there

would you mind doing `console.log(assemble.engines)` to see if the engine is even registered? might be registered without a `.`, but you shouldn't have to account for that, it should be added automatically

**Comment by jonschlinkert** [comment]
thanks for all of the detail, should make it a lot easier to figure out!

**Comment by avr** [comment]
Thanks, Jon.  It looks like I didn't have it quite right - it looks like things are happening between `Template.prototype.engine` and `Template.prototype.registerEngine`.  Here's some more troubleshooting.

```
var assemble = require('assemble');
console.log(assemble.engines);
```

returns:

```
{ '.md':
   { render: [Function],
     renderSync: [Function],
     compile: [Function],
     options: { layoutDelims: [Object], destExt: '.html' },
     helpers: {},
     name: 'render' },
  '.hbs':
   { render: [Function],
     renderSync: [Function],
     compile: [Function],
     options: { layoutDelims: [Object], destExt: '.html' },
     helpers: {},
     name: 'render' },
  '.*':
   { render: [Function],
     compile: [Function],
     options: {},
     helpers: {},
     name: 'noop',
     renderSync: [Function] } }
```

If I add `console.log(exts, fn);` to line 667 of  `Template.prototype.engine` I get the `engine-assemble` object.  Later in that function, Template calls `this.registerEngine`.  If I `console.log(ext, fn);` on line 641 of `Template.prototype.registerEngine` - I get the following (AKA - the dropped engine.Handlebars):

```
md function (path, options, callback) {
    options.filename = path;
    exports.readPartials(path, options, function (err) {
      if (err) {
        return callback(err);
      }
      if (exports.cache(options)) {
        exports[name].render('', options, callback);
      } else {
        read(path, options, function (err, str) {
          if (err) {
            return callback(err);
          }
          exports[name].render(str, options, callback);
        });
      }
    });
  }
hbs function (path, options, callback) {
    options.filename = path;
    exports.readPartials(path, options, function (err) {
      if (err) {
        return callback(err);
      }
      if (exports.cache(options)) {
        exports[name].render('', options, callback);
      } else {
        read(path, options, function (err, str) {
          if (err) {
            return callback(err);
          }
          exports[name].render(str, options, callback);
        });
      }
    });
  }
* function noop(str, opts, cb) {
    cb(null,  str);
  }
```

**Comment by avr** [comment]
Also - maybe a dumb question - but how do I see the output of Template's `debug.engine('engine %j:', exts);`?

**Comment by jonschlinkert** [comment]
hmm, @doowb just mentioned that the cause might be in engine-cache, where we do something like `fn.render || fn`. I need to look, but if that is how the code is setup and `fn.render` is used, obviously that would mean that the other methods aren't getting passed on. just wanted to mention this until I have a chance to look in a bit. 

> how do I see the output of Template's debug.engine('engine %j:', exts);?

totally not a dumb question, don't ever worry about that with us. I have a hard time understanding my own code sometimes lol. 

The `debug` statements are from [debug](https://github.com/visionmedia/debug). I created namespaces to make it easy to drill down to specific areas of the app.  

I created [some docs](https://github.com/jonschlinkert/template/tree/0.13.0#debugging) on the 0.13.0 branch of Template to answer the question. 

All of the available [namespaces are here](https://github.com/jonschlinkert/template/blob/master/lib/debug.js#L38-L50)

**Comment by avr** [comment]
Thanks for your help.  I'm not sure how I got down the rabbit hole in my comment above.  But - I've updated my Assemble file and everything is correct up until the `engine-cache` bit.  @doowb is definitely right about that `fn.render || fn` line.  I've also reworked my templates to get rid of the need for `handlebars-layouts`.

As always, thanks for your help.

**Comment by jonschlinkert** [comment]
:+1:

**Comment by shannonmoeller** [comment]
@avr @jonschlinkert I'll be updating `handlebars-layous` to support the Assemble 0.6.0 way of doing things. I just need to figure out the best way to do that as I'd like to avoid breaking the current pattern.

shannonmoeller/handlebars-layouts#15

**Comment by jonschlinkert** [comment]
@shannonmoeller I'll post an answer on shannonmoeller/handlebars-layouts#15
