### ISSUE TITLE
Warning: Missing helper: 'is' Use --force to continue.

### ISSUE THREAD

**Issue by ANTON072** [assemble/assemble#684]
The helper 'is' dose not work now. 

```
<li><a href="#"{{#is active "fuga"}} class="rc-h-active"{{/is}}>hogehoge</a></li>
```

assemble version is `"assemble": "^0.4.42"`.

It was working to this before. Why not working?

**Comment by jonschlinkert** [comment]
Can you recreate this issue on the handlebars-helpers repo? thanks

**Comment by ANTON072** [comment]
Sure .thanks.
