### ISSUE TITLE
v0.6.0 Merge YAML In Layouts

### ISSUE THREAD

**Issue by avr** [assemble/assemble#686]
I may have things set up wrong, but I can't seem to read YAML from my layouts.

Based on #681 and #685, I'm guessing I don't completely understand how context's are merged.

Is context from layouts (from `assemble.layouts`) available or does that need to be added somehow via the `mergeContext` option?

**Comment by jonschlinkert** [comment]
> Based on #681 and #685

No, neither of those are related to this. same with `mergeContext`.  685 is just a misunderstanding of how helpers work - the markdown helper in particular.

The layout data isn't exposed on the context yet for v0.6.0. It's definitely going to be implemented though. The main work for it has already been done. I'll update here when it's pushed up

**Comment by avr** [comment]
Great - thanks.

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of assemble and should be resolved now - and/or possible to do with custom middleware or plugins
