### ISSUE TITLE
v0.6.0 Template-Utils

### ISSUE THREAD

**Issue by vwochnik** [assemble/assemble#688]
Hey @jonschlinkert 

As you said in the last PR, it would be helpful to 'outsource' a couple utility functions such as the `getName()` function for getting the collection of the current task. It would also be very helpful outsourcing the `renameKey || default` construct. In my plugin I still have to check whether `renameKey` was set and use that or the default which I also have to provide.

* `getTemplateKey()`: Gets template key based on filename
* `getTaskCollection()`: Gets template collection for current task

Now this is just an idea but why not provide a function that does both meaning `retrieve` and `insert` templates into the current task collection so that I as a plugin developer do not have to worry about inserting the right keys into the right collections. I can put templates into the task and push them into the pipe (`toVinyl()`) and I can also retrieve Templates based on a key via `getTaskCollection()[key]` or a filename via `retrieveTaskTemplate(fp)`.

* `retrieveTaskTemplate()`: retrieves template by a filename (glob) from the current task collection.
* `insertTaskTemplate()`: insertes template into the task collection by `template.path` so that I as a developer do not have to worry about choosing the right collection/key.

**Comment by jonschlinkert** [comment]
good ideas. `renameKey` is fairly pervasively used throughout assemble and related libs. I'm not sure what you mean about checking to see if it was set, it might be that there is a problem that needs to be fixed. 

> why not provide a function that does both meaning retrieve and insert templates into the current task collection

interesting idea. currently I'm [doing this](https://github.com/assemble/verb/blob/refactor/index.js#L199) in verb. which is then used in plugins [like this](https://github.com/assemble/verb/blob/refactor/lib/plugins/init.js#L9-L14) and [again here](https://github.com/assemble/verb/blob/refactor/lib/plugins/init.js#L30). I love the idea of generalizing code wherever possible, as long as the abstraction doesn't end up creating more distance from what's actually happening in the code. If we can figure out a clean way to do that I'd love to do this. 

> insertes template into the task collection by template.path so that I as a developer do not have to worry about choosing the right collection/key.

To clarify, do you mean something [along these lines](https://github.com/assemble/verb/blob/refactor/lib/plugins/init.js#L33-L56)?

**Comment by jonschlinkert** [comment]
and thank you! also want to let you and others know that I'll be on vacation starting this morning (in about 2 hours :) and I'll be back on GitHub on Friday the 17th. wish there was a built-in way of letting people know this kind of thing on github...

**Comment by vwochnik** [comment]
With `renameKey`, I mean this:

```js
function getTemplateKey(fp) {
  var renameKey = assemble.option('renameKey') || function(fp) {
    return path.basename(fp, path.extname(fp));
  };

  return renameKey(fp);
}
```

Because that has to be checked and I as a plugin dev don't want to 'copy' this code since it's already there in `template-render`. Should be all put into this function.

* `getTask()` from `verb` looks good, however, I meant `getTaskCollection()` which in itself gets the task first and then retrieves the related collection for that task.

> to clarify ...

No, I mean this

```js
var template = /* my generated template from collection or whatever */;
// which does what my plugin does with `getName()`>plural>key>assign
assemble.insertTemplateIntoCurrentTaskCollection(template);
this.push(tutils.toVinyl(template));
```

**Comment by vwochnik** [comment]
Since sometimes you just want to insert a template into the current task collection to be used later. The function looks up the task collection and template key and then inserts the template into the corresponding collection.

**Comment by jonschlinkert** [comment]
> No, I mean this

I might be missing something, but I think that's what I'm doing. A [loader is created](https://github.com/assemble/verb/blob/refactor/lib/loaders/task.js) using the name of the task. So a custom template collection is created just for that task.  [then here is where the template is loaded](https://github.com/assemble/verb/blob/refactor/lib/plugins/init.js#L27) onto that collection. `id` is just the task name. This is more composable IMO. 

Then below I'm using [this line](Because that has to be checked and I as a plugin dev don't want to 'copy' this code since it's already there) to get that same collection off of the cache. The `pushToStream` function is already in template-utils, but I wanted to customize it.

> Because that has to be checked and I as a plugin dev don't want to 'copy' this code since it's already there

I see what you mean now, but that example you gave is the only place I can think of where that would be used. I think it could be useful, but since `renameKey` can be defined more than once on more than just global options it also seems like it could cause more problems.

**Comment by vwochnik** [comment]
This is nice!

OK, from my understanding you want to implement `assemble.gettask()` first which can then be used by plugins in the way you have described. Sounds great!

Now, following code assumes that I'm loading a `vinyl` file into the collection which I am not. I'm adding a template to the collection which THEN needs to be added to the stream.

```js
// Convert vinyl file to verb template and add to collection
verb[id](file);
```

```js
var assemble = this, id = assemble.gettask();

// somewhere in the through2 push callback
var template = /* my PAGE template that needs to be rendered (not a vinyl file) */
//TODO add to current task template collection ->assemble[id] ?
//TODO push template to stream (convert to vinyl)
```

IMO, the `pushToStream()` function works on a collection, however, I only want this ONE template to be pushed.

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of assemble and is no longer relevant
