### ISSUE TITLE
v0.6.0 merging partials with the same basename

### ISSUE THREAD

**Issue by Melindrea** [assemble/assemble#689]
So, I just realised that if I have the partial `a.hbs` and `b/a.hbs` these are merged into the same partial, `a` (when using `this.app.getPartial(…)`).

Is that intended behaviour? To me, it would be a lot more useful if I could have the same name and differentiate between them based on the folder structure.

**Comment by vwochnik** [comment]
Yes, this is intended since all files are being organized by `keys` and in this case the `key` is the `basename` without file extension. So you have two `a` properties in the `partials` collection which of course doesn't work.

To make it work, insert this code into your `assemblefile.js`:

```js
assemble.option('renameKey', function (fp) {
  var dirname = path.dirname(fp);
  var basename = path.basename(fp);
  var last = path.basename(dirname);
  return path.join(last, basename);
});
```

This will not only take the `basename` of the file but also the name of the last directory.

**Comment by Melindrea** [comment]
And that would only rename the *partials*? (I am not interested in 
changing how my layouts or pages are named)

**Comment by vwochnik** [comment]
I have no idea to be honest. Maybe you have to use loaders but I'm not familiar with it. @jonschlinkert's on holidays so maybe @doowb can give you more details.

**Comment by Melindrea** [comment]
I'll just need to fake the dirs for the moment, I guess. I'm planning on using the same templates repo for all/most of my sites, but some partials and layouts need to be more unique, so I figured I could just pop them into `site1/partial.hbs` and `site2/partial.hbs`, but I'll go with `site1/site1-partial.hbs`, at least for now.

**Comment by vwochnik** [comment]
If you really think that your partials have some added value to make them across multiple sites, you can use something similar to initialize these partials separately from your repository.

```js
// index.js
'use strict';

var path = require('path');

module.exports = function(assemble) {
    // add partials to given assemble instance
    assemble.partials(path.join(__dirname, 'partials', '*.hbs'));
};
```

Now just make a `node.js` package out of it and then in your sites you can require it like so:

```js
var assemble = require('assemble');

// add great partials
require('my-great-partial-module')(assemble);
```

**Comment by Melindrea** [comment]
That's the eventual plan, but for now I'm wanting a simpler solution, which is submodules =)

**Comment by vwochnik** [comment]
The solution I presented IS based on submodules! Just create a package `npm init` and then use it. You can globally install it on your system or publish it via `npm publish` and then `npm install` it before `require()`ing it.

**Comment by Melindrea** [comment]
git submodules, not NPM based. Thank you, but it's not the solution I am looking for at the moment
