### ISSUE TITLE
{{eachIndex}} helper: difference between docs & function

### ISSUE THREAD

**Issue by chaenu** [assemble/assemble#692]
Hey,

first of all, thank you for your fantastic static site generator!

I've notice a discrepancy between the docs and the engine. There's an example in the docs (http://assemble.io/helpers/helpers-collections.html) for the `{{eachIndex}}` helper. But if you implement the example with
```handlebars
{{#eachIndex collection}}
  {{this}} is {{index}}
{{/eachIndex}}
```
the output is:
```
[object Object] is 0 [object Object] is 1 [object Object] is 2
```

For the desired output, you have to switch `{{this}}` to `{{item}}`
```handlebars
{{#eachIndex collection}}
  {{item}} is {{index}}
{{/eachIndex}}
```
which outputs
```
Professor Farnsworth is 0 Fry is 1 Bend is 2
```

Is this only an error in the docs? In my opinion, the solution described in the docs is more coherent, as the {{each}} helper uses {{this}} too.

**Comment by jonschlinkert** [comment]
moved the handlebars-helpers repo
