### ISSUE TITLE
Add Project from Oct 22, 2004 semjs.org talk as an example

### ISSUE THREAD

**Issue by brandonmerritt** [assemble/assemble#693]
I've been trying to learn the 0.6.0 release by watching the video https://www.youtube.com/watch?v=R9kOy2e5koE. Was wondering if there was a way to add it as an example/boilerplate/recipe for 0.6.0. It would be great if I could follow along.

**Comment by jonschlinkert** [comment]
there are better examples in the works that we'll be adding to the assemble/assemble.io repo. since this is documentation/examples related, I'm going to close for now but I'll try to remember to link to info when completed
