### ISSUE TITLE
@index in #each is now empty

### ISSUE THREAD

**Issue by dudewad** [assemble/assemble#694]
I've spent several hours trying to debug why my code has stopped outputting the @index. Thought it was a bug of mine at first - but then I realized I had recently pulled code that was working to a new machine, and downloaded the latest node, as well as the latest version of Assemble.

I then tried pulling another project that prints the @index, and using the same node version and assemble version found that it too is not outputting @index. 

Lastly, i created a net new project, and am using this code in my partial:

<section>
    {{#each items}}
        Index: {{@index}}
    {{/each}}
</section>

Thats it. The output outputs the word "Index:" with no trailing numeric value as you would expect for a data file containing an array of five objects

Am I missing something? Can anyone repro this?

I rolled node back to 0.10.34 and am using assemble v 0.4.42.
I have tried any combination of node 0.10.34->current as well as assemble 0.4.0 -> current. Could this be something else?

**Comment by akileez** [comment]
missing the `@` in the partial code
```handlebars
{{#each items}}
Index: {{@index}}
{{/each}}
```
if this is what you meant but just have a typo then I am not sure what the issue may be.

**Comment by dudewad** [comment]
Yep, this is a typo - I have the @ in there. Like I mentioned, it grounded a fully functional project that has been working for months.
Any other ideas? Are you able to repro this?

**Comment by dudewad** [comment]
I edited my original post with the correct code. Sorry, too much time troubleshooting this issue, got me frazzled.

**Comment by akileez** [comment]
not sure what the issue may be. I see u are using assemble 0.4 branch. I haven't used that in months ... only using the 0.6 branch. I am aware that the 0.4 branch started using handlebars 3.0.1 ([assemble-engine](https://github.com/assemble/assemble-handlebars)). you can try pulling down assemble-engine v2.3 then reinstalling assemble to see if that clears the problem. 

I have no assemble/grunt setups where I can test the 0.4 branch any longer. if you have a test repo, I can look further but I think rolling back the assemble-engine should do the trick for you.

**Comment by doowb** [comment]
Thanks @akileez I was just about to suggest that. I think there are more issues with upgrading to handlebars 3 than we expected.

**Comment by dudewad** [comment]
Let me try that. Are you using the latest node version? I'm win8.1 x64 (FYI)

**Comment by dudewad** [comment]
@doowb when did the handlebars 3 upgrade happen? Just curious. I just switched to a new machine and havent upgraded my installs for several months, so I'm not incredibly surprised that there are issues. I've just been having a hell of a time figuring out whether this is a node, grunt, or assemble issue.

**Comment by doowb** [comment]
It was just a few days ago

**Comment by doowb** [comment]
I just created a new project with just grunt and assemble using the latest repos and it seems to be working okay:

```handlebars
---
title: Home
items:
 - one
 - two
 - three
---
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{title}}</title>
</head>
<body>
  <h3>{{title}}</h3>
  <ul>
    {{#each items}}
      <li>{{@index}} - {{.}}</li>
    {{/each}}
  </ul>
</body>
</html>
```

renders to this:

```html

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Home</title>
</head>
<body>
  <h3>Home</h3>
  <ul>
      <li>0 - one</li>
      <li>1 - two</li>
      <li>2 - three</li>
  </ul>
</body>
</html>
```

**Comment by doowb** [comment]
I don't have a window machine to test on right now and I'm on node v0.12.0.

**Comment by doowb** [comment]
Try running `npm ls` in the project directory to see if there's something else missing.

**Comment by dudewad** [comment]
Great, I didn't get a chance to test this yet but I will be doing it right now. Thanks for running the test!

**Comment by dudewad** [comment]
Sorry, is there a way i can get you to explain how to install assemble 0.4.x but also downgrade to the 2.3 engine? Thats the part I'm a little hazy on.
Thanks

**Comment by dudewad** [comment]
I'm runnin npm install assemble@0.4.14

**Comment by akileez** [comment]
first...
```bash
npm uninstall assemble
```
then 
```bash
npm install --save assemble-engine@2.3.0
npm install --save assemble # whatever version you want
```
this will install assemble-engine first. when you install assemble proper, it will recognize that you already have assemble-engine installed and will not download it as part of the assemble dependency. `--save` is optional of course.

**Comment by akileez** [comment]
version updated... i have a typo.

**Comment by dudewad** [comment]
ok thats what I thought, however I'm getting an error when trying to install the assemble engine that it doesnt exist in the npm registry. I'm running --save-dev:
npm install --save-dev assemble-engine@2.3.0

[...other stuff...]
npm ERR! 404 Not Found: assemble-engine
npm ERR! 404
npm ERR! 404 'assemble-engine' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'intel-pattern-library'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by akileez** [comment]
yeah, it should be `npm install assemble-engine@0.2.3`

**Comment by dudewad** [comment]
Yep, same error still. Says its  not in the npm registry. Could it be a proxy issue or something (I'm at Fluent conf right now on conference wifi)..?
Though, I did try the same command yesterday at my airbnb and had the same response so I doubt its that.

**Comment by dudewad** [comment]
For the record, assemble-engine doesn't come up in npmsearch:
https://www.npmjs.com/search?q=assemble-engine

**Comment by akileez** [comment]
doh! sorry... my fault.
`npm install assemble-handlebars@0.2.3`

I got version 0.6.0 on the brain.

**Comment by dudewad** [comment]
ahhhh! okay let me give this a shot. Thanks :)

**Comment by dudewad** [comment]
IT WORKED. THANK YOU.
Okay, so this has officially fixed this bug, and you have officially solved my problem. I *really appreciate* you going back and forth with me this quickly. 

My suggestion out of this is, perhaps you guys roll the assemble 0.4.x engines back until you've done further testing, and implement the 3.x handlebars engine into the 0.6.x builds. I don't know that that's feasible, and it's not a huge surprise that you wouldn't have seen this bug until now because it requires a fresh install. But, out of the box, on a fresh machine, if you run npm install assemble, it appears that the @index will come up empty.

Thank you thank you thank you.
--Layton

**Comment by jonschlinkert** [comment]
> For the record, assemble-engine doesn't come up in npmsearch:

it should be `engine-assemble`

**Comment by dudewad** [comment]
Indeed it is. Thanks!

**Comment by akileez** [comment]
@jonschlinkert. actually it was assemble-handlebars. The mixup was mine. I was combining `assemble-handlebars` and `engine-assemble` and come up with `assemble-engine`. totally on me.

**Comment by jonschlinkert** [comment]
oh, and nvm he meant assemble-handlebars I think... but you guys already resolved that! thanks @akileez and to @dudewad for reporting the issue and helping us figure it out

**Comment by jonschlinkert** [comment]
lol

**Comment by dudewad** [comment]
Glad to help, hope to contribute more in the future (you can close this issue now btw)

**Comment by jonschlinkert** [comment]
:+1:

**Comment by ryuran** [comment]
Resolve an issue by downgrade version :(.
This means it will not work in future ?

**Comment by dudewad** [comment]
For now, potentially. I don't know if this has been fixed since this was almost a year ago. @jonschlinkert off the top of your head has this issue been addressed?

**Comment by jonschlinkert** [comment]
well, since assemble no longer has any built in helpers at all I would suggest we move the discussion to the handlebars-helpers repo. if we do move the discussion to that repo, please look at the dev branch, it's 100+ commits ahead of master. 

also, a helper like this is pretty generic and doesn't really rely on any assemble-specific code, so anyone who has handlebars or javascript knowledge might be able to help out if @doowb or I don't get to it first.
