### ISSUE TITLE
Pages not rendering in {{#each pages }} in 0.6.0

### ISSUE THREAD

**Issue by brandonmerritt** [assemble/assemble#696]
I am trying to gather up all my pages and output them as a unordered list.

```
{{#each pages }}
<li>{{basename }}</li>
{{/each}}
```
I thought I was following 0.6.0 methodology by defining my pages in my task:

```
gulp.task('assemble', function () {
    assemble.pages('./src/hbs/components/**/*.hbs');
    assemble.layouts('./templates/layouts/*.hbs');
    assemble.option({
        layout: 'default'
    });

    gulp.src(paths.sources.pages)
        .pipe(gulpAssemble(assemble))
        .pipe(prettify())
        .pipe(extname())
        .pipe(gulp.dest(paths.build.www));
});
```
I've tried a few diff variations, but I'm not getting anywhere. Can you point me to a project or provide some feedback re: what might need to change?

**Comment by ChivPoint** [comment]
show prettify()

**Comment by jonschlinkert** [comment]
please reopen on gulp-assemble, thanks
