### ISSUE TITLE
Assemble docs out of date

### ISSUE THREAD

**Issue by foxx** [assemble/assemble#701]
None of the development docs shown [here][1] seem to match up with the 0.6.0 branch. I've wasted around 3 hours of debugging just trying to figure out what works and what doesn't due to inaccurate documentation.

From what I can tell, a whole bunch of stuff was changed since 0.4.0 (which is what the docs were based on?). There needs to be some better warnings to explain what docs relate to what versions, because this is a cluster of mess :(

[1]: http://assemble.io/docs/Methods.html

**Comment by jonschlinkert** [comment]
wrong repo.

**Comment by foxx** [comment]
This isn't the wrong repo, this relates directly to the assemble project. This is still a valid bug report but tbh, given your response on the other issues, I'm not going to even bother helping out here.
