### ISSUE TITLE
@index and @first no longer working

### ISSUE THREAD

**Issue by adriaanbalt** [assemble/assemble#702]
I was using Handlebars @index and @first and suddenly they stopped working after I reinstalled my node modules.  Is anyone else having this problem?

**Comment by jonschlinkert** [comment]
it's related to updating handlebars in a dependency. we've had a few issues reported, we might need to do another patch, but I haven't had a chance to look into it yet if anyone has suggestions/PR

**Comment by mikepeino** [comment]
I am also experiencing this in one of my projects.

**Comment by jonschlinkert** [comment]
closing since this is a handlebars helper issue. we can address this in the next release of handlebars-helpers
