### ISSUE TITLE
[v0.6.0] Loading single layout from Filesystem

### ISSUE THREAD

**Issue by ub1quit33** [assemble/assemble#705]
I feel like I am doing something very wrong, as I am finding myself having a lot of difficulty with setting up a workflow which seems like should be simple to establish.

I am trying to keep my content in Markdown pages and render those pages using a layout (a JSON template in this case). Each glob of src files will be sharing the same layout, so I only need to load one layout per task. I reviewed #614, which gave me insight into how a glob of src files can share a template, but my problem at this point is being more or less befuddled by the templates API. Is there a way to load a single template from the filesystem?

`assemble.layout` seems to only work with inline templates (I even tried substituting a string with a call to fs.readFileSync(), which left me with a steaming pile of stacktrace), and `assemble.layouts`, as far as I can tell, is intended for loading in templates by the glob. Even then, damned if I know how those templates have their keys assigned to them.

I'll take any knowledge I can get at this point, since I am sorely lacking in understanding right now. Thanks in advance for any help or pointers.

**Comment by jonschlinkert** [comment]
the title says that you want to load a single layout from the fs, but then you say you want to load layouts from JSON, and you want to use those to wrap markdown content (which would also need to be processed and rendered to HTML). 


> assemble.layout seems to only work with inline templates

The example on the readme doesn't work, e.g. when you do the following are you getting errors?:

```js
assemble.layout('templates/*.hbs');
// or
assemble.layouts('templates/*.hbs');
````

**Comment by ub1quit33** [comment]
Sorry for the lack of clarity... I was quite bleary eyed at the time I wrote this. To give an example of how I did this in 0.4.x:

```js
{
  assemble: {
    options: {
      // Global stuff..
    },
    posts_content: {
      options: {
        ext: '.json',
        layout: 'src/content/posts/template.hbs',
      },
      expand: true,
      cwd: 'src/content',
      src: 'posts/*.md',
      dest: 'build/'
    };
  };
};
```

Then the file `src/content/posts/template.hbs` was something like:

```json
{
  "title": "{{title}}",
  "content": "{{#markdown}}{{>page}}{{/markdown}}"
}
```
Where the `{{#markdown}}` blog was replaced by a custom helper which rendered the content as a JSON suitable string. I am essentially trying to replicate this workflow in 0.6.0 (It does not take over the name from assemble's builtin markdown block helper-- I just use the standard name here for clarity).

> The example on the readme doesn't work, e.g. when you do the following are you getting errors?

Loading layouts by the glob is not suitable for what I'm trying to do, since I'm only trying to pull in one per set of src files. I have tried the following

```js
 assemble.layout('src/content/posts/template.hbs');
 assemble.task('posts_content', function(){
    assemble.src('src/content/posts/*.md', {layout: 'src/content/posts/template.hbs'})
      .pipe(assemble.dest('build/posts'));
    });
```
With the following `src/content/posts/template.hbs`
```json
{
    "title": "{{title}}",
    "content" : "{{#markdown}}{% body %}{{/markdown}}"
}
```

What I end up with is basically the source markdown files copied from src to dest, with the YFM having been stripped from the content. The markdown does not appear in its layout, and no rendering is done. When I build using the following configuration however

```js
 assemble.layout('posts', '{{#markdown}}{% page %}{{/markdown}}');
 assemble.task('posts_content', function(){
    assemble.src('src/content/posts/*.md', {layout: 'posts'})
      .pipe(assemble.dest('build/posts'));
    });
```

I get a rendered HTML page, just as expected. I just can't seem to figure out how to substitute the inline layout for a path to my `template.hbs` file.

**Comment by vwochnik** [comment]
Why so complicated? Why not simply use this?

```js
assemble.layouts('src/layouts/*.hbs');
```

Then you'd only have to place `post.hbs` inside the `src/layouts` directory and use `{layout: 'post'}`. This is much simpler accomplished this way.

**Comment by ub1quit33** [comment]
> Why so complicated?

I don't think there's anything fundamentally complicated about what I was trying to do

> Why not simply use this?

Thanks for your suggestion! Based on your example, I've figured out what I'm doing wrong, and now I can render my content the way I expect to. I feel silly because I couldn't seem to figure out that the layout 'name' is simply the filename with the extension stripped... but now that my confusion has been cleared up, I should be able to take off running from here.

Thanks everyone! I'll come crawling back if I run into anymore mental road blocks ;)

**Comment by ub1quit33** [comment]
Actually before I close this out completely, I do have one more question regarding the templates API, as I foresee this being a snag I will run into...

Since the direction I am ultimately going is to maitain multiple types of content (e.g., 'posts' and 'docs'), and to be able to have a few different layout types for each content type (e.g., 'base.hbs' to render as normal content, 'atom.hbs' to render an RSS feed of the content, 'index.hbs' to render an index of the content), I figured that based on the suggestion of @vwochnik, I would be best off reorganizing my layouts something like:

- Base layout: `src/content/layouts/base/*.hbs`
- Feeds: `src/content/layouts/atom/*.hbs`
- Indeces: `src/content/layouts/indeces/*.hbs`

Where the glob is replaces by the content type. e.g., 'post.hbs' or 'doc.hbs'. The problem I foresee is colliding template names within the templates collection, as this would load three templates named 'post' and three templates named 'doc'. I figured the proper way to work around this would be to create a collection for each layout type, e.g.,

```js
assemble.create('base', { isLayout: true });
assemble.create('atom', { isLayout: true });
assemble.create('index', 'indeces', { isLayout: true });
```
And then add the respective templates
```js
assemble.bases('src/content/layouts/base/*.hbs');
assemble.atoms('src/content/layouts/atom/*.hbs');
assemble.indeces('src/content/layouts/indeces/*.hbs');
```
Looks cool to me so far! Where I'm having a disconnect is in how I would pass a template from a specific collection to `assemble.src`. As far as I can glean, the only available optoion ther is `{ layout: myLayoutName }`, which searches all collections which specify `isLayout`. Is that understandinf correct? Can anyone give me pointers on how I might specify a layout from a specific collection to pass to `assemble.src`?

**Comment by jonschlinkert** [comment]
yeah that looks like a good start (and this is technically a separate issue, or more technically not an issue lol ;) 

keep in mind that `layouts` are "wrappers" for other template types. there are two other `types` of templates in assemble v0.6.0 that can be specified when you use the `.create()` method:

**examples**

`type`s are in code comments:

```js
// layout
assemble.create('foo', { isLayout: true });
// partial
assemble.create('bar', { isPartial: true });
// renderable
assemble.create('baz', { isRenderable: true });

// mix and match
assemble.create('quux', { isRenderable: true, isPartial });
```

**types**

- `layout`: defined with `isLayout`. Layouts are wrappers for other templates. any template can use layouts. 
- `partial`: defined with `isPartial`. Partials, or "partial views" are the inverse of layouts. partials can be anything from buttons and navbars, to `<head>` and footer sections, or scripts
- `renderable`: defined with `isRenderable`. You can think of renderable templates as having a one-to-one relationship with what an end user might expect to view, like a `post` or `page`, or a `doc`

You can define more than one type, but if you're building a massive project and speed is a concern, try to define only one.

**What they do**

Each type gets special methods, helpers, or processing treatment from assemble. For example, when you pass a template name to the `.render()` method, assemble will only search the renderable views to find the name that was passed. When you specify a layout, assemble only searches for templates defined as layouts, etc...

hope this helps!
