### ISSUE TITLE
Sort Order w/ {{pager}} helper

### ISSUE THREAD

**Issue by firelite** [assemble/assemble#707]
By default, 'next' descends down alphabetically and 'prev' ascends up.  How do you set a specific sort order for the next/prev pagination helper? 

Any help would be great!

**Comment by jonschlinkert** [comment]
closing since pagination and collections are completely different in 0.6.0, and will be handled by plugins like [templates-indexer](https://github.com/doowb/templates-indexer) and [paginationator](https://github.com/doowb/paginationator) (loooove that name lol)
