### ISSUE TITLE
Are nested partials possible?

### ISSUE THREAD

**Issue by Nooshu** [assemble/assemble#708]
Hello,
I've been looking around the 'net / github issues on the best way to handle this problem. Essentially I want to create a modal window partial which can be re-used where the content inside can be different. That way if the modal functionality needs to be tweaked, I only need to modify it in one location, not across multiple pages

```
// Include the base modal window HTML in a page
{{> modal_window_functionality }}

// Content set one needs to go inside the above partial on one page
{{> modal_window_content_1 }}

// Content set two needs to go inside the above partial on another page
{{> modal_window_content_2 }}
```

Is there any way to handle this in a modular pattern? Or is it a case of just repeating the modal window wrapper functionality across multiple pages then include the content partial inside this?

Any input would be great, i've been racking my brain on how best to handle this.

Thanks!

**Comment by jonschlinkert** [comment]
this is totally possible using [helpers](http://handlebarsjs.com/expressions.html) or using subexpressions in partial expressions. best place to get help for template-engine related questions is on the engine's docs (handlebars in this case) or stackoverflow.
