### ISSUE TITLE
Markdown indentation

### ISSUE THREAD

**Issue by thedamon** [assemble/assemble#709]
Within a `{{#markdown}}` block I have the following code (including the opening and closing 3 backticks)

```javascript
var sitename = sitename || {}

sitename.setup = function setup(){
	//...codez
}
```

the first line is fine, but the following lines all have 3 tabs inserted in front of them. None of my markdown is indented so I'm not sure where this is coming from. It may not be an issue with assemble, but I thought I would raise it here in case it is!

**Comment by jonschlinkert** [comment]
hmm, it's most likely related to handlebars formatting. there are options for whitespace handling with handlebars, have you looked into that?

**Comment by jonschlinkert** [comment]
closing due to age and lack of follow up
