### ISSUE TITLE
Publish versions to npm

### ISSUE THREAD

**Issue by ryanve** [assemble/assemble#710]
Please publish 0.5.0 and 0.6.0 and any other versions to npm. It's hard to use assemble when the latest [on npm](https://www.npmjs.com/package/assemble) is 0.4.42 and same for the [tagged releases](https://github.com/assemble/assemble/releases).

**Comment by doowb** [comment]
`0.5.0` has been skipped and `0.6.0` is published as `@beta` on npm. You can use it just by doing `npm i assemble@beta -D`. Once we feel assemble 0.6.0 is ready, we'll publish it as latest.

**Comment by ryanve** [comment]
Does the beta change? I want to depend on a specific version and not worry that updates made by the assemble team don't break my app. Why not publish prereleases like `0.6.0-1` or `0.6.0-beta` or just release 0.6.0 and release later 0.6.x or 0.7.x as applicable using [semver](http://semver.org)?

**Comment by doowb** [comment]
> Why not publish prereleases like 0.6.0-1 or 0.6.0-beta

They're already published (`npm show assemble`):

![image](https://cloud.githubusercontent.com/assets/995160/7595353/74cd72a8-f8b4-11e4-926e-242a34ab514c.png)
