### ISSUE TITLE
Skip the current page in tags>pages collection?

### ISSUE THREAD

**Issue by gera446** [assemble/assemble#711]
I have a tags collection.

```handlebars
{{#tags}}
  {{#is tag "nature"}}
    {{#each  pages }}
      Working with data
    {{/each}}
  {{/is}}
{{/tags}}
```

I want to skip the current page, is it possible?

**Comment by jonschlinkert** [comment]
this is a handlebars syntax question, probably best asked on stackoverflow or answered by the handlebars docs.
