### ISSUE TITLE
tests failed: nested property should exist

### ISSUE THREAD

**Issue by brennanMKE** [assemble/assemble#714]
I just cloned this repo and ran the following commands.

`npm i -d && npm test`

It showed that 2 of the tests failed. (see screenshot below)

![failed tests](https://cloud.githubusercontent.com/assets/277419/7819512/2187a814-0397-11e5-8693-12a9d5ad8700.png)

**Comment by jonschlinkert** [comment]
hi @brennanMKE, which branch did you use?

**Comment by brennanMKE** [comment]
I cloned the one which appeared from main page for the repo which appears to be v0.6.0.

**Comment by brennanMKE** [comment]
I switched to master and now I see 17 passing tests with no failures.

**Comment by jonschlinkert** [comment]
ok, thanks for confirming. closing since it's not master. we get tests updated and passing on branches before merging with master
