### ISSUE TITLE
index pages for groups of pages

### ISSUE THREAD

**Issue by stefanwalther** [assemble/assemble#716]
Hi,

I am pretty far with my assemble implementation in several projects, but unfortunately I am struggling with a specific problem:

I am having several sections:

```bash
|--SectionA
|--SectionB
|----article-sectionB-1.md
|----article-sectionB-2.md
|--SectionC
|----article-sectionC-1.md
|----article-sectionC-2.md
|----article-sectionC-3.md
```
Now I need to have - on every page within a section - a list of articles of this section.
How would I do that - without generating data files an using ```assemble.data```??

Assume that I am having dozens of sections, so I need a fully automated solution.

Thx a lot!

Regards
Stefan

**Comment by jonschlinkert** [comment]
Hmm, I have a couple of ideas. How are you reading in the pages and sections? Are you using `assemble.pages()` or custom template types?

**Comment by jonschlinkert** [comment]
fyi I renamed the issue since the title didn't have anything to do with the question.

**Comment by stefanwalther** [comment]
Hi,

using pages was my first approach, but I never got it to work, my thinking was that using pages puts the collection of pages into the current context and then I can iterate through them ... But maybe I was missing something?

So I am currently using custom template types:

```js
assemble.task( 'pages', function () {
	assemble.src( cfg.pages.src )
		.pipe( debug() )
		.pipe( extname() )
		.pipe( assemble.dest( cfg.pages.dest ) );
} );
```

**Comment by jonschlinkert** [comment]
resolved in the pending release by [templates-indexer](https://github.com/doowb/templates-indexer)
