### ISSUE TITLE
Running gulp-plugins: Cannot read property 'dest' of undefined

### ISSUE THREAD

**Issue by stefanwalther** [assemble/assemble#717]
Doesn't matter which gulp-plugin I am running, I always get the same error:

```js
Cannot read property 'dest' of undefined

D:\Projects\Node.js\assemble\node_modules\gulp-util\lib\PluginError.js:114
    return '    ' + prop + ': ' + self[prop];
```

Example:
```js
var sitemap = require( 'gulp-sitemap' );
...
assemble.task( 'sitemap', function () {
	assemble.src( './../docs/**/*.md' )
		.pipe( sitemap( {siteUrl: 'http://www.foo.bar', fileName: 'sitemap.xml'} ) )
		.pipe( assemble.dest( './../' ) );
} );
```

Any ideas what I am doing wrong?

**Comment by jonschlinkert** [comment]
closing since this issue is addressed by other existing issues https://github.com/assemble/assemble/search?q=gulp-sitemap&type=Issues&utf8=%E2%9C%93.

**Comment by stefanwalther** [comment]
Just FYI.
I solved the problem by adding

`assemble.enable('minimal config');`

Followed your advice in #706 

Regards
Stefan

**Comment by stefanwalther** [comment]
Just realized one of the limitations, the middleware is not working anymore ...
