### ISSUE TITLE
Output doesn't contain what it should

### ISSUE THREAD

**Issue by marcinkrzeminski** [assemble/assemble#718]
Hi there Assemble people,

I'm willing to create documentation similar to Foundation with Assemble v0.6.0. Since it is possible to use any gulp plugin inside assemblefile.js I want to use this file as my main task runner because I preffer Gulp over Grunt personally. Unfortunately I cannot get this thing working properly. Here is my basic configuration. My plan is to use html with some markdown and handlebars:

src/includes/sidebar.html
```html
Sidebar content
````

src/layouts/default.html
````html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
</head>
<body>
    {{> "sidebar"}}

    {% body %}
</body>
</html>
````

src/pages/index.html
````html
---
layout: default
title: Hello world
---
# Hello world
````

assemblefile.js
````js
var assemble = require('assemble');

assemble.layouts('src/layouts/*.html');
assemble.partials('src/includes/*.html');

assemble.task('default', function() {
    assemble.src('src/pages/*.html')
        .pipe(assemble.dest('dist'));
});
```

When I run assemble from my command line I got this on the output:

dist/index.html
````html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
</head>
<body>
    {{> "sidebar"}}

    
# Hello world
</body>
</html>
````

Any ideas what I'm doing wrong here? Is it possible to have this working?

Any help highly appreciated.

**Comment by akileez** [comment]
change your extensions from `.html` to `.hbs`. the default engine is handlebars so its looking for `.hbs` or `.md` and maybe something else to render the file. you will probably have to use gulp-extname to change the extension back to `.html` (inserted right before `.pipe(assemble.dest())`

**Comment by jonschlinkert** [comment]
Since the `{{> "sidebar" }}` expression is still there, that tells me the template engine isn't even trying to render the templates - but the `{% body %}` tag is gone, so the layout renderer did try to find a layout for the file, but couldn't... 


Since engines are set to run on files with specific file extensions, try changing the file extensions for templates to `.hbs`.

**Comment by jonschlinkert** [comment]
lol

**Comment by akileez** [comment]
absolutely.

**Comment by jonschlinkert** [comment]
nice one, thanks @akileez!

**Comment by marcinkrzeminski** [comment]
I tried this already, but the on the output my file extension was .hbs instead of .html ;(.

**Comment by jonschlinkert** [comment]
> you will probably have to use gulp-extname to change the extension back to `.html`

this is all you have to do:

```js
var extname = require('gulp-extname');
assemble.task('default', function() {
    assemble.src('src/pages/*.hbs')
        .pipe(extname());
        .pipe(assemble.dest('dist'));
});
```

**Comment by marcinkrzeminski** [comment]
Daaaamn you are so fast, I need to work on my typing skills ;) Thanks for the feedback. Is there an engine on the market that will handle .html files (with some markdown, handlebars) on the input ?

**Comment by jonschlinkert** [comment]
markdown is a different beast... we want a template engine to actually resolve the variables in the string, but we also want a markdown renderer to convert the syntax to HTML.

Try this:

```js
assemble.engine(['html', 'md'], require('engine-assemble'));
```

Then wherever you're including markdown, try wrapping the content with:

```handlebars
{{#markdown}}
# Foo
> this is markdown
{{/markdown}}
```

If that doesn't seem idiomatic, do this:

First, create a layout named `markdown.html` or whatever you want, then add the following to the file.

```handlebars
---
layout: default
---
{{#markdown}}
{% body %}
{{/markdown}}
```

Next, in any file that has mostly markdown, just use `layout: markdown`.

**Comment by jonschlinkert** [comment]
fwiw, these little tricks work with any language, not just markdown. you could do the same to render LESS, minify CSS, convert from coffee to js, etc.  :)

**Comment by marcinkrzeminski** [comment]
Thank you guys for all those helpful tips. I'll try them soon. I guess when it comes to markdown I just want to use it for code snippets like Foundation people are using it.

**Comment by marcinkrzeminski** [comment]
one

**Comment by jonschlinkert** [comment]
you're very welcome! thanks for giving us feedback
