### ISSUE TITLE
npm install assemble

### ISSUE THREAD

**Issue by floriangosse** [assemble/assemble#719]
If I try to install the latest version of assemble I get version 0.4.42. So please tag your versions and upload them to npm.org.

By the way: Why I can't use grunt with version 0.6.0 ?

**Comment by floriangosse** [comment]
Really? Why you close the issue without an answer?

**Comment by jonschlinkert** [comment]
> If I try to install the latest version of assemble I get version 0.4.42. So please tag your versions and upload them to npm.org.

that's not a question

> Why I can't use grunt with version 0.6.0 ?

because it's not compatible

**Comment by jonschlinkert** [comment]
In the future, asking questions that sound more like questions and less like statements is more likely to get the results you want.
