### ISSUE TITLE
Documentation, examples & examples - I'd like to help ...

### ISSUE THREAD

**Issue by stefanwalther** [assemble/assemble#720]
@jonschlinkert: As you know I am following your projects, especially assemble and verb, for quite a while. But to be honest I am constantly nearly about to desperate, because I cannot figure out how to get assemble to work, just being very about new developments ... So I am nearly once a week just thinking: "Shouldn't I just give up with Assemble and move over to metalsmith, Jekyll or another tool ..."

I am not writing this because I am complaining, instead I want to help - just to ensure that other people don't get lost ...:

It seems that verb + assemble have reached a semi-stable state and having good examples - is beside having a good documentation - really key. So I am thinking of creating a set of examples using assemble:

* **Simple**  
A very basic assemble based documentation
  * Using some .md files
  * Some very basic templates & partials
* **The 80% solution**
  * Some templates + partials
  * using data to generate/configure parts of the page
  * Using handlebars more intensively
* **Full blown solution**
  * All of above
  * A page with blog entries
  * + articles
  * using custom middleware
  * including Lunr to search within the page

(Everything is just up to discuss).
What do you think? I'd take the initiative on that, but would certainly need your help to be in par of assemble's development and best practices.
We should certainly set up the "agenda" for the three solutions together ...

Regards
Stefan

**Comment by jonschlinkert** [comment]
@stefanwalther this would be great! We'd love to have your help! 

I would be willing to spend time with you and/or help you learn anything about assemble that will give you the information you need to accomplish what you outlined.  

Let me know what you think are next steps!

**Comment by jonschlinkert** [comment]
just wanted to follow up, I have some ideas for how to start getting docs updated quickly, I'll try to start working on it in the next day or two

**Comment by stefanwalther** [comment]
Me, too ... should be able to share some ideas tonight ...

**Comment by brandonmerritt** [comment]
I'm not sure what I can do, but I've been working with gulp, gulp-assemble and assemble for over a month or so and think I have just enough knowledge to be dangerous. If there's anything I can do to help (even if it's providing a "newbie" opinion on the documentation) let me know.

**Comment by jonschlinkert** [comment]
awesome! as a first step I'm thinking of moving all markdown docs back into assemble master. this should keep markdown docs close to the source and make it easier to contribute. and I'll probably wipe out the docs directory and start with clean docs. we can use a build step to generate and copy the html/css/assets over to the assemble.io repo. 

thoughts?

**Comment by brandonmerritt** [comment]
To clarify, would the 0.6.0 branch have a docs folder? I would have been unable to use 0.6.0 if I didn't have access to what's currently there. It would be frustrating to have to switch to the master branch to find the docs (or figure out that's where they are in the first place).

**Comment by jonschlinkert** [comment]
> To clarify, would the 0.6.0 branch have a docs folder? I would have been unable to use 0.6.0 if I didn't have access to what's currently there

yeah I won't actually delete any docs, docs will be kept on the branch that they are written for.

**Comment by stefanwalther** [comment]
Hi, here we go, my first draft, now starting to work on the basic example:

https://github.com/stefanwalther/assemble-samples/tree/master/doc

**Comment by brandonmerritt** [comment]
@stefanwalther I wish I had something like this a couple of months ago! I would argue that breaking things into basic, novice, advanced might be less useful than breaking things into the components necessary for building a "blog" (posts, navigation, theme, etc.) and then walking through the steps from start to finish. Do you envision portions of the example to link to more complex/detailed docs?

Let me know if there's anything I can do to help.

**Comment by stefanwalther** [comment]
@brandonmerritt I'd really like to help and actually I am waiting now for some months that assemble reaches a state where I have the feeling that I really can start digging into it, understanding it better and using it in a much better way in some of my projects.
Just following what @jonschlinkert is doing shows me (maybe I am wrong?) that there is still a lot of ongoing work, refactoring, bringing in some missing concepts (e.g. collections, etc.), writing documentation, etc.
So I am still absolutely behind what I was writing above: I very much like assemble and I am not considering anything else, just waiting to the right point in time that such efforts makes sense for me.

Maybe - even hopefully - I am wrong ;-)

**Comment by jonschlinkert** [comment]
@stefanwalther awesome comment. 

To give a high level overview of what we're planning, all of the following projects will work together or be compatible with one another (to the extent that it makes sense):

- [generate](https://github.com/generate/generate): Initialize projects
- [assemble](https://github.com/assemble/assemble): Build projects 
- [verb](https://github.com/verbose/verb): Document projects
- [update](https://github.com/update/update): Update existing projects
- cyborg (not ready to talk about this one yet, but it won't hold up the others)

Generate was the most time consuming and challenging piece, but that was released yesterday :) Now we're working on getting generators pushed up, as well as docs for generate.  The results of this will be used in verb, update and assemble. And we'll be using `generate` to create plugins and things like that.

If anyone wants to help move things along with assemble, the most effective way to do so is probably by helping us get the "foundational pieces" wrapped up.

I know the seeming lack of progress on assemble master kind of sucks, but I'm going to stick to my guns on doing this the right way. I'm a big fan of micro-libs and small modules, but not every problem can be solved with a micro-lib. Projects like assemble are (IMHO) necessary to accomplish complex tasks. When you see how fast all of this runs, and how easy it is to refactor or change something anywhere in the stack, you'll see why it was worthwhile - and why it's taking some time to build the infrastructure in a way that makes many of the individual pieces completely self-encapsulated and reusable on any other projects.

I can't wait to show you all what these things are capable of!

**Comment by jonschlinkert** [comment]
By the way, [assemble-core](https://github.com/assemble/assemble-core) is 100% released and stable. It has everything except for built-in defaults. The only reason we haven't released 0.6.0 is documentation. Now that most of the core, infrastructure pieces are almost done, we'll be shifting to docs very soon

**Comment by stefanwalther** [comment]
Hi @jonschlinkert, thx for your answer. I'll give assemble-core a try ASAP.
After reading your answers, some questions back:

I realize that you have created metalsmith alike examples
- How do you differentiate between assemble and metalsmith
- Are there any plans to allow also metalsmith plugins to work with assemble-core in the future?

Regards
Stefan

**Comment by jonschlinkert** [comment]
@stefanwalther just wanted to let you know I have an answer in the works. I'll post up here asap

**Comment by jonschlinkert** [comment]
> How do you differentiate between assemble and metalsmith

There is not much similar between the two. The examples show how to build projects using a similar style to metalsmith using a thin wrapper function, but that's about it.

- assemble has rich support for template collections
- assemble supports template "types": renderable, layout and partial - defined when a collection is created, to add special behavior and methods related to the type; and collections can use one or more type.
- assemble does not limit how and where you build files
- assemble supports instance plugins (like metalsmith), so you can do anything you want to an instance
- assemble supports pipeline plugins (like gulp)
- assemble `collections` can use plugins
- assemble `views` (templates) can use plugins (assemble views are vinyl files)
- assemble supports any template engine, and allows you to use one or more template engines simultaneously during the same build (assemble automatically uses the engine that was specified for a given file type)
- assemble supports middleware, similar to express, to allow files to be transformed at various specific points during the build, like `onLoad`, `preRender`, `postRender`, `preWrite` and so on

This is just a start. Let me know if you have questions about anything specific. I think both tools are great, it just depends on what you need and how much work you want to do to get it

**Comment by stefanwalther** [comment]
:+1:

**Comment by jonschlinkert** [comment]
@stefanwalther, and anyone else who'd like to help, now that we have 0.6.0 released it should be smooth sailing from here. Releases will be much faster too, master will be published as 0.7.0 sometime this week.  

The transition from 0.4.x to 0.6.0 was rocky because of how completely different the APIs are. But going forward we don't anticipate there being any major changes. 

Any help with docs or recipes would be great! (recipes are nice for PRs because they can be anything you like using in your own projects and would like to share.)

**Comment by stefanwalther** [comment]
For those who are following this discussion: I have started a project using the latest version of assemble. Idea in this project is to provide a typical setup for a website including pages, blogs, articles and a lot of other features. It should then be possible to reuse this setup in multiple projects just by configuration (grunt-alike):

https://github.com/stefanwalther/assemble-scaffold

**Comment by jonschlinkert** [comment]
@stefanwalther thanks. I'm going to close this for now, since it's not really an issue. when you or anyone is interested in helping with docs, please just feel free to do a pr or get in touch! thanks

**Comment by stefanwalther** [comment]
Absolutely.
