### ISSUE TITLE
ajax and handlebars.

### ISSUE THREAD

**Issue by harish2rock** [assemble/assemble#721]
I have an ajax call in my js file. How do I pass the response of this ajax call to an handlebars template ?
Something like this -

```js
var raw_template = $('#simple-template').html();
var template = Handlebars.compile(raw_template);
$.getJSON("/restful/fortune", function(response) {
var html = template(response);
$('#main').append(html);
});
```
The handlebars template is defined in a hbs file (another handlebars file 'results.hbs') as -

```html
<script id="simple-template" type="text/x-handlebars-template">
<div id="main">
<p>{{response.status}}</p>
<p>{{response.fortune}}</p>
</div>
</script>
```

Assemble is parsing the handlebars template as html itself. Can you please help me out ?

**Comment by jonschlinkert** [comment]
sorry, a bit out of date but there seems to be a misunderstanding of what assemble does. This kind of question is usually a better fit for stackoverflow anyway, since we try to keep issues focused on bugs and feature requests.
