### ISSUE TITLE
Example for generating html from hbs doesn't work / v0.6.0-beta.5

### ISSUE THREAD

**Issue by hyzhak** [assemble/assemble#722]
This example puts hbs inside of `dist` folder.

https://github.com/assemble/assemble/tree/v0.6.0-dev#example-templates
```javascript
var assemble = require('assemble');

assemble.task('default', function () {
  assemble.src('templates/*.hbs')
    .pipe(assemble.dest('dist'));
});
```

ever if I put extra parameter: ```{ext: '.html'}```

```javascript
var assemble = require('assemble');

assemble.task('default', function () {
  assemble.src('templates/*.hbs')
    .pipe(assemble.dest('dist', {ext: '.html'}));
});
```

What I'm doing wrong and how to generate html from hbs

**Comment by jonschlinkert** [comment]
Do you mean it doesn't change the file extension? 

if so you need to use a plugin for that.

```js
var assemble = require('assemble');
var extname = require('gulp-extname');

assemble.task('default', function () {
  assemble.src('templates/*.hbs')
    .pipe(extname());
    .pipe(assemble.dest('dist'));
});
```

**Comment by hyzhak** [comment]
thanks it works! Seems docs are obsolete because in `Readme.mb` you say that ```Generate HTML from templates.``` https://github.com/assemble/assemble/blob/v0.6.0/README.md#example-templates but it doesn't. So I think I'm not the first guys that got problem with it

**Comment by jonschlinkert** [comment]
being a community project, this would be a great opportunity to contribute and update the docs! :)

**Comment by hyzhak** [comment]
good point! here is PR :+1:
