### ISSUE TITLE
Multiple data's conflict and only use one

### ISSUE THREAD

**Issue by DusanMilko** [assemble/assemble#725]
I am trying to build the same hbs files using multiple data variations(language translations).
But the data seems to only use the first one and no change:

---

```
assemble.task('english', function() {
  assemble.data(['src/data/english/\*\*/\*.{json,yml}']);
  assemble.src('src/views/pages/\*\*/\*.hbs')
      .pipe(rename(function (path) {
        path.extname = ".html"
      }))
      .pipe(assemble.dest('build/englsih'));
});

assemble.task('german', function() {
  assemble.data(['src/data/german/\*\*/\*.{json,yml}']);
  assemble.src('src/views/pages/\*\*/\*.hbs')
      .pipe(rename(function (path) {
        path.extname = ".html"
      }))
      .pipe(assemble.dest('build/german'));
});

gulp.task('assemble', function() {
  assemble.run('english');
  assemble.run('german');
});
```

---

So I run "gulp assemble" which runs both assemble tasks. I get no errors. The pages get generated but the data used in them is from english. The data doesn't change when the german task runs. I want the english task to use the data in the english folder and german task to use data in the german folder.

**Comment by doowb** [comment]
Have you tried this using only `assemble`?

```
assemble.task('default', ['english', 'german']);
```

**Comment by DusanMilko** [comment]
Tried it, still uses same data for both

**Comment by jonschlinkert** [comment]
fwiw, I know it's a multi-lingual project, but I'm pretty sure `englsih` is a misspelling in all languages lol. jk
