### ISSUE TITLE
Assemble seems to hang for about 8 secs

### ISSUE THREAD

**Issue by Coder2012** [assemble/assemble#726]
I am getting slow build times on a really high spec laptop.

Running with -v it seems to hang at the following point for about 8 secs even if only assembling one single page.

Step 1 assembled.
Calling step 2
Validating options
>> >> Current engine: handlebars

Is this normal behaviour, or is there something I can investigate to sort this out?

**Comment by doowb** [comment]
Can you provide more information about the versions of node and os that you're using?

**Comment by jonschlinkert** [comment]
Can we get more info? Is this grunt-assemble (v0.4.x)? Or Assemble? Also what kind of tasks/plugins/helpers/templates?

**Comment by jonschlinkert** [comment]
lol

**Comment by Coder2012** [comment]
Sorry guys I'm in the UK it was getting late:

OS: Windows 7
CPU: i7 2.7GHZ
RAM: 16GB
HDD: 125GB
SSD: 125GB - project located here

Our project uses the following grunt tasks:

$ npm list --depth=0
trek-lab@0.1.0 E:\trek_amaze_html
├── almond@0.3.1
├── assemble@0.4.42
├── chalk@1.0.0
├── fs-readdir-recursive@0.1.2
├── grunt@0.4.5
├── grunt-autoprefixer@2.2.0
├── grunt-bowercopy@1.2.0
├── grunt-browser-sync@2.1.3
├── grunt-combine-mq@0.6.0
├── grunt-concurrent@1.0.0
├── grunt-contrib-clean@0.6.0
├── grunt-contrib-compress@0.13.0
├── grunt-contrib-connect@0.9.0
├── grunt-contrib-copy@0.7.0
├── grunt-contrib-cssmin@0.11.0
├── grunt-contrib-imagemin@0.9.4
├── grunt-contrib-jshint@0.11.2
├── grunt-contrib-requirejs@0.4.4
├── grunt-contrib-uglify@0.7.0
├── grunt-contrib-watch@0.6.1
├── grunt-modernizr@0.6.0
├── grunt-ng-annotate@0.10.0
├── grunt-pixrem@0.1.2
├── grunt-plato@1.3.0
├── grunt-sass@1.0.0
├── grunt-stripmq@0.0.6
├── grunt-svgmin@2.0.1
├── grunt-svgstore@0.3.6
├── grunt-webfont@0.5.3
├── handlebars-helpers@0.5.8
├── jit-grunt@0.9.1
├── lodash@3.9.3
├── path@0.11.14
└── time-grunt@1.2.1

Here is our assemble setup:

assemble: {
			options: {
				deploy: deploy,
				layoutdir: '<%= project.dirs.views.layouts %>',
				partials: '<%= project.dirs.views.partials %>**/*.hbs',
                data: '<%= project.dirs.views.partials %>**/data.json',
                helpers: '<%= project.dirs.client.helpers %>**/helper-*.js',
				plugins: ['handlebars-helpers']
			},
            lab: {
                options: {
                    layout: 'lab.hbs',
                    data: '<%= project.dirs.data.main %>**/*.json'
                },
                files: [{
                    cwd: '<%= project.dirs.views.lab %>',
                    dest: '<%= project.dirs.base %>',
                    expand: true,
                    src: ['index.hbs']
                }],
            },
			pages: {
				options: {
					layout: 'page.hbs',
                    data: '<%= project.dirs.data.main %>**/*.json'

				},
				files: [{
					cwd: '<%= project.dirs.views.main %>',
					dest: '<%= project.dirs.lab.pages %>',
					expand: true,
					src: [
						'**/*.hbs',
						'!_layouts/**',
                        '!_lab/**',
						'!_partials/**'
					]
				}],
			},
			components: {
				options: {
					layout: 'component.hbs'
				},
				files: [{
					flatten: true,
					cwd: '<%= project.dirs.views.main %>',
					dest: '<%= project.dirs.lab.components %>',
					expand: true,
					src: ['_partials/**/*.hbs']
				}]
			}
		}

When I am testing I run each task individually eg:

grunt assemble:lab - 9.8s for one page using a data.json to generate an index page.
grunt assemble:pages - 9.7s for 22 pages using maybe 3 data.json files
grunt assemble:components - 10.1s for 64 pages each are partials with data.json on most of them.

There is only one custom helper which checks if value exists.

This laptop is pretty high spec as you can see, when I run these tasks on similar spec macs they are a fraction of the time. They always hang at the same point, is there a lot of processing at step 2 or something?

Any advice to help me speed things up would be really appreciated.

**Comment by jonschlinkert** [comment]
Without seeing the data file or templates, it's hard to say for sure what would be causing the issue, but using more specific glob patterns might help. When you use `**` everything in that path will get globbed and processed. 

how big are the data files?

**Comment by paulsham** [comment]
I think I'm having the same issue. I am running Assemble with JSON and Handlebars templates.

It seemed to be running fine on an older version of node, but I updated to node version 0.12.4 and it seems to slow down after a certain number of files (in my case, 66).

**Comment by Coder2012** [comment]
@jonschlinkert 

Thank you so much, you helped me to track it down when you mentioned the globbing patterns:

helpers: '<%= project.dirs.client.helpers %>**/helper-*.js',

I did not have a variable for this path, therefore I assume that the task had to traverse the entire structure to find these helpers?

Once I fixed this boooooooooom, it ran like a dream.
