### ISSUE TITLE
Partials with custom data

### ISSUE THREAD

**Issue by mrmartineau** [assemble/assemble#727]
Having read the handlebar partial docs at http://handlebarsjs.com/#partials, is it possible to have custom data for each partial, using Assemble, if defined like below? :
```js
{{> input-text label="Text Input" errorMessage="Please provide a value"}}
```

input-text.hbs partial:
```html
<div class="form-controlGroup">
	<label for="text" class="form-label">{{label}}</label>
	<div class="form-controlGroup-inner">
		<div class="form-controlGroup-inputWrapper">
			<input type="text" id="text" placeholder="Joe Bloggs" class="form-input"/>
		</div>
		<div class="form-message">{{errorMessage}}</div>
	</div>
</div>
```

The error grunt gives me is:
```sh
Warning: Parse error on line 5:
...{{> input-text label="Text Input" errorM
-----------------------^
Expecting 'CLOSE', 'CLOSE_UNESCAPED', 'STRING', 'INTEGER', 'BOOLEAN', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'DATA', 'SEP', got 'EQUALS' Use --force to continue.
```

**Comment by jonschlinkert** [comment]
As far as I know, handlebars doesn't support using `hash` arguments in partials. However, you could easily do the same with a helper: http://handlebarsjs.com/block_helpers.html

**Comment by doowb** [comment]
This is a newer syntax. Try switching to [`grunt-assemble`](https://github.com/assemble/grunt-assemble) since it's been updated to use Handlebars 3.

**Comment by mrmartineau** [comment]
@doowb which is newer syntax? Mine or handlebars?

**Comment by jonschlinkert** [comment]
that works now? nice. thanks @doowb

**Comment by doowb** [comment]
[partial parameters](http://handlebarsjs.com/partials.html#partial-parameters) is something that's new to Handlebars. assemble 0.4.x is using Handlebars 1, but we moved the code to grunt-assemble to be able to support upgrading to Handlebars 3. If the syntax doesn't work with grunt-assemble, please open an issue there.

**Comment by jonschlinkert** [comment]
here are the [release notes](https://github.com/wycats/handlebars.js/blob/master/release-notes.md#v301---march-24th-2015) for it

**Comment by mrmartineau** [comment]
Amazing! thanks @doowb, I have switched to `grunt-assemble` and it works as expected. Is development for `grunt-assemble` moving faster than `assemble`?

**Comment by jonschlinkert** [comment]
@doowb grunt-assemble uses 3.0 https://github.com/assemble/assemble-handlebars/blob/master/package.json#L42. "assemble" 0.4.x is deprecated.

**Comment by jonschlinkert** [comment]
> Is development for grunt-assemble moving faster than assemble?

Assemble 0.6.0 development is continuing on this repo, but it's no longer a grunt plugin. grunt-assemble, which is just a continuation of assemble 0.4.x, will also continue to be maintained on the grunt-assemble repo
