### ISSUE TITLE
Default layout not working

### ISSUE THREAD

**Issue by stefanwalther** [assemble/assemble#728]
I don't exactly know where I have this from, but the default layout is not working:

```js
assemble.layouts('./config/layouts/**/*.hbs');
assemble.option( {layout:  'default'} );
// also tried: assemble.option('layout', 'default');
```
So if I don't define the layout now in front end matter, the page/doc will not be rendered ...

A WAD or BUG?

Regards
Stefan

**Comment by jonschlinkert** [comment]
do you have a layout named `default.hbs`?

**Comment by stefanwalther** [comment]
I am using a default.hbs, I don't use renameKey

**Comment by stefanwalther** [comment]
Just tested the other recommendation: 

```js
assemble.option( {layout:  'default.hbs'} );
```

... does also not work.

**Comment by doowb** [comment]
I just downloaded your sample project and using `assemble@beta` with `assemble.option('layout', 'default');` works for me.

I'm running `assemble` from inside the `Basic` folder (not sure if that's the same place you're running it from or if you're doing something else)

**Comment by doowb** [comment]
Oh... I took out all the `layout: default` in the front-matter of the `.md` files too.

**Comment by stefanwalther** [comment]
OK, now I have it: 

* The file will not be created if there is no content and just the front-matter ...

Thx!

**Comment by jonschlinkert** [comment]
> The file will not be created if there is no content and just the front-matter ...

@doowb is this a vinyl thing? e.g. if there is no contents, then a file is not created?

**Comment by doowb** [comment]
I don't think that's true.  Some of the files have `draft: true` in their front matter.

**Comment by stefanwalther** [comment]
Just commited a new version, you'll see that only one file has no content (`no-content.md`) and this this the only file not being generated.

https://github.com/stefanwalther/assemble-samples

**Comment by doowb** [comment]
The issue is in the version of `template-utils#toVinyl` that `template-init` is using.
For some reason an empty string is returning false in `if (template.content)`. This version is really old and will be replaced soon.

For now, you can add a new line after the closing `---` and that works (my editor always adds a newline so that's why I didn't notice it at first).

**Comment by stefanwalther** [comment]
OK, thx @doowb

**Comment by jonschlinkert** [comment]
newline or not, I just wanted to confirm that empty files are not written to disk by vinyl, correct?

**Comment by doowb** [comment]
Looks like it's a combination of issues, but ultimately, if `file.isNull()`, no file is created in `vinyl-fs#dest`.
