### ISSUE TITLE
#each collection ... documentation needed

### ISSUE THREAD

**Issue by stefanwalther** [assemble/assemble#729]
Ohhh gosh,

my thinking was that as soon as I define

```js
assemble.pages( './docs/pages/**/*.md' );
```

it will be added to be used in handlebars as

```html
{{#each pages}}
   bla
{{/each}}
```

Now I realized that this isn't the case.
Is this just misleading, a bug, a wad???
What am I missing here?

Regards
Stefan

**Comment by jonschlinkert** [comment]
this is exactly what helpers are for! 

what would you expect to render there? A list of relative links to all pages? the page names? the page content? A helper can iterate over the views to yield any of these things...

**Comment by jonschlinkert** [comment]
Maybe these will help, change them to get views from whatever collection you want:

```js
assemble.asyncHelper('post', function (name, options, cb) {
  var file = this.app.views.posts[name];
  if (typeof options === 'function') {
    cb = options;
    options = {};
  }

  file.render(this.context, function (err, content) {
    if (err) return cb(err);
    console.log(content);
    return cb(null, content);
  });
});

assemble.asyncHelper('posts', function(options, cb) {
  if (typeof options === 'function') {
    cb = options;
    options = {};
  }
  var ctx = this.context;
  var posts = this.app.views.posts;
  var keys = Object.keys(posts);

  async.map(keys, function (key, next) {
    posts[key].render(ctx, function (err, content) {
      if (err) return next(err);
      next(null, content);
    });
  }, function (err, res) {
    if (err) return cb(err);
    console.log(res)
    cb(null, res.join('\n'));
  });
});
```

**Comment by jonschlinkert** [comment]
closing since it's not actually an issue, more of a question

**Comment by stefanwalther** [comment]
Hi @jonschlinkert,

thx, now I think I get it.
My *wrong* thinking was that the `pages` collection will automatically created using all pages.
(If I am not completely wrong this was the way how assembe_v0.43 worked, right?)

Thx again, continue to get it working.

**Comment by jonschlinkert** [comment]
> If I am not completely wrong this was the way how assembe_v0.43 worked, right?

hmm, you might be right... I have to admit I don't remember, it's been so long since I used that version lol

**Comment by stefanwalther** [comment]
But maybe that's worth to think about ... IMHO it makes it much easier to get started with assemble. Understanding then the basics you can then still add additional view collections.

**Comment by jonschlinkert** [comment]
well, to repeat what I said above:

> what would you expect to render there? A list of relative links to all pages? the page names? the page content? A helper can iterate over the views to yield any of these things...

thoughts?

Maybe we should implement a few different built-in helpers for working with collections.

**Comment by stefanwalther** [comment]
So my humble thinking is:

Having the following .md files:

**docs/File1.md**:
```
---
title: This is file 1
---
```

**docs/File2.md**:
```
---
title: This is file 2
---
```

Then I have the following setup:

```
assemble.pages( './docs/*.md' );


assemble.task( 'site', function () {
	assemble.src( './docs/*.md' )
		.pipe (extname() )
		.pipe( assemble.dest( DESTINATION ) );
} );
```

... would then allow me to do something like that **out of the box**:

```
<ul>
{{#each pages}}
	<li>{{data.title}}</li>
{{/each}}
</ul>
```

and I would get

```
<ul>
	<li>This is file 1</li>
	<li>This is file 2</li>
</li>
```

**Comment by jonschlinkert** [comment]
k, that helps. thanks
