### ISSUE TITLE
How to ensure to write to a single file

### ISSUE THREAD

**Issue by stefanwalther** [assemble/assemble#735]
Hi,

how can I ensure that I only write to a single file?

This code gives me always `README.md\.readme.md`

```js
assemble.task( 'readme', function () {
	assemble.src( './../.readme.md' )
		.pipe( assemble.dest( './../README.md' ) )
} );
```

**Comment by jonschlinkert** [comment]
this is a vinyl-fs thing. `dest` can only be a directory.

**Comment by stefanwalther** [comment]
How are you doing it in verb?

**Comment by jonschlinkert** [comment]
Here's how I'm doing it in the [default task](https://github.com/verbose/verb-default/blob/master/index.js#L9). fwiw, @doowb and I have talked about this a lot, it's one of the (many) reasons I'd like to move away from using vinyl/vinyl-fs. It's a pita to do trivial things like set a dest path.

**Comment by stefanwalther** [comment]
The only way to achieve this without changing code was to use gulp-concat:

```js
assemble.task( 'readme', function () {
	assemble.src( './../docs/.README.md' )
		.pipe( concat( 'README.md' ) )
		.pipe( assemble.dest( './../' ) )
} );
```

**Comment by jonschlinkert** [comment]
Closing since this is more of a question. For future readers, `dest` takes a directory or function (e.g. not a full filepath). And if a function is passed, it must return a directory.
