### ISSUE TITLE
Nested Partials in Assemble

### ISSUE THREAD

**Issue by alwayrun** [assemble/assemble#736]
how to  different partials with the same filename in different folders

**Comment by jonschlinkert** [comment]
In the Assemble 0.6.0, you can customize how any and all templates are named using a `renameKey` function passed on the options.

```js
var assemble = require('assemble');
var app = assemble();

app.option('renameKey', function(key) {
  // do whatever you want to rename keys here
  return path.basename(key);
});
```
also see https://github.com/assemble/assemble/issues/708.
