### ISSUE TITLE
Including markdown in markdown pages

### ISSUE THREAD

**Issue by stefanwalther** [assemble/assemble#739]
Hi,

I am using assemble to generate markdown pages from markdown pages (including some handlebars handling).
I'd like to achieve the same as I would do as follows in verb:

```js
{%= docs('00-TOC.md')%}
```

I have tried several approaches, using partials, `include` but not of them really works. Important to mention that I don't want HTML output but again just the processed markdown (with some custom helpers).

What would be the recommended approach?

Regards
Stefan

**Comment by jonschlinkert** [comment]
you're using assemble v0.6.0, correct? if so maybe try one of these:

https://github.com/helpers/helper-markdown
https://github.com/helpers/helper-md

we can create a custom one if neither of those work out

**Comment by doowb** [comment]
don't those both render markdown into html?

I think you should be able to just use a built in helper by creating a `docs` type:

```
assemble.engine('.md', require('engine-assemble'));
assemble.create('doc');
assemble.docs('docs/*.md');

assemble.task('build', function () {
  return assemble.src('templates/README.md')
    .pipe(assemble.dest('./'));
});
```

then `templates/README.md` might look like this:

```
# Some Heading

{{docs "00-TOC.md"}}
```

Might have to leave off the `.md` if the default `renameKey` function is removing the extension.

**Comment by jonschlinkert** [comment]
ohhhhh... doh. I missed the entire operative point of this issue lol. no worries though! @doowb's got you covered!

**Comment by stefanwalther** [comment]
Thx a lot for your quick answer, I'll give it immediately a try ... ;-)

**Comment by jonschlinkert** [comment]
yeah, to @doowb's point, all you need is "includes", since you're not converting the markdown.

**Comment by stefanwalther** [comment]
If I do that as described above I'll just get "missing helper docs"

**Comment by doowb** [comment]
Sorry, it should be `{{doc "00-toc.md"}}`

**Comment by jonschlinkert** [comment]
yeah, atm by default only singular-form helpers are created. we're working on something pretty awesome though :)

**Comment by stefanwalther** [comment]
Sorry, already tried that, also doesn't work, here's my setup:

```js
assemble.engine( '.md', require( 'engine-assemble' ) );
assemble.create( 'doc' );
assemble.docs( './../docs/includes/**/*.md' );
```

**./../docs/includes/toc.md**

```
---
draft: false
---
bla bla bla bla 

bla bla bla bla
```
(also tried it without the frontend matter ... same result)

In the markdown file then
```
{{doc 'toc.md'}}
or
{docs 'toc.md'}}
```

The task then
```js
assemble.task( 'readme', function () {
	console.log('docs', assemble.docs());
	console.log('doc', assemble.doc());
	return assemble.src( './../docs/README.md' )
		.pipe( debug() )
		.pipe( assemble.dest( './../README/' ) );
} );
```

Both `docs`and `doc` return an empty object.
So it seems that with the loading of the "includes" something is wrong.

**Comment by jonschlinkert** [comment]
well, these are functions for loading:

```js
    console.log('docs', assemble.docs());
    console.log('doc', assemble.doc());
```

The actual views are on `assemble.views` for every template type. try doing:

```js
assemble.task( 'readme', function () {
    return assemble.src( './../docs/README.md' )
        .on('data', function(data) {
           console.log('doc', assemble.views.docs);
        });
        .pipe( assemble.dest( './../README/' ) );
} );
```

I use this same approach to do the default helpers for verb.

**Comment by stefanwalther** [comment]
OK, finally got it working. the trick is not to use

```js
{{doc 'toc.md`}}
```
but
```js
{{doc 'toc'}}
```

Thx @jonschlinkert , having the debug output immediately solved my issue.

**Comment by doowb** [comment]
:100:

**Comment by jonschlinkert** [comment]
> OK, finally got it working. the trick is not to use

great!
