### ISSUE TITLE
Slow compilation in node 0.12.4

### ISSUE THREAD

**Issue by paulsham** [assemble/assemble#740]
I think I'm having the same issue. I am running Assemble with JSON and Handlebars templates.

It seemed to be running fine on an older version of node, but I updated to node version 0.12.4 and it seems to slow down after a certain number of files (in my case, 66). Every file after that assembles slowly.

Reverting back to an older version of node (in my case, 0.10), resolved this.

**Comment by jonschlinkert** [comment]
yeah I've notices in benchmarks (for non-assemble code) that 0.12.4 is just slower in general. I'm going to close b/c I don't think there is much we can do about it - but I'd be happy to re-open if anyone has ideas for solutions. Thanks for letting us know
