### ISSUE TITLE
How to loop partials in Assemble

### ISSUE THREAD

**Issue by code-mattclaffey** [assemble/assemble#742]
I am trying to loop an array of partials in my styleguide but all I get is the partial name and not the actual partial.

This will error because it is trying to find this.component and not the actual partial name.

Is this possible with assemble or not?

Thank you

Link to post: http://stackoverflow.com/questions/31029214/how-to-loop-partials-in-assemble

**Comment by jonschlinkert** [comment]
sorry for the late reply. closing since this is more of a user question. if you think it's a bug, please reopen either on grunt-assemble or here if you're using the latest
