### ISSUE TITLE
AsyncHelper

### ISSUE THREAD

**Issue by stefanwalther** [assemble/assemble#743]
Hi @jonschlinkert,

you have previously posted the following example how to create a custom collection:

```js
assemble.asyncHelper('renderposts', function(options, cb) {
  if (typeof options === 'function') {
    cb = options;
    options = {};
  }
  var ctx = this.context;
  var posts = this.app.views.posts;
  var keys = Object.keys(posts);

  async.map(keys, function (key, next) {
    posts[key].render(ctx, function (err, content) {
      if (err) return next(err);
      next(null, content);
    });
  }, function (err, res) {
    if (err) return cb(err);
    console.log(res)
    cb(null, res.join('\n'));
  });
});
```

By first defining
```js
assemble.create( 'post' );
assemble.posts( './../docs/posts/*.md' );
```

I can now use

```hml
{{renderposts}}
```

which is fine, but actually what I'd like to achieve is to have a collection I can then use in all templates, so something like

```html
<ul>
{{#each posts}}
    <li>{{data.title}}</li>
{{/each}}
</ul>
```

How would you solve this. Sorry I keep asking this question, but this is the main issue for me in several projects where I am trying to use assemble v0.6.0

Regards
Stefan

**Comment by askesian** [comment]
+1 I would like to know how to do this as well. Using assemble 0.6.0.

**Comment by jonschlinkert** [comment]
sorry for not replying earlier, I thought I had. We're in the midst of releasing some new stuff for assemble, as well as docs. hang tight, it's on the way!

**Comment by jonschlinkert** [comment]
@doowb do we have an example of this somewhere with the new templates/assemble dev stuff?

**Comment by jonschlinkert** [comment]
closing since I believe this was answered on another issue. also this is mostly a documentation/implementation related question.
