### ISSUE TITLE
Blockquotes in assemble-handlebars

### ISSUE THREAD

**Issue by davidsinclair** [assemble/assemble#744]
Hi,

I am having a problem getting blockquotes to render correctly using assemble-handlebars). The following code illustrates the problem, when I run it the output is:

<h1 id="heading">heading</h1>
<p> &gt; pull quote</p>
i.e. the > is being escaped rather than rendered as a blockquote.

This bug only happens when using assemble-handlebars to render a javascript object - in our static site generation code where we write yaml files to disk we do not see this problem. 

Any help greatly appreciated,

David

```
var assemble = require('assemble-handlebars');
assemble.init({
  marked: { sanitize: false, gfm: true}
});
var templateSrc = '{{#markdown}}{{body}}{{/markdown}} ';
var doc = { body: "#heading\n\n > pull quote" };

assemble.compile(templateSrc, {}, 
  function(ex, template) {

  assemble.render(template, doc, function(ex, renderedContent) {
  console.log(renderedContent);

  });
});
```

**Comment by doowb** [comment]
Since you're using `assemble-handlebars` directly in this example you should use 3 curly braces around `body`. That tells handlebars that you don't want to escape the string in `body`.

**Comment by davidsinclair** [comment]
Thanks!  This fixes the example I gave. 

However, I am still not clear on why the behaviour is different than what I see with the same template using grunt-assemble ... we have a statically generated site but we also provide a preview tool that lets people see an individual page rendered dynamically (it uses assemble-handlebars directly as in my example).  We use the same templates and want to see the same behaviour in each.  Any idea why the behaviour is different?

David

**Comment by doowb** [comment]
It's because in grunt assemble we do a string replacement on the body tag to handle nested layouts. So the markdown helper is doing the transformation on the raw text then outputting a safe string.

**Comment by davidsinclair** [comment]
Great, thanks for the explanation.

**Comment by doowb** [comment]
Happy to help.
