### ISSUE TITLE
Comments in outputted code

### ISSUE THREAD

**Issue by asha23** [assemble/assemble#745]
I am using Assemble to streamline my Email creation process. I have found that it strips out all the comments when it compiles. (I need a couple of IE specific conditonals to be kept when the code is compiled) - Currently, Assemble seems to remove these comments. Is there an option available to stop it from doing this?

**Comment by doowb** [comment]
Do you have an example project with a template and the results that you're seeing? It'll make it easier for us to help.

**Comment by asha23** [comment]
Yes, I have created a repository here.

https://github.com/asha23/Email-Framework

Essentially it simply compiles out the email using Assemble... If you look in src/emails you will see where I'm creating the templates.

You can see an example of the compiled code in the build/emails folder. With no comments :(

Cheers!

**Comment by doowb** [comment]
assemble is working fine (you can verify that by just running `grunt assemble` and looking at the output). I have a feeling that [this line](https://github.com/asha23/Email-Framework/blob/master/gruntfile.js#L54) is telling `premailer` to remove the comments.
