### ISSUE TITLE
0.6 Caching Partials?

### ISSUE THREAD

**Issue by ashleynolan** [assemble/assemble#746]
Hi,

I’m building up a static documentation site using 0.6 for the first time and trying to work out some of the basics compared to using 0.4.

I’ve got my build working with Gulp, but when trying to watch files for changes (using gulp.watch) and then re–running the assemble task, if the change came from a partial (like an included page header) rather than the page itself, the compiled HTML reflects the old partials code.  It seems like it is caching the include at the start of the task being run as when I then re-run my gulp task – without the watch – it works as expected.

Guessing there must be a way around this – I have previously used watch tasks with Grunt on 0.4 and never had any problems, so thinking it must be something to do with how I’ve got it setup using 0.6…

Also, once I’ve got my site setup, will be more than happy to alter it so others can use as a base setup to get started when using 0.6 with Gulp.

Cheers,
Ash

**Comment by doowb** [comment]
You probably just need to move the `assemble.partials('path/to/partials/*.hbs');` line to inside the task function. If it's outside the task, it'll only run when the file is loaded the first time. If it's inside the task, then the code will run to re-load the partials each time watch executes the task.

**Comment by ashleynolan** [comment]
Yep – that was it.  Thanks :)
