### ISSUE TITLE
Change generated link extensions

### ISSUE THREAD

**Issue by ronydj** [assemble/assemble#748]
Hi Guys,

I am trying to create a boilerplate to generate github wiki pages to html documentation pages.

But I am facing this problem. In github we generally create sidebars with links in this way:

    ## Documentation
    1. [Getting Started](getting-started)

In github its generate a proper link for the **getting-started** page.

Using assemble, I can generate nice html pages from the github markdown pages. The only problem are these links for internal pages.

When I transform the .md file to .html file, its generate this html:

    <h2 id="Documentation">Documentation</h2>
    <ol>
           <li><a href="getting-started">Getting Started</a></li>
    </ol>

Is there any way to change the url from the generated html, and add a .html at the end of the links ?

so it looks like

    <h2 id="Documentation">Documentation</h2>
    <ol>
           <li><a href="getting-started.html">Getting Started</a></li>
    </ol>

**Comment by jonschlinkert** [comment]
What version of assemble are you using?

**Comment by jonschlinkert** [comment]
closing based on lack of follow up
