### ISSUE TITLE
Pagination?

### ISSUE THREAD

**Issue by jgibba** [assemble/assemble#749]
This framework is awesome and want to use it but would like to know if there is a working built in pagination? I have seen a few github repos and comments that suggest there may not be pagination.

If there is not, I know there are JavaScript pagination libraries as a substitute, but I wonder if there's a downside to using such a library with a large data set of posts, for example, and if there is a way around this.

Thank you!

**Comment by jonschlinkert** [comment]
really sorry for the late reply. We have some great pagination stuff on the way for assemble v0.6.0. grunt-assemble has some pagination/collections handling built-in, but it's somewhat limited. what version of assemble are you on? thanks

**Comment by jonschlinkert** [comment]
In 0.6.0 pagination and indexing will be handled by plugins. We have already published a couple, [templates-indexer](https://github.com/doowb/templates-indexer) and [paginationator](https://github.com/doowb/paginationator). If you need something different, it might be good to create an issue on one of those repos, or just create a custom plugin using those as an example.
