### ISSUE TITLE
Custom helpers in {{#each}} not called

### ISSUE THREAD

**Issue by fterrier** [assemble/assemble#751]
Hi,

We have the following pattern in our handlebar templates:

```handlebars
{{#each buttons_sizes}}
    {{#snippet this}}
        ...
    {{/snippet}}
{{/each}}
```

This week, that randomly stopped working (the custom helper inside the `each` was not called any more) and we could identify the issue. The `parser-front-matter` version 1.2.3 seems to cause the issue as we reverted to 1.2.2 and it works again.

You might want to check that yourself and maybe fix the version of `parser-front-matter` temporarily to `1.2.2`?

Let me know if that helps..

**Comment by jonschlinkert** [comment]
I believe this has been fixed. please open an issue on parser-front-matter if the issue persists
