### ISSUE TITLE
assemble@beta not render yml variable

### ISSUE THREAD

**Issue by onokumus** [assemble/assemble#752]
I have reinstalled the `assemble@beta` module. Named `assemblefile.js` and `home.hbs` have two files in the root directory. 

_assemblefile.js_
```javascript
var assemble = require('assemble');
var extname = require('gulp-extname');

assemble.task('default', function () {
  return assemble.src('home.hbs')
    .pipe(extname())
    .pipe(assemble.dest('dist/'));
});
```

_home.hbs_
```hbs
---
title: Home
---
<h1>{{title}}</h1>
```

I give the `assemble` command in the console. Results below

_dist/home.html_

```html
<h1></h1>
```

What's wrong?

**Comment by jonschlinkert** [comment]
see https://github.com/jonschlinkert/parser-front-matter/issues/3

**Comment by onokumus** [comment]
Ok. It's work

**Comment by jonschlinkert** [comment]
great! thanks for creating the issue
