### ISSUE TITLE
Page being assembled before handlebars can finish iterating over large dataset

### ISSUE THREAD

**Issue by Josh68** [assemble/assemble#753]
This may be a strictly handlebars issue, not sure, but I've just spent a lot of time debugging the rendering of an iterated block (each) that was preventing the portion of my page below that block from being rendered. I kept inspecting the data (valid JSON) for issues until I realized it just came down to the number of iterations that was the issue. If I truncate my JSON in just the right place, I can see more of the page render, and when I get it just right, all of the page renders, but then of course I'm missing a large part of my data set. Is there any known workaround for this issue in Assemble (note, I'm using grunt-assemble), to delay the assembly of pages until handlebars has iterated over all data? Thanks.

**Comment by jonschlinkert** [comment]
@Josh68 would you mind re-creating this issue on the grunt-assemble repo, so it would be easier for other users to find in the future. sorry for the inconvenience

**Comment by Josh68** [comment]
Will do that. Thanks.
