### ISSUE TITLE
Creating a custom collection with name 'template' prevents assemble.dest() from completing

### ISSUE THREAD

**Issue by askesian** [assemble/assemble#755]
I have an object w/ props whose values are path globs. I pass the object in, and iterate over the props and create a custom collection for each. If one of the object props is called 'template', the `.pipe(assemble.dest(dest));` part fails, and no files are generated. No error is thrown.

Example:
```
partials: {
            common: ['src/includes/common/**/*.{hbs,html}'],
            component: ['src/includes/patterns/components/**/*.{hbs,html}'],
            module: ['src/includes/patterns/modules/**/*.{hbs,html}'],
            structure: ['src/includes/patterns/structures/**/*.{hbs,html}'],
            template: ['src/includes/patterns/templates/**/*.{hbs,html}']
        },
```
I have no insight into the error that is occurring inside assemble (Template, really), but I know it's because of a custom collection called 'template' because if I use any other property name aside from 'template', everything works fine.

How can I get around this? I don't want to have to instruct my colleagues that they cannot use the property name 'template' in such a case.

**Comment by jonschlinkert** [comment]
this should be fixed with the latest assemble on the dev branch. please reopen if you still have this issue.
