### ISSUE TITLE
YFM parsing error?

### ISSUE THREAD

**Issue by pelletized** [assemble/assemble#756]
(for background please check this thread: http://stackoverflow.com/questions/31996215/code-snippets-blocks-within-yfm-variables)

I'm getting parsing errors while attempting to use a snippet of tracking code provided by Litmus for an HTML email. Sample code looks like this:
```
---
analytics: |
	<style>@media print{ #_t { background-image: url('https://0me4e2bg.emltrk.com/0me4e2bg?p&d=%%Email%%');}} div.OutlookMessageHeader {background-image:url('https://0me4e2bg.emltrk.com/0me4e2bg?f&d=%%Email%%')} table.moz-email-headers-table {background-image:url('https://0me4e2bg.emltrk.com/0me4e2bg?f&d=%%Email%%')} blockquote #_t {background-image:url('https://0me4e2bg.emltrk.com/0me4e2bg?f&d=%%Email%%')} #MailContainerBody #_t {background-image:url('https://0me4e2bg.emltrk.com/0me4e2bg?f&d=%%Email%%')}</style><div id="_t"></div>
	<img src="https://0me4e2bg.emltrk.com/0me4e2bg?d=%%Email%%" width="1" height="1" border="0" /> 
---
```
The error message I receive is 'JS-YAML: can not read an implicit mapping pair; a colon is missed...' 

It appears to be failing on `@media`, however, checking an Online YAML Parser this seems to be valid YAML. Thanks for looking at this!

**Comment by jonschlinkert** [comment]
closing since this would be an issue with the yaml parser, which is js-yaml
