### ISSUE TITLE
assemble.src('**/*.hbs') ignores duplicate named files in different directories.

### ISSUE THREAD

**Issue by pbaldwin** [assemble/assemble#757]
Say I have a directory structure like this:
```
pages/index.hbs
pages/apples/index.hbs
pages/oranges/index.hbs
```
and an assemble file like this:
```javascript
var assemble = require('assemble');
var debug = require('gulp-debug');

assemble.task('html', function () {
  assemble.src('pages/**/*.hbs')
    .pipe(debug())
    .pipe(assemble.dest('dist/');
});
```

If I run `assemble html` gulp-debug will log 'pages/oranges/index.hbs' and '1 items', while my `dist` directory only contains 'pages/oranges/index.hbs'.

I don't get the same result from gulp.src or when I set `assemble.enable('minimal config');`. My guess from looking through the source is that there might be something happening in event-streams that throws out duplicate named files? I dunno, though.

**Comment by jonschlinkert** [comment]
This should be resolved on the `dev` branch, since we no longer cache files by default.
