### ISSUE TITLE
Markdown rendering bug

### ISSUE THREAD

**Issue by MichielDeMey** [assemble/assemble#760]
Hey guys, I'd like to report a strange issue with markdown rendering.
This is most likely a bug in the markdown renderer that you use, however I could not find wich one.

The following bug is observed:
```markdown
---
title: Foo
---

# This is rendered as a header

<section>

  # This is not rendered as a header

</section>
```

output:

```html
<h1>This is rendered as a header</html>

<section>

  # This is not rendered as a header

</section>
```

The first header is rendered in html as an `h1`, however the second header inside the section tags is ignored and outputted literally.

I'm including the content as suggested in the documentation:

```handlebars
{{#markdown }}
  {{> body  }}
{{/markdown }}
```

Technically, this should work, right? Any ideas?

**Comment by jonschlinkert** [comment]
try un-indenting `body`

```handlebars
{{#markdown }}
{{> body  }}
{{/markdown }}
```

**Comment by MichielDeMey** [comment]
Hey Jon

Alas, no luck trying to un-indent it.
May I ask which Markdown parser you're using? Maybe I can replicate my issue?

**Comment by jonschlinkert** [comment]
what version of assemble are you using? also you can create and register a different markdown helper using whatever markdown renderer you want. also please verify with the [commonmark specification](http://commonmark.org/) that you're using valid markdown.

**Comment by MichielDeMey** [comment]
I'm currently using `grunt-assemble ^0.4.0`.
I checked the markdown and it appears valid, I have also added the YAML front matter to the example up top to let you know that I'm also using that.

**Comment by jonschlinkert** [comment]
okay, thanks. would you mind closing and re-creating this issue on the grunt-assemble repo so that we can track issues more effectively?

**Comment by MichielDeMey** [comment]
No problem, I'll move it over to that repo.
