### ISSUE TITLE
How to get a associative array value based on the key inside YAML variable ?

### ISSUE THREAD

**Issue by windmaomao** [assemble/assemble#761]
I searched everywhere, but i couldn't find the answer, basically here's what I want to do.

```
    ---
    alias: inventory_order
    url: <%= site.portfolios[alias].url %>
    metrics: <%= site.portfolios.inventory_order.metrics %>
    ---

```

here `site.portfolios.inventory_order.metrics` points to a object (array). I want to write the following

```
    metrics: <%= site.portfolios[alias].metrics %>
```

but the behavior is quite interesting, if I do that, `metrics` is a garbage, an object which I couldn't recognize. `url` is correct, because it points to a string.

I know this is a bit weird, i smell a bug, but i'm not sure.

**Comment by doowb** [comment]
Which version of assemble are you using?

If you're using assemble 0.4.x, then we're using `grunt.process` which is probably just passing the data into lodash and when using `<%= %>` the result is stringified. If `site.portfolios.inventory_order.metrics` is an array, then you're probably getting the same result as doing `site.portfolios.inventory_order.metrics.toString()` which looks like `one,two,three,four` for an array like `['one', 'two', 'three', 'four']`.

If you're going to use the metrics in handlebars, I would create a helper to get the metrics you want as an array and pass it into something like each:

```js
handlebars.registerHelper('get-metrics', function (obj, alias) {
  return obj[alias].metrics;
});
```

Then in handlebars do:

```handlebars
---
alias: inventory_order
---
{{#each (get-metrics site.portfolios alias)}}
{{/each}}
```

This is using Handlebars subexpressions to return an array and pass it to `each`. If it doesn't work with `assemble@0.4.0`, try using the latest `grunt-assemble` instead.

**Comment by windmaomao** [comment]
thank you very much doowb,with your help, i used a generic helper, ex. 

```
    module.exports.withItem = function (object, options) {
      return options.fn(object[options.hash.key]);
    };
```

then i can do something like

```
        {{#eachProperty metrics}}
            <tr>
                {{#withItem ../site.metrics key=key }}
                    <td class="area" data-tip="{{description}}">{{title}} <i class="fa fa-info-circle"></i></td>
                {{/withItem}}
                <td>
                    <div class="rating" data-score="{{this.value}}"></div>
                </td>
                <td>
                    <a href="{{ ../url }}" target="_blank">
                        <i class="fa fa-external-link"></i>
                    </a>
                </td>
            </tr>
        {{/eachProperty}}
```

**Comment by jonschlinkert** [comment]
closing since this is more of a question than an issue. If it does turn out to be a grunt-assemble issue, please reopen on that repo. thanks
