### ISSUE TITLE
How To: Render .md files passed to src(...) without using .hbs ext and wrapping content in {{#markdown}}{{/markdown}}

### ISSUE THREAD

**Issue by askesian** [assemble/assemble#762]
Using latest Assemble v.6.0x. I'm passing .md files as src(...) hoping to render them as .html to dest(...). I can't get this to work. I have to use the .hbs extension and wrap the content in the .hbs file with {{#markdown}} {{/markdown}}. I assumed there would be a way to write pages in markdown and render them through src(...) without having to resort the aforementioned work-around. Is there an assemble-markdown engine? Having to use .hbs and {{markdown}} tags messes up my syntax highlighting in Sublime.

Note: I also tried using .md.hbs as extension so I could work-around the Sublime syntax formatting issue, but the rendered files end up w/ .md.html extension.

**Comment by jonschlinkert** [comment]
Have you tried using a markdown plugin like https://github.com/sindresorhus/gulp-markdown?

**Comment by askesian** [comment]
Yes - it doesn't work:

### Source
```markdown
# Testing

## Test Title

* this
* is
* a test
```

### Assemble Task
```
return app.src(opts.src)
      .pipe(require('gulp-markdown')())
      .pipe(extname())
      .pipe(app.dest(opts.dest));
```

### Output

```markup

  # Testing

## Test Title

* this
* is
* a test
```

**Comment by askesian** [comment]
Ooops - I added it to the wrong assemble task. It does work. Thanks @jonschlinkert for the tip.
