### ISSUE TITLE
Duplicate files from different folders on consecutive runs

### ISSUE THREAD

**Issue by ghinda** [assemble/assemble#764]
When making consecutive `assemble` runs over different folders, the folders from a previous run will be duplicated/re-compiled in the new folder.

This is caused by the template caching in https://github.com/jonschlinkert/template-init.

When using the `minimal setup` option, the files are not duplicated, because `template-init` is not used.

Here's a quick example:

* With the directory structure:

```
/src
--one/one.hbs
--two/two.hbs
```

* When running:

```
assemble.src('src/one/*.hbs')
.pipe(assemble.dest('dist/one'));

assemble.src('src/two/*.hbs')
.pipe(assemble.dest('dist/two'));
```

* The `one.hbs` file will be present on both folders inside `dist/`:

```
/dist
--one/one.hbs
--two/one.hbs
--two/two.hbs
```

This happens regardless if the tasks are run in parallel or one after the other using `.on('end')`.

* This is because `one.hbs` is cached in `template-init` and recompiled on each `assemble` run.

The work-around I found is to use a "cache-buster" gulp plugin that excludes files not in the currently targeted folder.

```
var through = require('through2');

assemble.src('src/two/*.hbs')
.pipe(function() {

  return through.obj(function (file, enc, cb) {

    // return files only from the current folder
    if(file.path.indexOf('/two') !== -1) {
      return cb(null, file);
    }

    return cb(null);

  }, function (cb) {
    cb();
  });

}())
.pipe(assemble.dest('dist/two'));
```

I created a fully functioning demo of the problem here:
https://github.com/ghinda/assemble-duplicate-bug

**Comment by jonschlinkert** [comment]
this will be resolved in the pending release. thanks for reporting

**Comment by jonschlinkert** [comment]
resolved. we're no longer using template-init or any default plugins in the pending release (dev branch).
