### ISSUE TITLE
change signature of top-level export

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble#766]
currently we're exposing an instance of `Assemble`, so you can just use it directly without newing-up. 

e.g. 

```js
var assemble = require('assemble');
assemble.create('posts');

// to get the constructor you need to do
var Assemble = require('assemble').Assemble;
var assemble = new Assemble();
```

I think we should change this to expose the constructor instead of an instance. this way the user can easily create their own instances with options passed to the constructor. it would look like this:

```js
var assemble = require('assemble');

var app = assemble();
app.create('posts');

// new up again if you need a new instance
var site = assemble();
site.create('pages');
```

Thoughts? cc/ @doowb

**Comment by doowb** [comment]
If this is used in an `assemblefile.js` then we won't have access to the user's instance in `assemble-cli` to be able to run tasks.

I think we would need to change how the cli works and users would have to export their instance so the cli can use it.

```js
var Assemble = require('assemble');
var assemble = new Assemble();

// do awesome things

module.exports = assemble;
```

I do like this so they can use it however they want and only export the one they want to use. This will also allow publishing a module where the assemblefile is the main entry point and you can require it in and add things and re-export it in a new project.

**Comment by jonschlinkert** [comment]
hmm, all good points. I agree it would be nice to export a specific instance. and I like the express-like pattern of newing-up for the user. the point about the CLI is a case against it though IMHO. it might make things more complicated

**Comment by doowb** [comment]
I think it would work fine if we require assemble to be exported. We would still require in the `assemblefile` if found but give a nice error if the instance is missing. And it adds one line of code to assemblefiles. This will still allow a user to install assemble globally and use that instance so they don't have to have it in every project and it'll reduce the need for the cli to try to find the correct assemble module (local vs global).

**Comment by jonschlinkert** [comment]
done. in the next release we'll be exporting the `Assemble` constructor, so the user has control over instantiation.
