### ISSUE TITLE
Layouts Not Compiling/Rendering

### ISSUE THREAD

**Issue by leocreatini** [assemble/assemble#768]
Thanks for all the 0.6.0 docs so far, I've spent better half of the day catching up on it and reading past issues. My issue is that I cannot seem to get layouts to render. Here's my setup:

**Directory**
```
/app
    /templates
        /layouts
            *.hbs
        /pages
            *.hbs
        /partials
            *.hbs
/node_modules
    /assemble
```

**assembfile.js**
```
'use strict';

var Handlebars = require('handlebars'),
	assemble = require('assemble'),
	engines = require('consolidate'),
	helpers = require('handlebars-helpers'),
	rename = require('gulp-rename');

/* Cache Directories */
var paths = {
	dir: {
		app: 'app',
		dist: 'dist',
		test: 'test_',
		lay: 'app/templates/layouts'
	},
	files: {
		js: 'app/scripts/*.js',
		data: 'app/data/*.{json,yaml}',
		hbs: 'app/templates/**/*.hbs',
		layouts: 'app/templates/layouts/*.hbs',
		pages: 'app/templates/pages/*.hbs',
		partials: 'app/templates/partials/*.hbs',
		helpers: 'node_modules/handlebars-helpers/index.js'
	}
}; //paths{}

/* Options */
var options = {
		assemble: {
			data: paths.dir.data,
			partials: paths.files.partials,
			layout: paths.dir.lay + '/home.hbs',
			layouts: paths.dir.lay,
			helpers: paths.dir.helpers
		},
		register: {}
	},
	params = {
		grunt: {},
		assemble: assemble
	};

/* Register Helpers */
helpers.register(Handlebars, options.register, params);

/* Configure Assemble */
assemble.option('defaultLayout', 'home');
assemble.option('layoutExt', '.hbs');
assemble.engine('hbs', engines.handlebars);
assemble.data( paths.dir.data );
assemble.partials( paths.files.partials );
assemble.layouts( paths.files.layouts );

assemble.task('html', function() {
	return assemble.src(paths.files.pages)
		.pipe( rename( {extname: '.html'} ))
		.pipe( assemble.dest(paths.dir.test + paths.dir.dist) );

}); //html
```

**Current Output**
My src is the ```pages/*hbs``` that have front-matter at the top, with the ```layout: home``` for most of them. The pages are rendered, stripped of the YAML, ext renamed to ```.html```, and outputted to the test_dir directory.

**Background Info**
* The default handlebars engine was not working, so I ended up using one from Consolidate repo.

* I already renamed the layouts' ```{{> body }}``` to ```{% body %}``` to match the 0.6.0 API way of doing things.

* These files worked for the grunt build, but now the team is looking to switch to gulp/non-grunt to optimize performance.

* I'm loading the helpers via a temp fix from a previous issue: loading Handlebars, creating options/params, and then registering it.

**Thank you, Assemble Community**
Any help or tips are greatly appreciated, I feel like it's almost there, just missing one or two things.

**Comment by jonschlinkert** [comment]
Hi, at a first glance it seems that you're definitely not using the latest. Have a glance at [the dev branch](https://github.com/assemble/assemble/tree/dev), and be sure to take a look at the various unit tests for layouts and how they're registered and used.

Maybe start with [test/layouts.js](https://github.com/assemble/assemble/blob/dev/test/layouts.js), let us know if you have any questions.

**Comment by leocreatini** [comment]
My mistake, I thought 0.6.0-dev was the latest. :smile: 

I'll look at reconfiguring it to match the devs branch's docs and see if that works. I passed ~500 and failed 17 tests when I pulled the branch and did ```npm test```. Thanks for quick response, I'll see what I can do!

**Comment by jonschlinkert** [comment]
@leocreatini is this okay to close?

**Comment by leocreatini** [comment]
Hey Jon, yeah sorry. I ended up using gulp-grunt to use the working grunt's assemble:dist task as a hacky solution. I was unable to get the assemble file nor gulp-assemble to work with my build. Thanks for the support regardless.
