### ISSUE TITLE
Can't find CLI script for beta 6

### ISSUE THREAD

**Issue by criticalmash** [assemble/assemble#769]
I just installed "0.6.0-beta.6" and am trying to run the example in the readme.md file, but I can't find the CLI script. Previously (beta 5), I was seeing it in "assemble/bin/assemble.js" but the bin directory is gone.

I installed locally, and even tried a fresh install in a new project to see if it was just an issue with the upgrade. No luck.

Can someone point me in the right direction?

Thanks

**Comment by criticalmash** [comment]
Hi, still trying to figure this out. Any help would be appreciated.

Thanks

**Comment by doowb** [comment]
> I just installed "0.6.0-beta.6"

There hasn't been a "beta 6" published to npm. Are you installing assemble from one of the branches?

**Comment by criticalmash** [comment]
Yes, I installed from the dev branch. I wanted to use a version that matched the latest documentation.

But if it's not ready yet, I'll just play with beta 5 for now.

**Comment by jonschlinkert** [comment]
> I wanted to use a version that matched the latest documentation.

the docs on the readme of each branch are really only specific to that branch. this is exactly what we're working to clean up atm. sorry about any confusion

**Comment by criticalmash** [comment]
That's what I figured. If I download beat 5 and use the read me included, will I be using the right docs?

**Comment by jonschlinkert** [comment]
The latest branch is `dev`, and the docs on dev are better than the others - we're actively working on them.

closing since this is not technically an issue - we're working on docs right now. I promise you'll have something too look at soon :)
