### ISSUE TITLE
v0.6.0 including .hbs files or importing from strings

### ISSUE THREAD

**Issue by mkenney** [assemble/assemble#770]
Hi,

I'm pretty new to assemble and I'm struggling a bit so I'm looking for some guidance with an issue I'm having.

We're converting an existing (inherited) project that was built in v0.4 using `grunt` to `gulp` and at the same time making some fairly extensive changes to the site, turning around 30 individual pages into a long 1-pager. 

Rather than building one huge .hbs file I'm trying to set it up so we can keep all our individual documents separate as they are now and just compile them into a single page, so I'm wondering what the best way (or if there is even a valid way) to include and compile variable lists of files files or strings in a partial.  I'm pretty sure what I'm doing is an ugly hack but the result is very close to what I want.  The problem is that it seems that Assemble (or Handlebars, or my helpers, or something) is maintaining an indentation level in the HTML by adding space characters to the final output

Here's a trimmed-down version of my setup

**gulpfile.js**: There's more but this is the part I'm struggling with
```javascript
var assemble = require('assemble');
var handlebars = require('handlebars');
assemble.data([_conf_.src.docs.root+'/templates/data/*.{json,yml}']);
assemble.layouts(_conf_.src.docs.root+'/templates/layouts/*.hbs');
assemble.partials(_conf_.src.docs.root+'/templates/partials/*.hbs');
assemble.option('layout', 'default');
assemble.option('flatten', true);
assemble.option('assets', _conf_.dist.docs+'/assets');

// A couple of the helpers I'm using, these are where I'm having trouble

// This was part of the code I inherited, it's used for syntax-highlighting 
// blocks of code
assemble.helper('docsCode', function (lang, options) {
    var code = handlebars.Utils.escapeExpression(options.fn(this));
    var lines = code.split('\n');
    if (lines[0] === "") {
        lines.splice(0,1);
        code = lines.join('\n');
    }

    var output = [
        '<div class="docs-code">'
            , '<pre class="language-' + lang + '">'
                , '<code class="language-' + lang + '">'
                    , code
                , '</code>'
            , '</pre>'
        , '</div>'
    ].join('');

    return new handlebars.SafeString(output);
});

// This is how I'm trying to import files, by reading them 
// into a string
assemble.helper('importFromString', function (string) {
    var compiler = new handlebars.compile(string);
    return new handlebars.SafeString(compiler());
});

gulp.task('assemble-html', function (done) {
    assemble.task('html', function() {
        assemble.src([_conf_.src.docs.root+'/content/index.hbs'])
            .pipe(extname())
            .pipe(assemble.dest(_conf_.dist.docs))
            .on('error', function(e) {
                console.error(e.toString()+"\n");
            })
    });
    return assemble.run(['html'], done);
});
```

One of my partials has something like this in a loop, in each iteration "tabs" is data for one of the pages I want to include.  Here, "this.tabs.implementation.content" is the full contents of one of my .hbs files as a string
```markdown
{{#if this.tabs.implementation }}
<div class="tab-pane" id="{{as_id this.page}}-implementation">
{{importFromString this.tabs.implementation.content }}
</div>
{{/if}}
```

Inside of that string, there are some helper blocks using the docsCode helper, like so:
```javascript
{{#docsCode 'javascript'}}
$('#my-alert').bind('closed.bs.alert', function () {
    // do something…
})
{{/docsCode}}
```

All of this compiles (including helpers) and creates HTML files as expected except it seems like some HTML formatting is going on in the final output.  Some part of the process is maintaining the indentation level by inserting space characters, so the final output of that `docsCode` block is
```markdown
                <div class="docs-code"><pre class="language-javascript"><code class="language-javascript">$(&#x27;#my-alert&#x27;).bind(&#x27;closed.bs.alert&#x27;, function () {
                    // do something…
                })
                </code></pre></div>
```
instead of
```markdown
                <div class="docs-code"><pre class="language-javascript"><code class="language-javascript">$(&#x27;#my-alert&#x27;).bind(&#x27;closed.bs.alert&#x27;, function () {
    // do something…
})
</code></pre></div>
```

which normally wouldn't matter much but it's adding spaces to the contents of `pre` blocks. Prior to "including" the files this way using the `importFromString` helper, that wasn't happening, even though the formatting of the .hbs files hasn't changed.

I can't find where the spaces are coming from, they're not in the output of the `importFromString` helper when I console.log it so I assume it's something behind the scenes when assemble is putting it all together.  I tried taking out all extraneous whitespace in the imported string, partials and the layout, to no avail.

Any help would be **greatly** appreciated. And I don't mind taking a different approach if I'm doing something dumb :)  Thanks!

**Comment by doowb** [comment]
Have you tried using [whitespace control](http://handlebarsjs.com/expressions.html#whitespace-control) in your handlebars templates? Assemble doesn't do anything with whitespace, that's all controlled by the template rendering engine.

**Comment by jonschlinkert** [comment]
to clarify, assemble doesn't do anything at all to whitespace or with whitespace. that's all left to the template engine and how you setup your templates. You might consider using something like https://github.com/jonschlinkert/gulp-prettify, which uses js-beautify, which does a great job but it's still not 100% perfect

**Comment by mkenney** [comment]
Thanks to you both, @doowb had it, I wasn't familiar with [whitespace control](http://handlebarsjs.com/expressions.html#whitespace-control). The behavior was unexpected, it was indenting all lines in the string I gave it by the same amount of whitespace that preceded one of the `{{> partial}}` tags instead of just at the beginning and end of the full string, but telling handlebars not to do that was the solution: `{{~> partial~}}`

Thank you very much!

**Comment by jonschlinkert** [comment]
ha, I had this window open for a bit, apparently when I commented either @doowb's comment hadn't shown up or I just didn't see it lol. I was "clarifying" about assemble, not @doowb, sorry if that sounded like overkill! and glad you got it resolved
