### ISSUE TITLE
Collections in 0.6

### ISSUE THREAD

**Issue by Nooshu** [assemble/assemble#771]
Hello,

I've been a big fan of Assemble for quite a while now, excellent work! I'm just in the process of migrating some work from 0.4 using Grunt to 0.6 using Gulp (for the speed mainly). The only thing I am missing is the collections, e.g.

```
collections: [
                //Used for the overall index pages
                {
                    name: 'index',
                    sortby: 'index-name',
                    sortorder: 'ascending'
                },
                //Used for the content modules
                {
                    name: 'content-module',
                    sortby: 'content-module-number',
                    sortorder: 'ascending'
                },
                //Used for page templates
                {
                    name: 'thepage',
                    sortby: 'page-number',
                    sortorder: 'ascending'
                }
            ]
```

I understand that collections have yet to be added to 0.6, but is there any way I can mimic what they do using another method or maybe an additional plugin?

Any help would be appreciated.
Thanks!

**Comment by jonschlinkert** [comment]
> I understand that collections have yet to be added to 0.6, but is there any way I can mimic what they do using another method or maybe an additional plugin?

Well my friend you're in luck! You heard wrong, actually, collections are first class in 0.6.0 and are unbelievably awesome (no, seriously! collections are amazing in 0.6). You can create custom "view collections", or you can create generic collections for whatever you want to collect, but you can also create `lists` and `groups`.  I'll just cover view collections and lists below:

- **view collections**: create a collection for storing templates, like `pages`, `posts` or `docs`. To create a view collection, just do `app.create('posts')`. That adds two methods to assemble: `post` and `posts`. both are used to load views (templates) onto the `posts` collection (stored on `app.views.posts`)
- **lists**: lists are like collections but list `items` are stored as an array, allowing for grouping, sorting, and pagination (all built-in). 

Additionally, lists have `groupBy` and `sortBy` methods that allow you to easily sort and group by any number of properties on the context.

Here are some examples:

**view collections**

Example of how you can create a custom view collection.

```js
var assemble = require('assemble');
var app = assemble();

// create a custom collection, optionally pass options as the second arg
app.create('posts');

// now we can add "posts" with either of the following
app.post('abc.md', {content: '....'}); 
app.posts('xyz.md', {content: '....'});
```

Both will add a view to `app.views.posts`, but the singular form returns the actual view, so `view` methods can be chained from it, and the plural form returns the `posts` instance, so collection methods can be chained from it. Also the plural form will load objects or arrays of views as well. For example, here is the singular:

```js
// this is a single post, we'll use it's `render` method to
// render templates in the post's `content`
app.post('abc.md', {content: '....'});
  .render(function(err, res) {
  })
```

**Grouping and sorting**

This is just a small glimpse of what is implemented in 0.6.0

```js
var assemble = require('assemble');
var List = assemble.List;
var items = [
  { path: 'a.md', locals: { date: '2014-01-01', foo: 'zzz', bar: 1 } },
  { path: 'f.md', locals: { date: '2014-01-01', foo: 'mmm', bar: 2 } },
  { path: 'd.md', locals: { date: '2014-01-01', foo: 'xxx', bar: 3 } },
  { path: 'i.md', locals: { date: '2014-01-01', foo: 'xxx', bar: 5 } },
  { path: 'k.md', locals: { date: '2014-01-01', foo: 'xxx', bar: 1 } },
  { path: 'j.md', locals: { date: '2014-01-01', foo: 'xxx', bar: 4 } },
  { path: 'h.md', locals: { date: '2014-01-01', foo: 'xxx', bar: 6 } },
  { path: 'l.md', locals: { date: '2014-01-01', foo: 'xxx', bar: 7 } },
  { path: 'e.md', locals: { date: '2015-01-02', foo: 'aaa', bar: 8 } },
  { path: 'b.md', locals: { date: '2012-01-02', foo: 'ccc', bar: 9 } },
  { path: 'f.md', locals: { date: '2014-06-01', foo: 'rrr', bar: 10 } },
  { path: 'c.md', locals: { date: '2015-04-12', foo: 'ttt', bar: 11 } },
  { path: 'g.md', locals: { date: '2014-02-02', foo: 'yyy', bar: 12 } },
];

var list = new List();
list.addList(items);

var grouped = list
  .sortBy('locals.date')
  .groupBy(function (view) {
    var date = view.locals.date;
    view.locals.year = date.slice(0, 4);
    view.locals.month = date.slice(5, 7);
    view.locals.day = date.slice(8, 10);
    return view.locals.year;
  }, 'locals.month');

console.log(grouped)
```
Results in something like:

```js
{
  '2012': { '01': [ <View "b.md"> ] },
  '2014':
   { '01':
      [ <View "h.md">,
        <View "d.md">,
        <View "i.md">,
        <View "k.md">,
        <View "j.md">,
        <View "f.md">,
        <View "l.md">,
        <View "a.md"> ],
     '02': [ <View "g.md"> ],
     '06': [ <View "f.md"> ] },
  '2015': { '01': [ <View "e.md"> ], '04': [ <View "c.md"> ] }
```

Is this what you're looking for?

There is also pagination, permalinks, and a bunch of other great features in 0.6. docs are on the way!

**Comment by Nooshu** [comment]
Wow... what an awesome comment, Thanks Jon, you have made my evening! Looking forward to the documentation for the other features! I will report back in the next couple of days if I have any questions.

Thanks again!

**Comment by Nooshu** [comment]
Actually, just thinking now, can you add items to lists using front-matter once the lists / groups / view collections have been initialised?

Like i did this in 0.4...
```
---
title: "Templates"
layout: "index"
---
```

These pages would be added to the index collection. Is something similar possible in 0.6?

Thanks again!

**Comment by jonschlinkert** [comment]
I think it would be pretty easy to do, and you'd have your choice of a few different ways to do it based on how you need it done. 

For example, you could do this with a middleware. A middleware is just a function that exposes the `view` object and `next`. After you do something to `view`, call `next` to move onto the next middleware:

```js
function(view, next) {
  // do something to view
  next();
}
```

This is how you would define a middleware for parsing front matter (this might be included the 0.6. release by default, haven't decided yet, feel free to share your thoughts):

```js
var matter = require('parser-front-matter');

app.onLoad(/\.hbs$/, function (view, next) {
  matter.parse(view, next);
});
```

Above, `view` is a template (vinyl file actually), and any front-matter that's parsed from `view.contents` will be added to `view.data` and then merged into the context at render time, pretty similar to 0.4.x assemble.

Inside the middleware function you can do whatever you want with `view` or its data. So, given your example above, the  `view.data` object for that particular template would look something like this:

```js
{ title: 'Templates', layout: 'index' }
```

I know this isn't what you're asking for specifically, but the point is that we've tried to make it really easy to extend assemble to do whatever you need to with the templates and their data.

Maybe also take a look at these to get some ideas:

- https://github.com/doowb/paginationator
- https://github.com/assemble/assemble-indexer

**Comment by jonschlinkert** [comment]
oh, almost forgot, another way to do this would be to use a pipeline plugin (can be a gulp plugin, or exactly the same signature as a gulp plugin). @doowb any other thoughts?

**Comment by doowb** [comment]
[This example](https://github.com/assemble/assemble-indexer/blob/master/examples/archives.js) is a good one for showing how to build up an archive collection based on front-matter contained in views in other collections.

Since people use collections in different ways we wanted to build methods that help create/sort/group/paginate lists and use them however they choose. Using these methods you can build up your own collections based on the front-matter in your pages and use the list in middleware, plugins, and or helpers.

As @jonschlinkert mentioned, the docs are on their way, but if you have a project with an `assemblefie.js`, we could take a look to see if we can help with anything specific you're trying to do.

**Comment by jonschlinkert** [comment]
closing since this was more of a question than an issue.
