### ISSUE TITLE
build only changed files with grunt-newer dosen't work

### ISSUE THREAD

**Issue by tobiasharth** [assemble/assemble#772]
Hey there,

i will use Assemble like the description on the [installation-site](http://assemble.io/docs/Installation.html#add-grunt-newer-to-speed-up-builds) with the grunt-newer task, but it build always the whole page with 1000+ pages.

My Assemble task in the Gruntfile: 
```
 assemble: {
      options: {
        assets: "contents/assets",
        data: "config.json",
        layoutdir: "templates",
        layout: "default.hbs",
        partials: "templates/partials/**/*.hbs",
        helpers: ["lib/helpers/*.js" ]
      },
      project: {
        options: {},
        files: {
          "sites/_default/public": ["contents/**/*.md" ]
        }
      }
    },
```

The content tree is like:
```
|- contents
    |--- docs
    |     |--- current
    |           |--- lorem ipsum
    |                 |--- lorem-ipsum.md
    |--- versions
    |     |--- v.1.0.1
    |     |--- v.1.0.2
    |     |--- v.1.0.3
    |           |--- lorem ipsum
    |                 |--- lorem-ipsum.md
    |--- product
    |--- start
```

What is wronge? Do you support grunt-newer with single changed files? Is there a failure in grunt-newer or in my Gruntfile?

Cheers, 
Tobi

**Comment by jonschlinkert** [comment]
Please reopen on the [grunt-assemble issues](https://github.com/assemble/grunt-assemble), thanks
