### ISSUE TITLE
Tip: Bootstrap Template Another Way (BTAW)

### ISSUE THREAD

**Issue by pacav69** [assemble/assemble#776]
I've created a Bootstrap Template that uses assemble, grunt and bower components.
It illustrates of how to create reusable parts of a template to create single or multi-page webpages using bootstrap. It also includes details of using Table Of Contents (TOC), Markdown files and bower components.

https://github.com/pacav69/btaw/

**Comment by jonschlinkert** [comment]
thanks for letting us know! we'll add to the grunt-assemble docs when we make updates
