### ISSUE TITLE
Error passing parameter into partial

### ISSUE THREAD

**Issue by matthewtrinder** [assemble/assemble#781]
**From the [Handlebars docs](http://handlebarsjs.com/partials.html):** 
> Custom data can be passed to partials through hash parameters.
> {{> myPartial parameter=value }}
> Will set **parameter** to **value** when the partial runs.

**However I'm getting the following error when trying to do this with assemble:**

```
Warning: Parse error on line 10:
...simple-nav-item test="test" }}         
-----------------------^
Expecting 'CLOSE', 'CLOSE_UNESCAPED', 'STRING', 'INTEGER', 'BOOLEAN', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'DATA', 'SEP', got 'EQUALS'
```
**The .hbs file being processed contains:**

`{{> inc-simple-nav-item test="test" }}`

** My version of assemble is: **

`"assemble": "^0.4.42",`

Any ideas? Not implemented in assemble?
Really appreciate any help on this one!

Thanks,
Matt

**Comment by avr** [comment]
I believe that was an addition made to a more recent edition of Handlebars.  This works in v0.6.0.

**Comment by matthewtrinder** [comment]
Works with assemble 0.6.0 - **closing**
