### ISSUE TITLE
Migrating to 0.6.0-beta5

### ISSUE THREAD

**Issue by rparree** [assemble/assemble#784]
Hi i am (trying to) migrate from 0.4.42. It has not been easy so far.

The docs [docs/_verb/helpers.md](https://github.com/assemble/assemble/blob/d75ae80efa0fef63ad4ab8768cdad0e3837ff3ac/docs/_verb/helpers.md) states the handlebars-helpers should work without any additional setup. I am however getting 
````
Error: Missing helper: "formatDate"
````
I tried registering like

```javascript
assemble.helpers(require('handlebars-helpers'));
```

But that did not help. Am i missing something?

tx.,

**Comment by jonschlinkert** [comment]
Sorry, the `_verb` folder contains docs templates that haven't been actually generated into docs yet. The branch we're currently working from is `dev`. There is also a [dev branch on handlebars-helpers](https://github.com/assemble/handlebars-helpers/tree/dev) that is more up to date. 

If you want to to work with a stable version of assemble, I suggest giving `assemble-core` a try. There are examples in the `./examples` directory, and almost 900 unit tests to help you get started.

**Comment by rparree** [comment]
What is the difference between `assemble-core` and `assemble`? Do i still need to install `assemble`? Looking at the documentation it looks like it:

```
var assemble = require('assemble');
var app = assemble();
```
Too be honest i am a little bit lost...I have the feeling i am missing an important change of concept between 0.4.x and 0.6.x.  have a running site in production on 0.4.42.  I might just abandon the migration (did get far, was just working on the helpers above and trying to figure out how permalinks need to be setup).

**Comment by jonschlinkert** [comment]
Have you looked at the readme for assemble-core? It's fairly detailed. Regarding the differences, I've answered the question about differences many times on other issues. assemble will build on top of assemble-core, and will add a CLI, default template collections, like `pages`, `layouts` and `partials`, and other defaults that will make the transition to assemble 0.6.0 easier for grunt-assemble users. 

we'll soon be releasing docs that cover the details. In the meantime, we have very little time to provide support for transitioning. We'd love to add people to the core team to help with this!

**Comment by rparree** [comment]
I am trying to use `assemble-core` (using the examples and test cases as a reference). Great work, but  still i am stuck. I'll post my question over at 'assemble-core'.
Thanks.
