### ISSUE TITLE
Change delimiters

### ISSUE THREAD

**Issue by brunowego** [assemble/assemble#785]
Have a way to change native delimiters? I wish use with Angular.

```
{{ var }}
```

Replace to:

```
{% var %}
```

**Comment by jonschlinkert** [comment]
What version of assemble? are you using assemble or grunt-assemble?

**Comment by brunowego** [comment]
@jonschlinkert `grunt-assemble`, thanks!

**Comment by jonschlinkert** [comment]
Ok, would you mind recreating on that repo? thanks!
