### ISSUE TITLE
Build callback in grunt

### ISSUE THREAD

**Issue by funkage** [assemble/assemble#786]
Hello guys, I've been search high and low for reference on this but to no avail, thus my presence here.

**Background**
I'm running multiple assemble targets and would like to add a callback that copies a folder of assets (CSS, JS, etc) to the destination directory every time a target build is complete—preferably by referencing to a `grunt-contrib-copy` module already present.

**What does the grunt file look like?**
```
// some grunt configs
assemble: {

            options: {
                site:         '<%= site %>',
                assets:       '<%= site.assets %>',
                data:         '<%= site.data %>',
                helpers:      '<%= site.helpers %>',
                layout:       '<%= site.layout %>',
                layoutdir:    '<%= site.layouts %>',
                partials:     '<%= site.includes %>',
                plugins:      '<%= site.plugins %>'
            },

            target_1: { options: { site_id: 'foobar' }, expand: true, cwd: '<%= site.pages %>/foo/bar', src: '<%= site.pages_src %>', dest: '<%= site.dest %>/foo/bar' },
            target_2: { options: { site_id: 'foobar2' }, expand: true, cwd: '<%= site.pages %>/foo/bar2', src: '<%= site.pages_src %>', dest: '<%= site.dest %>/foo/bar2' }

        }
// more grunt configs
```

I'm aware of the `build` method found on [this page] (http://assemble.io/docs/Methods.html) but I haven't been able to figure out on how to implement it within the grunt file.

Thank you for taking time to read this and activating your brain cells in coming up with an answer.

**Comment by jonschlinkert** [comment]
Sorry to make you do this, but would you mind reopening on the grunt-assemble repo? you can just link to this one if it's easier. thanks!
