### ISSUE TITLE
Docs refer to "Block" target instead of "Blog"

### ISSUE THREAD

**Issue by betsydupuis** [assemble/assemble#787]
I think that `block` code snippet should say "blog" instead. 
http://assemble.io/docs/Pages-Collections.html

<img width="808" alt="screen shot 2015-12-17 at 2 00 48 am" src="https://cloud.githubusercontent.com/assets/2096627/11864447/29369324-a462-11e5-8823-a66f14ee188f.png">

**Comment by jonschlinkert** [comment]
closing since this is for a different repository, but it's been noted. thank you
